import { resolvePlatformKnowledge } from '../knowledge/recovery-activation-resolver.js';

const issue=(code,context,extra={})=>({code,severity:extra.blocking===false?'attention':'critical',blocking:extra.blocking!==false,category:extra.category??'COMPLETION',module_id:extra.module_id??'assets-accounts',field_id:extra.field_id??null,entity_id:extra.entity_id??context.asset_id??null,platform_label:context.platform_label??'未选择平台',asset_label:context.asset_label??'未命名账户',condition_label:context.condition_label??null,current_value:extra.current_value??null,temporary_state:extra.temporary_state??null,message_key:code,why_needed:extra.why_needed??'该信息是第一层恢复路径的一部分。',how_to_fix:extra.how_to_fix??'打开目标字段并补充。',skippable:extra.blocking===false,escalation:extra.escalation??'NONE',navigation_target:{module_id:extra.module_id??'assets-accounts',entity_id:extra.entity_id??context.asset_id??null,field_id:extra.field_id??null}});
const validAttachment=file=>Number.isSafeInteger(file?.byte_length)&&file.byte_length>0&&file.bytes?.byteLength===file.byte_length&&/^[a-f0-9]{64}$/.test(file.sha256??'')&&Boolean(file.media_type)&&Boolean(file.module_refs?.length)&&Boolean(file.account_id)&&Boolean(file.field_id)&&Boolean(file.purpose_id);

export function evaluateActivationRules(draft,{activationConfig,claims=[],attachments=[],now=new Date().toISOString()}={}){
  const assets=draft?.modules?.['assets-accounts']?.entries??[],summaries=draft?.modules?.['recovery-conditions']?.entries??[],locations=draft?.modules?.['locations-finding']?.entries??[],steps=draft?.modules?.['recovery-order-exceptions']?.entries??[],issues=[],cex=new Set(['binance','okx','coinbase']),factorLabel=id=>activationConfig.factors.find(item=>item.id===id)?.label??id;
  for(const asset of assets){const platformLabel=activationConfig.supported_platforms.find(item=>item.id===asset.platform)?.label??asset.platform,context={asset_id:asset.client_id,asset_label:asset.nickname?`${platformLabel} · ${asset.nickname}`:platformLabel||'未命名账户',platform_label:platformLabel};
    if(!asset.platform)issues.push(issue('ACCOUNT_PLATFORM_REQUIRED',context,{field_id:'platform',how_to_fix:'选择平台或“其他/自定义”。'}));
    if(cex.has(asset.platform)&&!asset.registration_geography)issues.push(issue('ACCOUNT_REGION_REQUIRED',context,{field_id:'registration_geography',how_to_fix:'选择该托管账户所属国家或地区。'}));
    if(cex.has(asset.platform)&&!asset.account_class)issues.push(issue('ACCOUNT_CLASS_REQUIRED',context,{field_id:'account_class',how_to_fix:'选择个人或机构账户。'}));
    if(asset.account_class&&asset.account_class!=='Personal')issues.push(issue('PERSONAL_ACCOUNT_ONLY',context,{field_id:'account_class',why_needed:'当前版本只支持普通个人账户。',how_to_fix:'不要套用个人模板；请使用官方或人工升级。',escalation:'OFFICIAL_SUPPORT'}));
    if(assets.filter(item=>item.platform&&item.platform===asset.platform).length>1&&!asset.nickname?.trim())issues.push(issue('ACCOUNT_NICKNAME_REQUIRED',context,{field_id:'nickname',why_needed:'同平台账户必须可区分。',how_to_fix:'填写不同的备注名称。'}));
    const summary=summaries.find(item=>item.asset_ref===asset.client_id),selected=summary?.selected_conditions??[];
    if(!selected.length)issues.push(issue('CONDITION_SELECTION_REQUIRED',context,{module_id:'recovery-conditions',entity_id:summary?.client_id,field_id:'selected_conditions',why_needed:'每个账户至少需要一项可执行的恢复条件。',how_to_fix:'勾选至少一个实际适用的条件。'}));
    for(const factorId of summary?.unknown_conditions??[])issues.push(issue('CONDITION_NOT_READY',{...context,condition_label:factorLabel(factorId)},{module_id:'recovery-conditions',entity_id:summary.client_id,field_id:'selected_conditions',temporary_state:'UNKNOWN',current_value:'UNKNOWN',how_to_fix:'确认后勾选适用条件，或移除该临时状态。'}));
    for(const factorId of summary?.later_conditions??[])issues.push(issue('CONDITION_NOT_READY',{...context,condition_label:factorLabel(factorId)},{module_id:'recovery-conditions',entity_id:summary.client_id,field_id:'selected_conditions',temporary_state:'LATER',current_value:'LATER',how_to_fix:'完成补充后勾选适用条件。'}));
    for(const factorId of selected){const conditionId=`condition-${asset.client_id}-${factorId}`,location=locations.find(item=>item.condition_ref===conditionId),fieldContext={...context,condition_label:factorLabel(factorId)},summaryValue=draft.location_summaries?.[asset.client_id],summaryFile=attachments.some(file=>validAttachment(file)&&file.account_id===asset.client_id&&file.field_id==='summary_instructions'&&file.coverage_condition_ids?.includes(conditionId)),covered=Boolean(location?.covered_by_summary&&(summaryValue?.instructions?.trim()||summaryFile));
      if(!location)issues.push(issue('CONDITION_LOCATION_REQUIRED',fieldContext,{module_id:'locations-finding',field_id:'type',how_to_fix:'为该条件添加逐项位置或汇总覆盖。'}));
      else if(!covered){const files=attachments.filter(file=>validAttachment(file)&&file.owner_entity_refs?.includes(location.client_id));if(!location.type)issues.push(issue('LOCATION_TYPE_REQUIRED',fieldContext,{module_id:'locations-finding',entity_id:location.client_id,field_id:'type',how_to_fix:'选择位置类型，或使用有效汇总覆盖。'}));if(!location.label?.trim())issues.push(issue('LOCATION_NAME_REQUIRED',fieldContext,{module_id:'locations-finding',entity_id:location.client_id,field_id:'label',how_to_fix:'填写位置名称，或使用有效汇总覆盖。'}));if(!location.finding_instructions?.trim()&&!files.length)issues.push(issue('LOCATION_CONTENT_REQUIRED',fieldContext,{module_id:'locations-finding',entity_id:location.client_id,field_id:'finding_instructions',why_needed:'未来恢复人需要知道从哪里找到该条件。',how_to_fix:`填写${factorLabel(factorId)}的位置说明，或上传并覆盖该条件的有效附件。`}));}
    }
    const step=steps.find(item=>item.asset_ref===asset.client_id),stepFiles=attachments.filter(file=>validAttachment(file)&&file.owner_entity_refs?.includes(step?.client_id)&&file.purpose_id==='recovery-steps');if(!step||!step.action?.trim()&&!stepFiles.length)issues.push(issue('STEP_CONTENT_REQUIRED',context,{module_id:'recovery-order-exceptions',entity_id:step?.client_id,field_id:'action',why_needed:'未来恢复人需要一条可以执行的恢复与转移路径。',how_to_fix:'填写恢复与转移步骤，或上传属于该账户的步骤附件。'}));if(step&&!step.saved)issues.push(issue('PLATFORM_SAVE_REQUIRED',context,{module_id:'recovery-order-exceptions',entity_id:step.client_id,field_id:'saved',why_needed:'对象级保存用于确认该平台当前内容。',how_to_fix:'点击“保存该平台”。'}));
    if(asset.platform&&asset.registration_geography&&asset.account_class){const resolution=resolvePlatformKnowledge({...asset,platform:asset.platform},claims,{now});if(resolution.conservative)issues.push(issue('CONSERVATIVE_REGION_FALLBACK',context,{blocking:false,category:'KNOWLEDGE_INFO',why_needed:'当前地区没有完全匹配的Approved知识。',how_to_fix:'执行前以当前官方流程为准。',escalation:'OFFICIAL_SUPPORT'}));}
  }
  for(const file of attachments)if(!validAttachment(file))issues.push(issue('ATTACHMENT_INVALID',{asset_id:file.account_id,asset_label:assets.find(item=>item.client_id===file.account_id)?.nickname??'附件',platform_label:assets.find(item=>item.client_id===file.account_id)?.platform??'附件'},{module_id:file.source_module_id??'evidence-messages',entity_id:file.id,field_id:'attachment',category:'SECURITY',why_needed:'附件必须非空、完整、可读取且归属明确。',how_to_fix:'删除无效附件并从具体条目重新上传。'}));
  if(!assets.length)issues.push(issue('ASSET_REQUIRED',{},{field_id:'assets',why_needed:'Recovery Map至少需要一个账户。',how_to_fix:'添加一个资产账户。'}));
  const key=item=>[item.code,item.module_id,item.entity_id,item.field_id,item.condition_label].join('|'),unique=[...new Map(issues.map(item=>[key(item),item])).values()],blocking=unique.filter(item=>item.blocking),attention=unique.filter(item=>!item.blocking);return{valid:blocking.length===0,blocking,attention,issues:unique};
}
