import { ASSISTANCE_STATES,clone,field,nowIso,selectedConditions } from './model.js';

const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{2,127}$/;
function mutate(store,expectedRevision,clock,fn){if(store.version.status==='GENERATED')throw new Error('GENERATED_VERSION_IMMUTABLE');if(store.draft_revision!==expectedRevision)throw new Error('STALE_DRAFT_REVISION');const next=clone(store);fn(next);next.draft_revision++;next.version.draft_revision=next.draft_revision;next.version.status='DRAFT';next.updated_at=nowIso(clock);return next;}
const requireAccount=(store,id)=>{const account=store.accounts[id];if(!account)throw new Error('ACCOUNT_NOT_FOUND');return account;};

export const ProductActions={
  addAccount(store,{account_id,platform_id,platform_name='',region='',account_type='',display_label=''},options={}){if(!ID.test(account_id??'')||store.accounts[account_id])throw new Error('INVALID_ACCOUNT_ID');return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{const now=nowIso(options.clock);next.accounts[account_id]={account_id,platform_id,platform_name,region:field(region),account_type:field(account_type),display_label,created_at:now,updated_at:now};next.condition_selections[account_id]={account_id,selected_condition_ids:[],custom_conditions:[],optional_notes:'',related_attachment_ids:[]};next.recovery_instructions[account_id]={account_id,instruction_text:'',instruction_attachment_ids:[],optional_risk_notes:'',optional_risk_attachment_ids:[],saved_at:null};});},
  updateAccount(store,accountId,changes,options={}){return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{const account=requireAccount(next,accountId);for(const key of ['platform_id','platform_name','display_label'])if(key in changes)account[key]=String(changes[key]??'');for(const key of ['region','account_type'])if(key in changes)account[key]=typeof changes[key]==='object'?clone(changes[key]):field(changes[key]);account.updated_at=nowIso(options.clock);});},
  removeAccount(store,accountId,{confirmCascade=false,...options}={}){if(!confirmCascade)throw new Error('CASCADE_CONFIRMATION_REQUIRED');return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{requireAccount(next,accountId);delete next.accounts[accountId];delete next.condition_selections[accountId];delete next.recovery_instructions[accountId];for(const[id,value]of Object.entries(next.location_coverages))if(value.account_id===accountId)delete next.location_coverages[id];for(const[id,value]of Object.entries(next.attachments))if(value.account_id===accountId)delete next.attachments[id];});},
  setConditionSelection(store,accountId,{selected_condition_ids=[],custom_conditions=[],optional_notes},options={}){return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{requireAccount(next,accountId);const selection=next.condition_selections[accountId],unique=[...new Set(selected_condition_ids)];selection.selected_condition_ids=unique;selection.custom_conditions=clone(custom_conditions);if(optional_notes!==undefined)selection.optional_notes=String(optional_notes);for(const[id,coverage]of Object.entries(next.location_coverages)){if(coverage.account_id!==accountId)continue;coverage.covered_condition_ids=coverage.covered_condition_ids.filter(value=>unique.includes(value));if(!coverage.covered_condition_ids.length)delete next.location_coverages[id];}for(const attachment of Object.values(next.attachments))if(attachment.account_id===accountId)attachment.covered_condition_ids=attachment.covered_condition_ids.filter(value=>unique.includes(value));});},
  upsertCoverage(store,coverage,options={}){if(!ID.test(coverage.coverage_id??'')||!['ITEMIZED','SUMMARY'].includes(coverage.mode))throw new Error('INVALID_COVERAGE');return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{requireAccount(next,coverage.account_id);const selected=new Set(selectedConditions(next,coverage.account_id)),covered=[...new Set(coverage.covered_condition_ids??[])];if(!covered.length||covered.some(id=>!selected.has(id)))throw new Error('COVERAGE_CONDITION_NOT_SELECTED');for(const[id,item]of Object.entries(next.location_coverages))if(id!==coverage.coverage_id&&item.account_id===coverage.account_id&&item.covered_condition_ids.some(value=>covered.includes(value)))throw new Error('DUPLICATE_CONDITION_COVERAGE');next.location_coverages[coverage.coverage_id]={coverage_id:coverage.coverage_id,account_id:coverage.account_id,mode:coverage.mode,covered_condition_ids:covered,location_type:String(coverage.location_type??''),location_name:String(coverage.location_name??''),description:String(coverage.description??''),attachment_ids:[...new Set(coverage.attachment_ids??[])],created_at:next.location_coverages[coverage.coverage_id]?.created_at??nowIso(options.clock),updated_at:nowIso(options.clock)};});},
  removeCoverage(store,coverageId,options={}){return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{if(!next.location_coverages[coverageId])throw new Error('COVERAGE_NOT_FOUND');delete next.location_coverages[coverageId];});},
  updateInstruction(store,accountId,changes,options={}){return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{const instruction=next.recovery_instructions[accountId];requireAccount(next,accountId);if(!instruction)throw new Error('INSTRUCTION_NOT_FOUND');for(const key of ['instruction_text','optional_risk_notes'])if(key in changes)instruction[key]=String(changes[key]??'');for(const key of ['instruction_attachment_ids','optional_risk_attachment_ids'])if(key in changes)instruction[key]=[...new Set(changes[key]??[])];instruction.saved_at=null;});},
  confirmInstructionSaved(store,accountId,options={}){return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{requireAccount(next,accountId);next.recovery_instructions[accountId].saved_at=nowIso(options.clock);});},
  setAssistantDecision(store,decision,options={}){if(!ASSISTANCE_STATES.includes(decision))throw new Error('INVALID_ASSISTANCE_DECISION');return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{next.assistant_decision=decision;if(decision!=='NEED')next.assistants={};});},
  upsertAssistant(store,assistant,options={}){if(!ID.test(assistant.assistant_id??''))throw new Error('INVALID_ASSISTANT_ID');return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{next.assistants[assistant.assistant_id]={assistant_id:assistant.assistant_id,role:String(assistant.role??''),contact_timing:String(assistant.contact_timing??''),allowed_help:String(assistant.allowed_help??''),permission_boundary:String(assistant.permission_boundary??'')};});},
  removeAssistant(store,assistantId,options={}){return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{delete next.assistants[assistantId];});},
  setPersonalMessage(store,message,options={}){return mutate(store,options.expected_revision??store.draft_revision,options.clock,next=>{next.personal_message=message?{text:String(message.text??''),attachment_ids:[...new Set(message.attachment_ids??[])],updated_at:nowIso(options.clock)}:null;});}
};

export function applyAction(memoryStore,action,...args){const current=memoryStore.read(),next=action(current,...args,{expected_revision:current.draft_revision});return memoryStore.commit(next,current.draft_revision);}
