import { clone,nowIso,selectedConditions } from './model.js';
import { cryptoEngine } from '../crypto/crypto-engine.js';
import { assertAttachmentAllowed,resolveAttachmentMime } from '../ui/attachment-policy.js';

const normalizeMime=value=>String(value??'').trim().toLowerCase().split(';')[0];
const assertScope=(store,input)=>{const account=store.accounts[input.account_id];if(!account||account.platform_id!==input.platform_id)throw new Error('ATTACHMENT_OWNER_INVALID');if(!input.module_id||!input.field_or_condition_id||!input.purpose)throw new Error('ATTACHMENT_SCOPE_INVALID');if((input.covered_condition_ids??[]).some(id=>!selectedConditions(store,input.account_id).includes(id)))throw new Error('ATTACHMENT_COVERAGE_INVALID');};
const totals=store=>Object.values(store.attachments).reduce((sum,item)=>sum+item.byte_length,0);
export function attachmentCapacity(store,rules){const used=totals(store),count=Object.keys(store.attachments).length;return{used_bytes:used,remaining_bytes:Math.max(0,rules.limits.max_version_bytes-used),count,remaining_count:Math.max(0,rules.limits.max_attachments-count)};}
export async function addAttachment(store,input,{rules,policy,clock,hash=bytes=>cryptoEngine.hashHex(bytes)}={}){assertScope(store,input);const candidate=input.file??{name:input.file_name,type:input.mime_type,size:input.byte_length??input.bytes?.byteLength};if(policy)assertAttachmentAllowed(candidate,Object.values(store.attachments),policy);const bytes=input.bytes instanceof Uint8Array?new Uint8Array(input.bytes):new Uint8Array(await input.file.arrayBuffer()),size=input.byte_length??input.file?.size??bytes.byteLength,mime=normalizeMime(policy?resolveAttachmentMime(candidate,policy):input.mime_type??input.file?.type);if(!bytes.byteLength||bytes.byteLength!==size)throw new Error('ATTACHMENT_BYTES_INVALID');if(!mime)throw new Error('ATTACHMENT_MIME_REQUIRED');const limits=policy?.limits??rules?.limits;if(!limits||size>limits.max_attachment_bytes||Object.keys(store.attachments).length>=limits.max_attachments||totals(store)+size>limits.max_version_bytes)throw new Error('ATTACHMENT_CAPACITY_EXCEEDED');const sha256=await hash(bytes);if(!/^[a-f0-9]{64}$/.test(sha256))throw new Error('ATTACHMENT_HASH_INVALID');const next=clone(store),now=nowIso(clock),id=input.attachment_id;if(!id||next.attachments[id])throw new Error('ATTACHMENT_ID_INVALID');next.attachments[id]={attachment_id:id,file_name:String(input.file_name??input.file?.name??'attachment.bin').normalize('NFC'),mime_type:mime,byte_length:size,sha256,module_id:input.module_id,platform_id:input.platform_id,account_id:input.account_id,field_or_condition_id:input.field_or_condition_id,purpose:input.purpose,covered_condition_ids:[...new Set(input.covered_condition_ids??[])],created_at:now,updated_at:now,technical_status:'VALID',bytes};next.draft_revision++;next.version.draft_revision=next.draft_revision;next.version.status='DRAFT';next.updated_at=now;return next;}
export async function replaceAttachment(store,id,replacement,options){const old=store.attachments[id];if(!old)throw new Error('ATTACHMENT_NOT_FOUND');const base=clone(store);delete base.attachments[id];const candidate={...old,...replacement,attachment_id:id,created_at:old.created_at};if(replacement.file&&!Object.hasOwn(replacement,'bytes'))delete candidate.bytes;const next=await addAttachment(base,candidate,options);next.attachments[id].created_at=old.created_at;return next;}
export function removeAttachment(store,id,{clock}={}){if(!store.attachments[id])throw new Error('ATTACHMENT_NOT_FOUND');const next=clone(store);delete next.attachments[id];for(const coverage of Object.values(next.location_coverages))coverage.attachment_ids=coverage.attachment_ids.filter(value=>value!==id);for(const instruction of Object.values(next.recovery_instructions)){instruction.instruction_attachment_ids=instruction.instruction_attachment_ids.filter(value=>value!==id);instruction.optional_risk_attachment_ids=instruction.optional_risk_attachment_ids.filter(value=>value!==id);}if(next.personal_message)next.personal_message.attachment_ids=next.personal_message.attachment_ids.filter(value=>value!==id);next.draft_revision++;next.version.draft_revision=next.draft_revision;next.version.status='DRAFT';next.updated_at=nowIso(clock);return next;}
export function reassignAttachment(store,id,changes,{clock}={}){const next=clone(store),file=next.attachments[id];if(!file)throw new Error('ATTACHMENT_NOT_FOUND');const candidate={...file,...changes};assertScope(next,candidate);Object.assign(file,candidate,{updated_at:nowIso(clock)});next.draft_revision++;next.version.draft_revision=next.draft_revision;next.updated_at=nowIso(clock);return next;}
