import { MODULE_IDS,accountAttachments,accountLabel,selectedConditions } from './model.js';
import { assertReceiptMatches } from './validator.js';
import { assertGenerationPreflightMatches,generationPreflightFor } from './generation-preflight.js';

export const REPORT_LABELS=Object.freeze({
  conditions:{email:'注册邮箱',phone:'注册手机号',password:'登录密码',authenticator:'Authenticator',passkey:'Passkey',security_key:'Security Key',identity:'身份验证材料',new_device:'新设备确认',withdrawal_whitelist:'提币地址白名单',fund_password:'资金或交易密码',other:'其他恢复条件'},
  coverage_modes:{SUMMARY:'汇总位置',ITEMIZED:'逐项位置'},
  modules:{accounts:'资产与账户资料',conditions:'恢复所需材料和条件',locations:'位置与查找说明',instructions:'恢复与转移步骤',assistants:'协助人资料',message:'给未来恢复人的嘱托'},
  account_types:{Personal:'个人账户',Institutional:'机构账户'},
  assistance:{NOT_SET:'尚未设置',NEED:'需要协助',NOT_NEEDED:'不需要协助',UNKNOWN:'暂不确定'}
});
const conditionName=(id,platformTemplates,account,conditionLabelForAccount)=>{
  const label=conditionLabelForAccount?.(account,id)??REPORT_LABELS.conditions[id]??platformTemplates.condition_labels[id];
  if(!label)throw Object.assign(new Error(`UNRESOLVED_CONDITION_ID:${id}`),{code:'UNRESOLVED_CONDITION_ID',condition_id:id,account_id:account?.account_id});
  return label;
};
const isModuleSummary=file=>file.field_or_condition_id==='module-summary';
const PREFLIGHT_MODULES=Object.freeze({'assets-accounts':'accounts','recovery-conditions':'conditions','locations-finding':'locations','recovery-order-exceptions':'instructions','contacts-assistance':'assistants','evidence-messages':'message'});
const publicPreflightIssue=item=>{const moduleId=PREFLIGHT_MODULES[item.module_id]??'accounts',code=item.issue_id??item.id??item.code??'GENERATION_PREFLIGHT_FAILED';return{issue_id:`GENERATION:${code}`,issue_code:code,module_id:moduleId,account_id:item.entity_id??null,field_id:item.field_id??null,business_message:'此模块尚未通过创建前检查。',why_required:'当前资料结构还不能稳定生成安全恢复版本。',completion_method:'请返回对应模块检查必要内容后再次进入 Review。',missing_parts:[],navigation_anchor:`${moduleId}:map:generation`,blocking:true};};
const publicAttachment=(file,store,platformTemplates,conditionLabelForAccount)=>({attachment_id:file.attachment_id,file_name:file.file_name,mime_type:file.mime_type,byte_length:file.byte_length,account_id:isModuleSummary(file)?null:file.account_id,account_label:isModuleSummary(file)?'本模块汇总信息':accountLabel(store.accounts[file.account_id],platformTemplates),attachment_scope:isModuleSummary(file)?'MODULE_SUMMARY':'ACCOUNT',module_id:file.module_id,module_label:REPORT_LABELS.modules[file.module_id]??'相关资料',purpose:file.purpose,covered_condition_ids:file.covered_condition_ids,covered_labels:file.covered_condition_ids.map(id=>conditionName(id,platformTemplates,store.accounts[file.account_id],conditionLabelForAccount))});

export function projectDashboard(store,receipt,{platformTemplates}={}){assertReceiptMatches(store,receipt);return{draft_id:store.draft_id,draft_revision:store.draft_revision,title:store.title,version:store.version,module_cards:MODULE_IDS.map(id=>({...receipt.module_statuses[id],module_id:id,issues:receipt.validation_issues.filter(item=>item.module_id===id).slice(0,2)})),uncompleted_count:receipt.validation_issues.filter(item=>item.blocking).length,suggestion_count:0,attachment_count:Object.keys(store.attachments).length,knowledge_notices:receipt.knowledge_notices};}
export function projectReview(store,receipt,preflight=generationPreflightFor(receipt)){assertReceiptMatches(store,receipt);assertGenerationPreflightMatches(store,preflight);const groups={},known=new Set(receipt.validation_issues.map(item=>item.issue_id)),issues=[...receipt.validation_issues,...preflight.issues.filter(item=>item.blocking&&!known.has(item.issue_id)).map(publicPreflightIssue)];for(const item of issues){const key=`${item.module_id}:${item.account_id??'map'}`;(groups[key]??={module_id:item.module_id,account_id:item.account_id,issues:[]}).issues.push(item);}return{draft_revision:store.draft_revision,groups:Object.values(groups),generation_allowed:preflight.publishable};}
export function projectReport(store,receipt,{platformTemplates,mode='PREVIEW_EDITABLE',conditionLabelForAccount}={}){assertReceiptMatches(store,receipt);const directory=Object.values(store.attachments).map(file=>publicAttachment(file,store,platformTemplates,conditionLabelForAccount)),moduleAttachments=directory.filter(file=>file.attachment_scope==='MODULE_SUMMARY'),assistants=store.assistant_decision==='NEED'?Object.values(store.assistants):[];const accounts=Object.values(store.accounts).map(account=>{const files=directory.filter(file=>file.attachment_scope==='ACCOUNT'&&file.account_id===account.account_id);return{account_id:account.account_id,label:accountLabel(account,platformTemplates),platform:account.platform_name||platformTemplates.platforms.find(item=>item.id===account.platform_id)?.name,region:account.region.value||'',account_type:REPORT_LABELS.account_types[account.account_type.value]??'未确认',conditions:selectedConditions(store,account.account_id).map(condition_id=>({condition_id,label:conditionName(condition_id,platformTemplates,account,conditionLabelForAccount),coverage:Object.values(store.location_coverages).filter(item=>item.account_id===account.account_id&&item.covered_condition_ids.includes(condition_id)).map(item=>({coverage_id:item.coverage_id,mode:REPORT_LABELS.coverage_modes[item.mode]??'位置说明',location_type:item.location_type,location_name:item.location_name,description:item.description,attachment_ids:item.attachment_ids}))})),instruction:store.recovery_instructions[account.account_id],risk_notes:store.recovery_instructions[account.account_id]?.optional_risk_notes??'',assistants,personal_message:store.personal_message,attachment_sections:Object.values(REPORT_LABELS.modules).map(label=>({label,attachments:files.filter(file=>file.module_label===label)})).filter(section=>section.attachments.length),attachments:files,edit_anchor:mode==='PREVIEW_EDITABLE'?`accounts:${account.account_id}:platform_id`:undefined};});return{report_version:2,mode,draft_id:store.draft_id,draft_revision:store.draft_revision,title:store.title,version_number:store.version.version_number,created_at:store.created_at,updated_at:store.updated_at,completion_status:receipt.generation_allowed?'已完成':'尚未完成',verification_status:Object.values(receipt.account_statuses).every(item=>item.state==='VERIFIED')?'已验证':'未验证',account_count:accounts.length,platform_count:new Set(accounts.map(item=>item.platform)).size,condition_count:accounts.reduce((sum,item)=>sum+item.conditions.length,0),attachment_count:directory.length,module_attachments:moduleAttachments,accounts,assistance:{decision:REPORT_LABELS.assistance[store.assistant_decision],assistants},personal_message:store.personal_message,attachment_directory:directory,issues:receipt.validation_issues};}
export function generationGate(store,receipt,report,preflight=generationPreflightFor(receipt)){assertReceiptMatches(store,receipt);assertGenerationPreflightMatches(store,preflight);const reportMatches=report?.draft_id===store.draft_id&&report?.draft_revision===store.draft_revision,issueIds=[...new Set([...receipt.validation_issues.filter(item=>item.blocking).map(item=>item.issue_id),...preflight.issues.filter(item=>item.blocking).map(item=>item.issue_id??item.id??item.code)].filter(Boolean))];return{allowed:Boolean(receipt.generation_allowed&&receipt.report_ready&&preflight.publishable&&reportMatches),draft_revision:store.draft_revision,issue_ids:issueIds,report_matches:reportMatches,preflight_publishable:preflight.publishable};}
