import { REPORT_LABELS } from './projections.js';

const moduleIds={'assets-accounts':'accounts','recovery-conditions':'conditions','locations-finding':'locations','recovery-order-exceptions':'instructions','contacts-assistance':'assistants','evidence-messages':'message'};
const conditionName=id=>REPORT_LABELS.conditions[id]??id;
const metadataValue=(map,id)=>(map.custom_fields??[]).find(item=>item.id===id)?.value;
const scopeFor=(map,file)=>{const marker=(file.owner_entity_refs??[]).map(id=>metadataValue(map,id)).find(value=>value==='MODULE_SUMMARY'||value==='SYSTEM_GENERATED'||String(value).startsWith('ACCOUNT:'));if(marker)return marker;const owners=(map.assets??[]).filter(asset=>(asset.attachment_refs??[]).includes(file.id));return owners.length===1?`ACCOUNT:${owners[0].id}`:'MODULE_SUMMARY';};
const publicFile=(file,map)=>{const scope=scopeFor(map,file),accountId=scope.startsWith('ACCOUNT:')?scope.slice(8):null,asset=(map.assets??[]).find(item=>item.id===accountId),relatedAccountIds=(map.assets??[]).filter(item=>(file.owner_entity_refs??[]).includes(item.id)).map(item=>item.id),locationRefs=(map.locations??[]).filter(item=>(item.attachment_refs??[]).includes(file.id)).map(item=>item.id),covered=(map.recovery_conditions??[]).filter(item=>(!accountId||(item.asset_refs??[]).includes(accountId))&&(item.location_refs??[]).some(id=>locationRefs.includes(id)));return{attachment_id:file.id,file_name:file.display_name,mime_type:file.media_type,byte_length:file.byte_length,account_id:accountId,account_label:asset?.label??null,related_account_ids:relatedAccountIds,attachment_scope:scope,module_id:moduleIds[file.module_refs?.[0]]??'accounts',module_label:REPORT_LABELS.modules[moduleIds[file.module_refs?.[0]]]??'相关资料',purpose:file.purpose,covered_labels:covered.map(item=>conditionName(item.type))};};

export function projectRecoveredReport(snapshot){const map=snapshot.knowledge_graph;if(map.schema_version!==2)return null;const files=(map.attachments??[]).map(file=>publicFile(file,map)),metadata=(asset,suffix)=>metadataValue(map,`metadata-${asset.id}-${suffix}`),contacts=map.contacts??[];const accounts=(map.assets??[]).map(asset=>{const conditions=(asset.condition_refs??[]).map(ref=>{const item=(map.recovery_conditions??[]).find(value=>value.id===ref),type=item?.type??'other',label=(item?.custom_field_refs??[]).map(id=>metadataValue(map,id)).find(Boolean)??conditionName(type),coverages=(item?.location_refs??[]).map(locationRef=>{const location=(map.locations??[]).find(value=>value.id===locationRef);return{location_id:locationRef,label:location?.label??'位置说明',description:location?.finding_instructions??'',mode:(location?.label??'').includes('SUMMARY')?'汇总位置':'位置说明'};});return{condition_id:type,label,coverage:coverages};});const step=(map.recovery_steps??[]).find(item=>(item.asset_refs??[]).includes(asset.id)),accountFiles=files.filter(file=>file.attachment_scope.startsWith('ACCOUNT:')&&file.account_id===asset.id);return{account_id:asset.id,label:asset.label,platform:asset.label,region:metadata(asset,'region')||'未记录',account_type:REPORT_LABELS.account_types[metadata(asset,'account-type')]??metadata(asset,'account-type')??'未记录',conditions,instruction:{instruction_text:step?.action??''},risk_notes:step?.stop_condition??'',assistants:contacts.filter(item=>(asset.contact_refs??[]).includes(item.id)),personal_message:map.personal_message,attachment_sections:Object.values(REPORT_LABELS.modules).map(label=>({label,attachments:accountFiles.filter(file=>file.module_label===label)})).filter(section=>section.attachments.length),attachments:accountFiles};});return{title:map.vault_title,version_number:snapshot.version??snapshot.snapshot_version??1,updated_at:map.reviewed_at,account_count:accounts.length,platform_count:new Set(accounts.map(item=>item.platform)).size,condition_count:accounts.reduce((sum,item)=>sum+item.conditions.length,0),attachment_count:files.length,assistant_count:contacts.length,accounts,assistance:{needed:map.assistance?.needed,assistants:contacts},personal_message:map.personal_message,module_attachments:files.filter(file=>file.attachment_scope==='MODULE_SUMMARY'),system_files:files.filter(file=>file.attachment_scope==='SYSTEM_GENERATED'),attachment_directory:files};}
