import { MODULE_IDS,accountLabel,selectedConditions } from './model.js';

const MODULE_STATE={NOT_STARTED:'NOT_STARTED',IN_PROGRESS:'IN_PROGRESS',SUGGESTED:'SUGGESTED',COMPLETE:'COMPLETE',VERIFIED:'VERIFIED'};
const validField=value=>value?.state==='VALID'&&String(value.value??'').trim();
const temporary=value=>['UNKNOWN','LATER'].includes(value?.state);
const target=(moduleId,accountId,fieldId,conditionId=null)=>({module_id:moduleId,account_id:accountId,condition_id:conditionId,field_id:fieldId,navigation_anchor:[moduleId,accountId??'map',conditionId??fieldId].join(':')});
const make=(code,{module_id,account=null,condition_id=null,field_id,message,why,method,missing_parts=[],severity='BLOCKING'})=>({issue_id:[code,account?.account_id??'map',condition_id??field_id].join(':'),issue_code:code,severity,module_id,account_id:account?.account_id??null,condition_id,field_id,business_message:message,why_required:why,completion_method:method,missing_parts,navigation_anchor:target(module_id,account?.account_id??null,field_id,condition_id).navigation_anchor,blocking:severity!=='WARNING'});
const validAttachment=file=>file?.technical_status==='VALID'&&Number.isSafeInteger(file.byte_length)&&file.byte_length>0&&/^[a-f0-9]{64}$/.test(file.sha256??'')&&Boolean(file.mime_type&&file.account_id&&file.module_id&&file.field_or_condition_id&&file.purpose);
const moduleSummarySupports=(store,moduleId)=>Object.values(store.attachments).some(file=>validAttachment(file)&&file.module_id===moduleId&&file.field_or_condition_id==='module-summary');
const fileSupports=(store,ids,{accountId,moduleId,conditionId=null})=>ids.some(id=>{const file=store.attachments[id];return validAttachment(file)&&file.account_id===accountId&&file.module_id===moduleId&&(!conditionId||file.covered_condition_ids.includes(conditionId)||file.field_or_condition_id===conditionId);});
const moduleHasAttachment=(store,moduleId)=>Object.values(store.attachments).some(file=>validAttachment(file)&&file.module_id===moduleId);

export function validateProductStore(store,{platformTemplates,rules,verifiedAccountIds=[]}={}){const issues=[],notices=[],accounts=Object.values(store.accounts),duplicatePlatforms=new Set(accounts.filter((item,index)=>accounts.some((other,i)=>i!==index&&other.platform_id===item.platform_id)).map(item=>item.platform_id));
  if(!accounts.length)issues.push(make('ACCOUNT_REQUIRED',{module_id:'accounts',field_id:'accounts',message:'尚未添加需要恢复的账户。',why:'Recovery Map必须至少包含一个账户。',method:'添加一个账户。'}));
  for(const account of accounts){const template=platformTemplates.platforms.find(item=>item.id===account.platform_id),label=accountLabel(account,platformTemplates);if(!template)issues.push(make('PLATFORM_REQUIRED',{module_id:'accounts',account,field_id:'platform_id',message:`${label}尚未选择有效平台。`,why:'平台决定账户模板和恢复条件。',method:'选择Binance、OKX、Coinbase或其他/自定义。'}));if(template?.requires_region&&!validField(account.region))issues.push(make(temporary(account.region)?'ACCOUNT_REGION_TEMPORARY':'ACCOUNT_REGION_REQUIRED',{module_id:'accounts',account,field_id:'region',message:`${label}的所属地区尚未完成。`,why:'托管平台的地区决定适用账户范围。',method:'选择有效地区，不要保留UNKNOWN或LATER。'}));if(template?.requires_account_type&&!validField(account.account_type))issues.push(make(temporary(account.account_type)?'ACCOUNT_TYPE_TEMPORARY':'ACCOUNT_TYPE_REQUIRED',{module_id:'accounts',account,field_id:'account_type',message:`${label}的账户类型尚未完成。`,why:'账户类型用于区分个人与机构恢复资料。',method:'选择个人账户或机构账户。'}));if(validField(account.account_type)&&!['Personal','Institutional'].includes(account.account_type.value))issues.push(make('ACCOUNT_TYPE_UNSUPPORTED',{module_id:'accounts',account,field_id:'account_type',message:`${label}的账户类型无法识别。`,why:'账户必须使用当前支持的个人或机构类型。',method:'选择个人账户或机构账户。'}));if(duplicatePlatforms.has(account.platform_id)&&!account.display_label.trim())issues.push(make('ACCOUNT_LABEL_REQUIRED',{module_id:'accounts',account,field_id:'display_label',message:`${label}与同平台其他账户无法区分。`,why:'条件、位置、步骤和附件必须绑定到唯一账户。',method:'填写唯一备注名称。'}));
    const selected=selectedConditions(store,account.account_id);if(!selected.length)issues.push(make('CONDITION_SELECTION_REQUIRED',{module_id:'conditions',account,field_id:'selected_condition_ids',message:`${label}尚未选择恢复条件。`,why:'恢复人必须知道恢复该账户需要哪些条件。',method:'至少选择一项实际适用条件。'}));
    const missing=[];if(!moduleSummarySupports(store,'locations'))for(const conditionId of selected){const coverage=Object.values(store.location_coverages).filter(item=>item.account_id===account.account_id&&item.covered_condition_ids.includes(conditionId)),complete=coverage.filter(item=>Boolean(item.description.trim()||item.location_name.trim()||fileSupports(store,item.attachment_ids,{accountId:account.account_id,moduleId:'locations',conditionId})));if(complete.length!==1)missing.push({condition_id:conditionId,reason:complete.length?'DUPLICATE':'MISSING'});}if(missing.length)issues.push({...make('LOCATION_COVERAGE_REQUIRED',{module_id:'locations',account,condition_id:missing[0].condition_id,field_id:'coverage',message:`${label}仍有${missing.length}项恢复条件未形成唯一有效位置覆盖。`,why:'每个已选择条件必须通过位置文字或明确关联的附件完成覆盖，且不能存在冲突覆盖。',method:'逐项填写位置，或用汇总文字/附件覆盖；移除重复覆盖。',missing_parts:missing.map(item=>`${item.condition_id}:${item.reason}`)}),missing_condition_ids:missing.map(item=>item.condition_id)});
    const instruction=store.recovery_instructions[account.account_id],hasStep=moduleSummarySupports(store,'instructions')||(instruction&&(instruction.instruction_text.trim()||fileSupports(store,instruction.instruction_attachment_ids,{accountId:account.account_id,moduleId:'instructions'})));if(!hasStep)issues.push(make('INSTRUCTION_REQUIRED',{module_id:'instructions',account,field_id:'instruction',message:`${label}缺少恢复与转移步骤。`,why:'恢复人需要明确可执行的操作顺序。',method:'填写步骤文字或添加归属正确的步骤附件。'}));if(hasStep&&!moduleSummarySupports(store,'instructions')&&!instruction.saved_at)issues.push(make('INSTRUCTION_UNSAVED',{module_id:'instructions',account,field_id:'saved_at',message:`${label}的恢复步骤有未保存修改。`,why:'页面底部的统一保存会确认当前步骤内容。',method:'点击保存并继续，或保存并返回Review。'}));
  }
  if(store.assistant_decision==='NEED'){const assistants=Object.values(store.assistants),hasAttachment=moduleHasAttachment(store,'assistants');if(!assistants.length&&!hasAttachment)issues.push(make('ASSISTANT_REQUIRED',{module_id:'assistants',field_id:'assistants',message:'已选择需要协助，但尚未填写协助人或上传协助说明附件。',why:'恢复人需要知道联系谁及权限边界。',method:'填写完整协助人信息，或上传能够完整承担本模块记录的有效附件。'}));for(const assistant of assistants){const missing=['role','contact_timing','allowed_help','permission_boundary'].filter(key=>!assistant[key]?.trim());if(missing.length&&!hasAttachment)issues.push(make('ASSISTANT_DETAILS_REQUIRED',{module_id:'assistants',field_id:missing[0],message:'协助人信息尚不完整。',why:'已创建的结构化协助人必须具备完整基本字段。',method:'补充角色、联系时机、可协助事项和权限边界，或上传能够完整承担本模块记录的有效附件。',missing_parts:missing}));}}
  for(const file of Object.values(store.attachments))if(!validAttachment(file)||!store.accounts[file.account_id]||file.platform_id!==store.accounts[file.account_id]?.platform_id||file.covered_condition_ids.some(id=>!selectedConditions(store,file.account_id).includes(id)))issues.push(make('ATTACHMENT_INVALID',{module_id:file.module_id||'message',account:store.accounts[file.account_id]??null,field_id:'attachment',message:'附件技术信息或归属无效。',why:'恢复材料必须完整并准确属于具体账户和用途。',method:'删除后从正确账户字段重新添加，或修正归属。',severity:'DATA_ERROR'}));
  const unique=[...new Map(issues.map(item=>[item.issue_id,item])).values()],module_statuses={},account_statuses={};for(const moduleId of MODULE_IDS){const moduleIssues=unique.filter(item=>item.module_id===moduleId),hasContent=moduleId==='accounts'?accounts.length>0:moduleId==='conditions'?accounts.some(a=>selectedConditions(store,a.account_id).length):moduleId==='locations'?Object.keys(store.location_coverages).length>0||moduleSummarySupports(store,'locations'):moduleId==='instructions'?Object.values(store.recovery_instructions).some(item=>item.instruction_text||item.instruction_attachment_ids.length)||moduleSummarySupports(store,'instructions'):moduleId==='assistants'?store.assistant_decision!=='NOT_SET':Boolean(store.personal_message?.text||store.personal_message?.attachment_ids?.length);module_statuses[moduleId]={state:!hasContent?'NOT_STARTED':moduleIssues.length?'IN_PROGRESS':verifiedAccountIds.length&&['accounts','conditions','locations','instructions'].includes(moduleId)?'VERIFIED':'COMPLETE',issue_ids:moduleIssues.map(item=>item.issue_id),incomplete_count:moduleIssues.length,suggestion_count:0};}
  for(const account of accounts){const own=unique.filter(item=>item.account_id===account.account_id);account_statuses[account.account_id]={state:own.length?'IN_PROGRESS':verifiedAccountIds.includes(account.account_id)?'VERIFIED':'COMPLETE',issue_ids:own.map(item=>item.issue_id)};}
  const blocking=unique.filter(item=>item.blocking),result={draft_id:store.draft_id,draft_revision:store.draft_revision,rulebook_version:store.rulebook_version,account_statuses,module_statuses,validation_issues:unique,knowledge_notices:notices,generation_allowed:blocking.length===0,report_ready:blocking.length===0,validated_at:new Date().toISOString()};return Object.freeze(result);
}

export function assertReceiptMatches(store,receipt){if(!receipt||receipt.draft_id!==store.draft_id||receipt.draft_revision!==store.draft_revision||receipt.rulebook_version!==store.rulebook_version)throw new Error('STALE_VALIDATION_RECEIPT');return true;}
