import {cryptoEngine} from '../../src/crypto/crypto-engine.js';
import {createVaultArtifacts} from '../../src/ui/vault-pipeline.js';
import {STANDARD_MODULE_IDS} from '../../src/knowledge/schema-v2.js';

const safeId=(prefix,value,index)=>`${prefix}-${index}-${String(value).normalize('NFKD').replace(/[^A-Za-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)||'custom'}`;

export async function createCryptoProductArtifacts({assets,attachments,password,createdAt=new Date().toISOString(),idFactory=()=>crypto.randomUUID()}){
  if(!assets.length)throw new Error('至少需要一项加密资产。');
  const prepared=[];for(let index=0;index<attachments.length;index++){const item=attachments[index],sha256=await cryptoEngine.hashHex(item.bytes),id=`attachment-${String(index+1).padStart(4,'0')}-${sha256.slice(0,16)}`;prepared.push({...item,id,sha256});}
  const assetRows=assets.map((asset,index)=>{const id=safeId('crypto-asset',asset.name,index+1),condition=`condition-${index+1}`,location=`location-${index+1}`,step=`step-${index+1}`,attachmentRefs=prepared.filter(item=>item.assetId===asset.id).map(item=>item.id);return{id,condition,location,step,attachmentRefs,asset,index};});
  const customFields=[];for(const row of assetRows){customFields.push({id:`field-category-${row.index+1}`,module_ref:'assets-accounts',label:'Crypto Category',field_type:'text',value:row.asset.category},{id:`field-note-${row.index+1}`,module_ref:'evidence-messages',label:'Recovery Note',field_type:'text',value:row.asset.note||''});}
  const graph={schema_version:2,vault_title:'CJAS Crypto Recovery Map',plan_type:'crypto-product-v1',reviewed_at:createdAt,standard_modules:STANDARD_MODULE_IDS.map((id,index)=>({id,order:(index+1)*10})),custom_modules:[],assets:assetRows.map(row=>({id:row.id,type:'crypto',label:row.asset.name,exists:true,platform_hint:row.asset.category,condition_refs:[row.condition],location_refs:[row.location],contact_refs:[],step_refs:[row.step],attachment_refs:row.attachmentRefs,custom_field_refs:[`field-category-${row.index+1}`,`field-note-${row.index+1}`]})),recovery_conditions:assetRows.map(row=>({id:row.condition,type:'recovery-materials',exists:true,asset_refs:[row.id],location_refs:[row.location],fallback_path_refs:[],notes:row.asset.note||'待持有人补充恢复说明',custom_field_refs:[]})),fallback_paths:[],locations:assetRows.map(row=>({id:row.location,label:`${row.asset.name} 恢复资料位置`,type:'digital',finding_instructions:row.asset.note||'查看本资产关联的恢复说明和附件',access_prerequisites:[],attachment_refs:row.attachmentRefs,custom_field_refs:[]})),assistance:{needed:false},contacts:[],recovery_steps:assetRows.map(row=>({id:row.step,sequence:row.index+1,risk_level:'medium',action:`按持有人说明恢复 ${row.asset.name}`,completion_check:'核对公开资产信息并确认控制权',failure_action:'停止操作并联系官方或可信专业人士',stop_condition:'身份、地址、网络或授权范围不一致',asset_refs:[row.id],condition_refs:[row.condition],location_refs:[row.location],contact_refs:[],warning_refs:['warning-secrets'],attachment_refs:row.attachmentRefs})),warnings:[{id:'warning-secrets',risk_level:'high',instruction:'不得在Recovery Map中保存私钥、助记词、完整密码、OTP或验证码。',applies_to_refs:assetRows.map(row=>row.id)}],attachments:prepared.map(item=>{const row=assetRows.find(value=>value.asset.id===item.assetId);return{id:item.id,display_name:item.name,media_type:item.mimeType,byte_length:item.bytes.length,sha256:item.sha256,module_refs:['evidence-messages'],owner_entity_refs:[row.id],purpose:'Crypto Recovery Map辅助材料',sensitive_acknowledged:true};}),personal_message:null,custom_fields:customFields};
  const snapshotId=`crypto-v1-${idFactory()}`,vaultId=`crypto-product-${idFactory()}`,attachmentPayloads=Object.fromEntries(prepared.map(item=>[item.id,item.bytes])),artifacts=await createVaultArtifacts({knowledgeGraph:graph,attachmentPayloads,password,wizardConfigVersion:3,vaultId,snapshotId,createdAt});
  return{...artifacts,snapshotId,vaultId,fileCount:prepared.length,totalOriginalBytes:prepared.reduce((sum,item)=>sum+item.bytes.length,0)};
}
