import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {MAINNET_STAGES,ENCRYPTED_CHECKPOINT_SCHEMA_VERSION,createOperation,transitionOperation,createEncryptedOperationRecord,unlockEncryptedOperationRecord,validateResumableOperationRecord,sanitizeCompletedOperationRecord} from '../../src/ui/mainnet-stability.js';
import {RESUME_CHECKPOINT_CRYPTO} from '../../src/ui/resume-checkpoint-crypto.js';

const password='CorrectHorse9!Battery',hash='a'.repeat(64),txid='T'.repeat(43);
function input({state=MAINNET_STAGES.LOCAL_ARTIFACTS_READY,signedTransaction=null}={}){const operation=createOperation({draftId:'draft-sensitive',versionId:'version-1',snapshotId:'snapshot-1',archiveSha256:hash,operationId:'operation-1'});if(state!==MAINNET_STAGES.LOCAL_ARTIFACTS_READY)for(const next of ['CHECKPOINT_DURABLE','WALLET_DETECTED','WALLET_CONNECTED','QUOTE_READY','FEE_CONFIRMED','SIGNING','SIGNED_CHECKPOINTED','UPLOADING','TX_ACCEPTED','EVIDENCE_READY','VERIFYING','COMPLETE']){transitionOperation(operation,MAINNET_STAGES[next],next==='TX_ACCEPTED'?{transaction_id:txid}:{});if(next===state)break;}return{operation,store:{draft_id:'draft-sensitive',draft_revision:7,rulebook_version:'rules',version:{version_id:'version-1',version_number:1,status:'REVIEW_READY',draft_revision:7},accounts:{secret:{label:'private account'}},condition_selections:{},location_coverages:{},recovery_instructions:{},assistants:{},attachments:{secret:{filename:'secret.txt',bytes:new Uint8Array([80,76,65,73,78,84,69,88,84])}}},receipt:{draft_id:'draft-sensitive',draft_revision:7,generation_allowed:true,report_ready:true},artifacts:{snapshot:{snapshot_id:'snapshot-1',secret:'plaintext snapshot',attachments:[{filename:'secret.txt',byte_length:9}]},archiveBytes:new Uint8Array([1,2,3,4]),kitBytes:new Uint8Array([5,6,7]),archiveName:'archive.cjasvault',ciphertextSha256:hash},evidence:state===MAINNET_STAGES.COMPLETE?{status:'READY_FOR_INDEPENDENT_RECOVERY',txid,archive_sha256:hash,archive_size:4,background_verification:'PASS'}:{status:'LOCAL_ENCRYPTION_PASS'},signedTransaction};}

test('post-password checkpoint persists one authenticated ciphertext and no plaintext product structures',async()=>{const record=await createEncryptedOperationRecord({...input(),password});assert.equal(record.checkpoint_schema,ENCRYPTED_CHECKPOINT_SCHEMA_VERSION);assert.equal(record.checkpoint_crypto.format,'SKREK_ENCRYPTED_RESUME_V1');assert.equal(record.checkpoint_crypto.kdf.domain,RESUME_CHECKPOINT_CRYPTO.domain);assert.ok(record.encrypted_payload instanceof Uint8Array);for(const key of ['store','receipt','artifacts','signed_transaction'])assert.equal(key in record,false);const serialized=JSON.stringify(record);for(const marker of ['private account','secret.txt','plaintext snapshot','PLAINTEXT'])assert.equal(serialized.includes(marker),false);assert.equal(validateResumableOperationRecord(record),record);});

test('correct password restores minimum state without restoring full Draft or Snapshot',async()=>{const record=await createEncryptedOperationRecord({...input(),password}),restored=await unlockEncryptedOperationRecord(record,password);assert.deepEqual(restored.artifacts.archiveBytes,new Uint8Array([1,2,3,4]));assert.deepEqual(restored.artifacts.kitBytes,new Uint8Array([5,6,7]));assert.equal(restored.artifacts.snapshot.snapshot_id,'snapshot-1');assert.equal(restored.artifacts.snapshot.secret,undefined);assert.deepEqual(restored.store.accounts,{});assert.equal(restored.store.version.version_id,'version-1');});

test('wrong password and tampering fail closed without mutating checkpoint',async()=>{const record=await createEncryptedOperationRecord({...input(),password}),before=structuredClone(record);await assert.rejects(()=>unlockEncryptedOperationRecord(record,'WrongPassword9!'),error=>error.code==='RESUME_CHECKPOINT_UNLOCK_FAILED');assert.deepEqual(record,before);const tampered=structuredClone(record);tampered.encrypted_payload[0]^=1;await assert.rejects(()=>unlockEncryptedOperationRecord(tampered,password),error=>error.code==='RESUME_CHECKPOINT_UNLOCK_FAILED');assert.deepEqual(record,before);});

test('signed transaction has exact reversible checkpoint representation',async()=>{const signed={id:txid,owner:'owner',reward:'123',tags:[{name:'Content-Type',value:'application/octet-stream'}],data_root:'root',signature:'signature'},record=await createEncryptedOperationRecord({...input({state:MAINNET_STAGES.UPLOADING,signedTransaction:signed}),password}),restored=await unlockEncryptedOperationRecord(record,password);assert.deepEqual(restored.signed_transaction,signed);assert.equal(restored.signed_transaction.id,txid);});

test('legacy plaintext incomplete records are rejected and stable complete records sanitize',async()=>{const unfinished=input(),legacy={schema_version:2,operation_id:unfinished.operation.operation_id,operation:unfinished.operation,store:unfinished.store,receipt:unfinished.receipt,artifacts:unfinished.artifacts,evidence:unfinished.evidence,signed_transaction:null};await assert.rejects(()=>unlockEncryptedOperationRecord(legacy,password),error=>error.code==='LEGACY_PLAINTEXT_CHECKPOINT_REJECTED');const complete=input({state:MAINNET_STAGES.COMPLETE,signedTransaction:{id:txid}}),legacyComplete={schema_version:2,operation_id:complete.operation.operation_id,operation:complete.operation,store:complete.store,receipt:complete.receipt,artifacts:complete.artifacts,evidence:complete.evidence,signed_transaction:complete.signedTransaction},sanitized=sanitizeCompletedOperationRecord(legacyComplete);assert.equal(sanitized.retention.state,'COMPLETED_SANITIZED');assert.equal(sanitized.encrypted_payload,null);assert.equal(sanitized.store,null);});

test('stable complete encrypted record removes payload and crypto parameters',async()=>{const record=await createEncryptedOperationRecord({...input({state:MAINNET_STAGES.COMPLETE,signedTransaction:{id:txid}}),password}),sanitized=sanitizeCompletedOperationRecord(record);assert.equal(sanitized.retention.state,'COMPLETED_SANITIZED');assert.equal(sanitized.encrypted_payload,null);assert.equal(sanitized.checkpoint_crypto,null);assert.equal(sanitized.operation.transaction_id,txid);assert.equal(sanitized.evidence.txid,txid);});

test('50 MiB-class encrypted archive remains a single ciphertext checkpoint payload',async()=>{const large=input(),size=50*1024*1024;large.artifacts.archiveBytes=new Uint8Array(size);large.artifacts.archiveBytes[0]=17;large.artifacts.archiveBytes[size-1]=29;const started=performance.now(),record=await createEncryptedOperationRecord({...large,password}),elapsed=performance.now()-started;assert.ok(record.encrypted_payload.byteLength>size);assert.ok(record.encrypted_payload.byteLength<size+1024*1024);assert.equal('artifacts' in record,false);const restored=await unlockEncryptedOperationRecord(record,password);assert.equal(restored.artifacts.archiveBytes.byteLength,size);assert.equal(restored.artifacts.archiveBytes[0],17);assert.equal(restored.artifacts.archiveBytes[size-1],29);assert.ok(elapsed<15000);});

test('no-copy source gate rejects persistent plaintext fields or password/key storage',async()=>{const stability=await readFile(new URL('../../src/ui/mainnet-stability.js',import.meta.url),'utf8'),cryptoSource=await readFile(new URL('../../src/ui/resume-checkpoint-crypto.js',import.meta.url),'utf8'),app=await readFile(new URL('../../web/v2/v2-app.js',import.meta.url),'utf8');assert.match(stability,/encrypted_payload/);assert.match(stability,/plaintext_fields/);assert.doesNotMatch(`${stability}\n${cryptoSource}`,/localStorage[^;]*(password|derivedKey|resumeKey)|sessionStorage[^;]*(password|derivedKey|resumeKey)/i);assert.doesNotMatch(app,/bindRecoveryMetadata\(\{\s*(password|resumeCheckpointPassword)/i);});
