import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createRecoveryMapDraft } from '../../src/product-v2/model.js';
import { MemoryProductStore } from '../../src/product-v2/store.js';
import { ProductActions } from '../../src/product-v2/actions.js';
import { addAttachment,removeAttachment,replaceAttachment,attachmentCapacity } from '../../src/product-v2/attachment-manager.js';
import { validateProductStore } from '../../src/product-v2/validator.js';
import { projectDashboard,projectReview,projectReport,generationGate } from '../../src/product-v2/projections.js';
import { markReviewReady,markGenerated,createDraftFromVersion } from '../../src/product-v2/version-machine.js';
import { mapProductToKnowledgeV2,attachmentPayloads } from '../../src/product-v2/snapshot-mapper.js';
import {runGenerationPreflight,bindGenerationPreflight} from '../../src/product-v2/generation-preflight.js';
import { importLegacyDraft } from '../../src/product-v2/legacy-importer.js';
import { createVaultArtifacts,recoverVaultArtifacts } from '../../src/ui/vault-pipeline.js';
import { commitPendingAccount } from '../../src/product-v2/account-form.js';
import { projectRecoveredReport } from '../../src/product-v2/recovered-report.js';
import { recoverAttachmentForDownload } from '../../src/recovery/attachment-recovery.js';
import { createApplicationState,enterApplicationView,beginAttachmentView,leaveAttachmentView,nextProductView } from '../../src/product-v2/application-state.js';

const root=new URL('../../',import.meta.url),json=async path=>JSON.parse(await readFile(new URL(path,root),'utf8')),templates=await json('config/recovery-map/v2/platform-templates-v2.json'),rules=await json('config/recovery-map/v2/living-rules-v2.json'),clock=()=> '2026-08-04T00:00:00.000Z';
const addAccount=(store,id,platform,nickname='')=>ProductActions.addAccount(store,{account_id:id,platform_id:platform,platform_name:templates.platforms.find(item=>item.id===platform).name,region:'Australia',account_type:'Personal',display_label:nickname},{expected_revision:store.draft_revision,clock});
const select=(store,id,ids)=>ProductActions.setConditionSelection(store,id,{selected_condition_ids:ids},{expected_revision:store.draft_revision,clock});
const item=(store,accountId,conditionId)=>ProductActions.upsertCoverage(store,{coverage_id:`coverage-${accountId}-${conditionId}`,account_id:accountId,mode:'ITEMIZED',covered_condition_ids:[conditionId],location_type:'设备或资料',location_name:`${conditionId}位置`,description:'脱敏查找说明',attachment_ids:[]},{expected_revision:store.draft_revision,clock});
const instruction=(store,id,text='从官方入口恢复，核对账户与接收地址后安全转移。')=>{let next=ProductActions.updateInstruction(store,id,{instruction_text:text},{expected_revision:store.draft_revision,clock});return ProductActions.confirmInstructionSaved(next,id,{expected_revision:next.draft_revision,clock});};
const receipt=store=>{const result=validateProductStore(store,{platformTemplates:templates,rules});return bindGenerationPreflight(result,runGenerationPreflight(store,result,{platformTemplates:templates}));};
const bytes=new TextEncoder().encode('CJAS V2 attachment');
const attach=async(store,{id,accountId,moduleId='locations',field='summary',covers=[]})=>addAttachment(store,{attachment_id:id,file_name:`${id}.txt`,mime_type:'text/plain',byte_length:bytes.byteLength,bytes,module_id:moduleId,platform_id:store.accounts[accountId].platform_id,account_id:accountId,field_or_condition_id:field,purpose:'恢复说明',covered_condition_ids:covers},{rules,clock});

function story1(){let store=createRecoveryMapDraft({clock});store=addAccount(store,'binance-a','binance');const ids=['email','phone','password','authenticator'];store=select(store,'binance-a',ids);for(const id of ids)store=item(store,'binance-a',id);return instruction(store,'binance-a');}
async function story2(){let store=createRecoveryMapDraft({clock});store=addAccount(store,'okx-a','okx');const ids=['email','phone','password','authenticator'];store=select(store,'okx-a',ids);store=await attach(store,{id:'okx-summary',accountId:'okx-a',covers:ids});store=ProductActions.upsertCoverage(store,{coverage_id:'coverage-okx-summary',account_id:'okx-a',mode:'SUMMARY',covered_condition_ids:ids,description:'',attachment_ids:['okx-summary']},{expected_revision:store.draft_revision,clock});return instruction(store,'okx-a');}
function story3(){let store=createRecoveryMapDraft({clock});store=addAccount(store,'coinbase-a','coinbase');const ids=['email','phone','password','authenticator','passkey'];store=select(store,'coinbase-a',ids);store=ProductActions.upsertCoverage(store,{coverage_id:'coverage-coinbase-summary',account_id:'coinbase-a',mode:'SUMMARY',covered_condition_ids:ids.slice(0,3),description:'前三项材料位于同一脱敏保管位置',attachment_ids:[]},{expected_revision:store.draft_revision,clock});for(const id of ids.slice(3))store=item(store,'coinbase-a',id);return instruction(store,'coinbase-a');}
async function story4(){let store=createRecoveryMapDraft({clock});store=addAccount(store,'binance-a','binance','主账户');store=addAccount(store,'binance-b','binance','备用账户');for(const[id,condition]of[['binance-a','email'],['binance-b','authenticator']]){store=select(store,id,[condition]);store=await attach(store,{id:`file-${id}`,accountId:id,field:condition,covers:[condition]});store=ProductActions.upsertCoverage(store,{coverage_id:`coverage-${id}`,account_id:id,mode:'ITEMIZED',covered_condition_ids:[condition],location_type:'设备',location_name:`${id}位置`,description:'',attachment_ids:[`file-${id}`]},{expected_revision:store.draft_revision,clock});store=instruction(store,id,`${id}独立恢复步骤`);}return store;}

test('Golden Story 1: Binance four itemized locations',()=>{const store=story1(),result=receipt(store);assert.equal(result.generation_allowed,true);assert.equal(Object.values(store.location_coverages).length,4);});
test('Golden Story 2: OKX one summary attachment covers four conditions',async()=>{const store=await story2(),result=receipt(store);assert.equal(result.generation_allowed,true);assert.equal(Object.values(store.location_coverages)[0].mode,'SUMMARY');});
test('Golden Story 3: Coinbase mixed coverage is first-class',()=>{const store=story3();assert.equal(receipt(store).generation_allowed,true);assert.deepEqual(Object.values(store.location_coverages).map(item=>item.mode),['SUMMARY','ITEMIZED','ITEMIZED']);});
test('Golden Story 4: duplicate Binance accounts remain isolated',async()=>{const store=await story4();assert.equal(receipt(store).generation_allowed,true);for(const id of ['binance-a','binance-b'])assert.ok(Object.values(store.attachments).every(file=>file.account_id===id||file.account_id!==id));assert.notDeepEqual(store.condition_selections['binance-a'],store.condition_selections['binance-b']);});
test('Golden Story 5: one business gap produces one shared issue and exact target',()=>{let store=story1();delete store.location_coverages['coverage-binance-a-authenticator'];const validation=receipt(store),dashboard=projectDashboard(store,validation,{platformTemplates:templates}),review=projectReview(store,validation),report=projectReport(store,validation,{platformTemplates:templates}),gate=generationGate(store,validation,report),issues=validation.validation_issues.filter(item=>item.issue_code==='LOCATION_COVERAGE_REQUIRED');assert.equal(issues.length,1);assert.equal(dashboard.uncompleted_count,1);assert.equal(review.groups.flatMap(item=>item.issues).length,1);assert.deepEqual(gate.issue_ids,[issues[0].issue_id]);assert.equal(issues[0].navigation_anchor,'locations:binance-a:authenticator');});
test('Golden Story 6: add replace and delete synchronize capacity, validation and report',async()=>{let store=story1();store=await attach(store,{id:'guide',accountId:'binance-a',moduleId:'instructions',field:'instruction'});store=ProductActions.updateInstruction(store,'binance-a',{instruction_attachment_ids:['guide']},{expected_revision:store.draft_revision,clock});store=ProductActions.confirmInstructionSaved(store,'binance-a',{expected_revision:store.draft_revision,clock});const before=attachmentCapacity(store,rules);store=await replaceAttachment(store,'guide',{bytes:new TextEncoder().encode('replacement'),byte_length:11,file_name:'replacement.txt',mime_type:'text/plain'},{rules,clock});assert.equal(Object.keys(store.attachments).length,1);assert.notEqual(attachmentCapacity(store,rules).used_bytes,before.used_bytes);store=removeAttachment(store,'guide',{clock});const validation=receipt(store),report=projectReport(store,validation,{platformTemplates:templates});assert.equal(attachmentCapacity(store,rules).used_bytes,0);assert.equal(report.attachment_count,0);assert.equal(validation.generation_allowed,true);});
test('browser File replacement discards old bytes before validating the new file',async()=>{let store=story1();store=await attach(store,{id:'replace-file',accountId:'binance-a'});const replacementBytes=new TextEncoder().encode('new browser file bytes'),file={name:'new-file.txt',type:'text/plain',size:replacementBytes.byteLength,arrayBuffer:async()=>replacementBytes.buffer};store=await replaceAttachment(store,'replace-file',{file,file_name:file.name,mime_type:file.type,byte_length:file.size},{rules,clock});assert.equal(store.attachments['replace-file'].file_name,'new-file.txt');assert.deepEqual(store.attachments['replace-file'].bytes,replacementBytes);});
test('all four projections consume the same revision-bound Validation Receipt',()=>{const store=story1(),validation=receipt(store),dashboard=projectDashboard(store,validation,{platformTemplates:templates}),review=projectReview(store,validation),report=projectReport(store,validation,{platformTemplates:templates}),gate=generationGate(store,validation,report);assert.equal(dashboard.draft_revision,validation.draft_revision);assert.equal(review.draft_revision,validation.draft_revision);assert.equal(report.draft_revision,validation.draft_revision);assert.equal(gate.draft_revision,validation.draft_revision);});
test('generated Version is immutable and new edits require a derived Draft',()=>{let store=story1(),validation=receipt(store),ready=markReviewReady(store,validation,clock),generated=markGenerated(ready,validation,clock);assert.throws(()=>ProductActions.updateAccount(generated,'binance-a',{display_label:'changed'},{expected_revision:generated.draft_revision,clock}),/GENERATED_VERSION_IMMUTABLE/);const next=createDraftFromVersion(generated,{draftId:'draft-v2-next',clock});assert.equal(next.version.status,'DRAFT');assert.equal(next.version.version_number,2);assert.equal(next.source_version_id,generated.version.version_id);});
test('Snapshot Mapper passes frozen Schema v2 and completes Kit Archive recovery',async()=>{const store=await story2(),validation=receipt(store),knowledge=mapProductToKnowledgeV2(store,validation,{platformTemplates:templates,reviewedAt:clock()}),password='River-Lantern-27-Mango',artifacts=await createVaultArtifacts({knowledgeGraph:knowledge,attachmentPayloads:attachmentPayloads(store),password,wizardConfigVersion:2,vaultId:'v2-vault',snapshotId:'v2-snapshot',createdAt:clock()}),recovered=await recoverVaultArtifacts({kitBytes:artifacts.kitBytes,archiveBytes:artifacts.archiveBytes,password});assert.deepEqual(recovered.snapshot.knowledge_graph,knowledge);assert.equal(recovered.snapshot.attachment_payloads['okx-summary'],artifacts.snapshot.attachment_payloads['okx-summary']);});
test('Legacy importer is fail-closed and requires Review',()=>{const source={draft_version:2,vault_title:'Legacy',modules:{'assets-accounts':{entries:[{client_id:'legacy-a',platform:'binance',registration_geography:'Australia',account_class:'Personal'}]},'recovery-conditions':{entries:[{client_id:'legacy-condition',asset_ref:'legacy-a',type:'email',readiness:'PREPARED'}]}}},result=importLegacyDraft(source,{platformTemplates:templates,clock});assert.equal(result.requires_user_review,true);assert.ok(result.blocking_ambiguities.includes('LEGACY_CONDITION_ROWS_AMBIGUOUS:legacy-a'));assert.equal(result.canonical_draft.condition_selections['legacy-a'].selected_condition_ids.length,0);});
test('MemoryProductStore rejects stale revisions and restores exact canonical state',()=>{const initial=createRecoveryMapDraft({clock}),memory=new MemoryProductStore(initial),next=addAccount(initial,'binance-a','binance');memory.commit(next,0);assert.deepEqual(memory.read(),next);assert.throws(()=>memory.commit(next,0),/STALE_DRAFT_REVISION/);});
test('instruction Save reads both visible fields before confirming the saved revision',async()=>{const source=await readFile(new URL('web/v2/v2-app.js',root),'utf8');const handler=source.match(/function renderInstructions\(anchor\).*?function renderAssistants/s)?.[0]??'';assert.match(handler,/Object\.fromEntries\(fields\.map/);assert.ok(handler.indexOf('ProductActions.updateInstruction')<handler.indexOf('ProductActions.confirmInstructionSaved'));assert.doesNotMatch(handler,/node\.onchange/);});
test('editing conditions or locations invalidates Review revision but not saved instruction content',()=>{let store=story1(),saved=store.recovery_instructions['binance-a'].saved_at;store=ProductActions.removeCoverage(store,'coverage-binance-a-authenticator',{expected_revision:store.draft_revision,clock});assert.equal(store.recovery_instructions['binance-a'].saved_at,saved);assert.deepEqual(receipt(store).validation_issues.map(item=>item.issue_code),['LOCATION_COVERAGE_REQUIRED']);});
test('CEO entry uses an Application Shell home action instead of a document-reloading link',async()=>{const html=await readFile(new URL('web/v2/index.html',root),'utf8'),source=await readFile(new URL('web/v2/v2-app.js',root),'utf8');assert.match(html,/id="app-home"/);assert.doesNotMatch(html,/href="\.\/">CJAS Recovery Map V2/);assert.match(html,/id="flow-nav"/);assert.match(source,/const flow=PRODUCT_FLOW/);});
test('attachment presentation exposes business selectors and maps internal scope failures',async()=>{const source=await readFile(new URL('web/v2/v2-app.js',root),'utf8');assert.doesNotMatch(source,/字段\/条件/);assert.doesNotMatch(source,/覆盖条件（逗号分隔）/);assert.match(source,/请选择该附件所属账户、用途以及需要覆盖的恢复条件/);assert.match(source,/data-upload-location/);assert.match(source,/data-file-conditions/);});
test('all six modules bind the shared previous continue Dashboard flow controls',async()=>{const source=await readFile(new URL('web/v2/v2-app.js',root),'utf8');for(const name of ['renderAccounts','renderConditions','renderLocations','renderInstructions','renderAssistants','renderMessage']){const start=source.indexOf(`function ${name}`),next=source.indexOf('\nfunction ',start+10),body=source.slice(start,next<0?source.length:next);assert.match(body,/focus\(/,`${name} must bind the Application Shell controls`);}});

test('Story 7: valid pending Binance account commits before Save and Continue',()=>{let store=createRecoveryMapDraft({clock});store=addAccount(store,'okx-main','okx','主账户');const before=store.draft_revision,result=commitPendingAccount(store,{platform_id:'binance',region:'Australia',account_type:'Personal',display_label:'澳洲账户'},{accountId:'binance-au',platformName:'Binance',clock});assert.equal(result.revision_before,before);assert.equal(result.revision_after,before+1);assert.deepEqual(Object.keys(result.store.accounts),['okx-main','binance-au']);assert.equal(result.store.condition_selections['binance-au'].account_id,'binance-au');assert.throws(()=>commitPendingAccount(store,{platform_id:'binance',region:'',account_type:'Personal'},{accountId:'bad',platformName:'Binance',clock}),/注册国家或地区/);});

test('Story 8: recovery-person report is account-first and translates internal values',async()=>{let store=createRecoveryMapDraft({clock});for(const[id,platform]of[['okx-main','okx'],['binance-au','binance']]){store=addAccount(store,id,platform,id==='okx-main'?'主账户':'澳洲账户');store=select(store,id,['email']);store=item(store,id,'email');store=instruction(store,id);store=await attach(store,{id:`file-${id}`,accountId:id,covers:['email']});}const report=projectReport(store,receipt(store),{platformTemplates:templates});assert.equal(report.account_count,2);assert.equal(report.platform_count,2);assert.equal(report.condition_count,2);assert.equal(report.attachment_count,2);for(const account of report.accounts){assert.equal(account.conditions[0].label,'注册邮箱');assert.equal(account.conditions[0].coverage[0].mode,'逐项位置');assert.equal(account.attachments.length,1);assert.equal(account.attachment_sections[0].attachments[0].account_label,account.label);}const source=await readFile(new URL('web/v2/v2-app.js',root),'utf8'),renderer=source.match(/function renderReportV2\(\).*?function renderPassword/s)?.[0]??source.slice(source.indexOf('function renderReportV2'));assert.doesNotMatch(renderer,/escape\(item\.condition_id\)|escape\(file\.account_id\)|escape\(file\.module_id\)/);});

test('Story 9: Kit Archive recovery preserves account and attachment report ownership',async()=>{let store=createRecoveryMapDraft({clock});for(const[id,platform]of[['okx-main','okx'],['binance-au','binance']]){store=addAccount(store,id,platform,id==='okx-main'?'主账户':'澳洲账户');store=select(store,id,['email']);store=item(store,id,'email');store=instruction(store,id);store=await attach(store,{id:`file-${id}`,accountId:id,covers:['email']});}const validation=receipt(store),before=projectReport(store,validation,{platformTemplates:templates}),knowledge=mapProductToKnowledgeV2(store,validation,{platformTemplates:templates,reviewedAt:clock()}),password='River-Lantern-27-Mango',artifacts=await createVaultArtifacts({knowledgeGraph:knowledge,attachmentPayloads:attachmentPayloads(store),password,wizardConfigVersion:2,vaultId:'story-9-vault',snapshotId:'story-9',createdAt:clock()}),recovered=await recoverVaultArtifacts({kitBytes:artifacts.kitBytes,archiveBytes:artifacts.archiveBytes,password}),after=projectRecoveredReport(recovered.snapshot);assert.equal(after.account_count,before.account_count);assert.equal(after.attachment_count,before.attachment_count);for(const account of after.accounts){assert.equal(account.attachments.length,1);const file=await recoverAttachmentForDownload(recovered.snapshot,account.attachments[0].attachment_id);assert.deepEqual(file.bytes,bytes);assert.equal(account.attachments[0].account_id,account.account_id);}});

test('attachment center starts with explicit choices and filters purpose by module',async()=>{const source=await readFile(new URL('web/v2/v2-app.js',root),'utf8');assert.match(source,/附件用于什么<select[^>]+><option value="">请选择/);assert.match(source,/具体用途<select[^>]+><option value="">请选择/);assert.match(source,/const attachmentPurposes=\{accounts:/);assert.match(source,/reassignAttachment/);});

test('Story 10: module 3 attachment mutation preserves active module and continues to module 4',async()=>{const state=createApplicationState();enterApplicationView(state,'locations');let store=story1(),before=store.draft_revision;beginAttachmentView(state,{return_module:'locations',account_id:'binance-a',module_id:'locations',purpose:'位置说明'});store=await attach(store,{id:'story-10-location',accountId:'binance-a',covers:['email']});assert.equal(state.active_module_id,'locations');assert.equal(store.draft_revision,before+1);assert.equal(leaveAttachmentView(state),'locations');assert.equal(nextProductView('locations'),'instructions');assert.equal(store.location_coverages['coverage-binance-a-email'].description,'脱敏查找说明');assert.ok(store.attachments['story-10-location']);});

test('Story 11: two account instructions and attachments remain isolated after continuing to module 5',async()=>{let store=await story4();const state=createApplicationState();enterApplicationView(state,'instructions');for(const id of ['binance-a','binance-b']){store=await attach(store,{id:`instruction-${id}`,accountId:id,moduleId:'instructions',field:'instructions'});store=ProductActions.updateInstruction(store,id,{instruction_attachment_ids:[`instruction-${id}`]},{expected_revision:store.draft_revision,clock});store=ProductActions.confirmInstructionSaved(store,id,{expected_revision:store.draft_revision,clock});}beginAttachmentView(state,{return_module:'instructions'});assert.equal(leaveAttachmentView(state),'instructions');assert.equal(nextProductView('instructions'),'assistants');for(const id of ['binance-a','binance-b']){assert.match(store.recovery_instructions[id].instruction_text,/独立恢复步骤/);assert.deepEqual(store.recovery_instructions[id].instruction_attachment_ids,[`instruction-${id}`]);}});

test('Story 12: module 5 and 6 attachment routes advance to message and Review without module 1 fallback',()=>{const state=createApplicationState();enterApplicationView(state,'assistants');beginAttachmentView(state,{return_module:'assistants'});assert.equal(state.active_module_id,'assistants');assert.equal(leaveAttachmentView(state),'assistants');assert.equal(nextProductView('assistants'),'message');enterApplicationView(state,'message');beginAttachmentView(state,{return_module:'message'});assert.equal(state.active_module_id,'message');assert.equal(leaveAttachmentView(state),'message');assert.equal(nextProductView('message'),'review');});

test('Story 13: attachment revision race uses the latest Store and stale revision fails without navigation',async()=>{let store=story1(),stale=store.draft_revision;store=await attach(store,{id:'race-file',accountId:'binance-a',covers:['email']});assert.equal(store.draft_revision,stale+1);assert.throws(()=>ProductActions.updateInstruction(store,'binance-a',{instruction_text:'错误旧版本'},{expected_revision:stale,clock}),/STALE_DRAFT_REVISION/);assert.equal(store.recovery_instructions['binance-a'].instruction_text,'从官方入口恢复，核对账户与接收地址后安全转移。');const state=createApplicationState();enterApplicationView(state,'locations');assert.equal(state.active_module_id,'locations');});

test('P1 presentation has bulk location controls, unified instruction save, limits and one contextual attachment zone',async()=>{const source=await readFile(new URL('web/v2/v2-app.js',root),'utf8');assert.match(source,/全选本账户恢复条件/);assert.match(source,/全部取消/);const renderer=source.slice(source.indexOf('function renderInstructionsV2'),source.indexOf('function renderAssistantsV2'));assert.doesNotMatch(renderer,/保存该账户/);assert.match(source,/function moduleAttachmentZone/);assert.match(source,/id="module-attachments"/);assert.match(source,/单文件上限/);assert.match(source,/beginAttachmentView/);});
