import test from'node:test';
import assert from'node:assert/strict';
import {benchmarkCompatibleEndpoints,summarizeUploadPerformance} from'../../src/ui/upload-performance.js';
import {formatByteSize} from'../../src/ui/format-byte-size.js';
import {uploadSignedTransaction} from'../../tools/ar-unified-multi-file-mainnet-pilot/pilot-core.js';

test('performance report separates transaction header from data chunks',async()=>{
  let step=0;const timeline=[0,5,10,20,30,40,50,60,70,80,90,100],clock=()=>timeline[Math.min(step++,timeline.length-1)],uploader={isComplete:false,uploadedChunks:0,totalChunks:2,pctComplete:0,lastResponseStatus:200,async uploadChunk(){if(this.header){this.uploadedChunks++;this.pctComplete=this.uploadedChunks/2*100;}else this.header=true;if(this.uploadedChunks===2)this.isComplete=true;}},transaction={id:'A'.repeat(43),chunks:{chunks:[{minByteRange:0,maxByteRange:262144},{minByteRange:262144,maxByteRange:400000}]}};
  const result=await uploadSignedTransaction({arweave:{transactions:{getUploader:async()=>uploader}},transaction,clock});
  assert.equal(result.chunk_count,2);assert.equal(result.chunks[0].kind,'transaction_header');assert.deepEqual(result.chunks.slice(1).map(item=>item.kind),['data_chunk','data_chunk']);assert.equal(result.performance.data_chunk_count,2);assert.equal(result.performance.payload_bytes,400000);
});

test('instrumentation preserves synchronous getChunk and restores SDK methods',async()=>{let tick=0,seenPromise=false;const clock=()=>++tick*5,transaction={id:'B'.repeat(43),chunks:{chunks:[{minByteRange:0,maxByteRange:3}]},getChunk(){return{chunk:new Uint8Array([1,2,3])};}},originalGetChunk=transaction.getChunk,api={async post(){return{status:200};}},originalPost=api.post,uploader={isComplete:false,uploadedChunks:0,totalChunks:1,pctComplete:0,header:false,async uploadChunk(){if(!this.header){this.header=true;await api.post('tx');return;}const chunk=transaction.getChunk(0);seenPromise=chunk instanceof Promise;await api.post('chunk');this.uploadedChunks=1;this.pctComplete=100;this.isComplete=true;}};const result=await uploadSignedTransaction({arweave:{api,transactions:{getUploader:async()=>uploader}},transaction,clock});assert.equal(seenPromise,false);assert.equal(transaction.getChunk,originalGetChunk);assert.equal(api.post,originalPost);assert.ok(result.performance.get_chunk_ms>0);assert.ok(result.performance.http_ms>0);});

test('summary preserves retry/backoff and throughput evidence',()=>{const report=summarizeUploadPerformance({prepareChunksMs:20,startedAt:0,endedAt:3020,entries:[{kind:'transaction_header',roundtrip_ms:100},{kind:'data_chunk',roundtrip_ms:1000,payload_bytes:262144,http_ms:900,get_chunk_ms:10,proof_validation_ms:20,serialization_ms:0},{kind:'data_chunk',roundtrip_ms:1500,payload_bytes:262144,http_ms:1300,get_chunk_ms:12,proof_validation_ms:25,serialization_ms:0}]});assert.equal(report.header_post_ms,100);assert.equal(report.data_chunk_average_ms,1250);assert.equal(report.http_ms,2200);assert.equal(report.idle_wait_ms,400);assert.ok(report.throughput_mbps>1);});

test('endpoint benchmark accepts only compatible Arweave info and price APIs',async()=>{let time=0;const fetchImpl=async url=>{time+=10;if(url.includes('bad'))return{ok:true,status:200,json:async()=>({}),text:async()=> 'not-price'};return url.endsWith('/info')?{ok:true,status:200,json:async()=>({network:'arweave.N.1'}),text:async()=>''}:{ok:true,status:200,json:async()=>({}),text:async()=> '123'};};const result=await benchmarkCompatibleEndpoints({endpoints:['https://good','https://bad'],archiveBytes:82776339,rounds:1,fetchImpl,clock:()=>time});assert.equal(result.find(item=>item.endpoint==='https://good').compatible,true);assert.equal(result.find(item=>item.endpoint==='https://bad').compatible,false);});

test('customer size presentation uses KB MB and GB without raw bytes',()=>{assert.equal(formatByteSize(1024),'1.0 KB');assert.equal(formatByteSize(82776339,{approximate:true}),'约 78.9 MB');assert.equal(formatByteSize(2*1024**3),'2.0 GB');});
