import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {inflateRawSync} from 'node:zlib';
import {createDynamicDocxTemplate} from '../../src/product-v2/dynamic-docx-templates.js';

const root=new URL('../../',import.meta.url);
const asset=name=>readFile(new URL(`web/v2/assets/templates/${name}`,root));
const accounts=[
  {account_id:'cex',platform_or_wallet:'Binance',category:'中心化交易所',account_type_label:'中心化交易所',selected_recovery_conditions:[{id:'email',label:'注册邮箱'},{id:'authenticator',label:'2FA / Authenticator'},{id:'passkey',label:'Passkey'}]},
  {account_id:'dex',platform_or_wallet:'Curve',category:'DEX / DeFi',account_type_label:'DEX / DeFi',selected_recovery_conditions:[{id:'connected_wallet',label:'关联钱包 / Connected Wallet'},{id:'recovery_phrase',label:'Seed Phrase / 助记词'}]},
  {account_id:'hot',platform_or_wallet:'imToken',category:'自托管钱包',account_type_label:'热钱包 / 软件钱包',selected_recovery_conditions:[{id:'recovery_phrase',label:'Seed Phrase / 助记词'},{id:'wallet_password',label:'钱包访问密码'}]},
  {account_id:'cold',platform_or_wallet:'Keystone',category:'自托管钱包',account_type_label:'冷钱包 / 硬件钱包',selected_recovery_conditions:[{id:'hardware_device',label:'Hardware Wallet / 硬件钱包'},{id:'recovery_phrase',label:'Seed Phrase / 助记词'},{id:'additional_passphrase',label:'Passphrase / 额外口令'}]},
  {account_id:'multi',platform_or_wallet:'Safe',category:'多签钱包',account_type_label:'多签钱包',selected_recovery_conditions:[{id:'multisig_approval',label:'Signer / Threshold'}]}
];
const base={conditions:{summary:'LEGAVIK_Module2_恢复所需条件与资料_Canonical_V2.docx'},locations:{summary:'LEGAVIK_Module3_位置与查找_恢复信息位置汇总_Canonical_V2.docx',single:'LEGAVIK_Module3_位置与查找_单一平台信息_Canonical_V2.docx'},instructions:{summary:'LEGAVIK_Module4_恢复与转移步骤_恢复步骤汇总_Canonical_V2.1.docx',single:'LEGAVIK_Module4_恢复与转移步骤_单一平台恢复步骤_Canonical_V2.1.docx'}};

function entry(bytes,name){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);for(let o=0;o<bytes.length;){if(v.getUint32(o,true)!==0x04034b50)break;const method=v.getUint16(o+8,true),size=v.getUint32(o+18,true),nl=v.getUint16(o+26,true),el=v.getUint16(o+28,true),n=new TextDecoder().decode(bytes.slice(o+30,o+30+nl)),raw=bytes.slice(o+30+nl+el,o+30+nl+el+size);if(n===name)return new TextDecoder().decode(method?inflateRawSync(raw):raw);o+=30+nl+el+size;}throw Error(`missing ${name}`);}
const normalizeXml=xml=>xml.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').replace(/\s*｜\s*/g,'｜').replace(/模块\s*([234])\s*/g,'模块$1').trim();
const xmlText=bytes=>normalizeXml(entry(bytes,'word/document.xml'));
const tableTexts=bytes=>(entry(bytes,'word/document.xml').match(/<w:tbl(?:\s[^>]*)?>[\s\S]*?<\/w:tbl>/g)||[]).map(normalizeXml);
const locationConditionLabels=bytes=>{const tables=entry(bytes,'word/document.xml').match(/<w:tbl(?:\s[^>]*)?>[\s\S]*?<\/w:tbl>/g)||[];return tables.map(table=>(table.match(/<w:tr(?:\s[^>]*)?>[\s\S]*?<\/w:tr>/g)||[]).map(row=>(row.match(/<w:tc(?:\s[^>]*)?>[\s\S]*?<\/w:tc>/g)||[]).map(normalizeXml))).filter(rows=>/^(恢复条件|恢复材料)/.test(rows[0]?.[0]??'')&&rows[0].some(cell=>cell.includes('具体保存位置'))).map(rows=>rows.slice(1).map(row=>row[0]));};
async function generate(moduleId,accountId=null,list=accounts){const canonicalBytes=new Uint8Array(await asset(base[moduleId][accountId?'single':'summary']));return createDynamicDocxTemplate({accounts:list},{moduleId,accountId,canonicalBytes});}

test('Module 2 summary uses Canonical V2 and emits only selected conditions with continuous numbering',async()=>{const x=xmlText((await generate('conditions')).bytes);for(const account of accounts){assert.match(x,new RegExp(account.platform_or_wallet));for(const condition of account.selected_recovery_conditions)assert.match(x,new RegExp(condition.label.replace(/[\/]/g,'\\/')));}assert.doesNotMatch(x,/05\s+恢复条件/);assert.match(x,/01\s+注册邮箱\s+02\s+2FA/);});
test('Module 3 summary maps A+B+C+C+D without treating Connected Wallet as a wallet name',async()=>{const out=await generate('locations'),x=xmlText(out.bytes),tables=tableTexts(out.bytes);for(const name of accounts.map(a=>a.platform_or_wallet))assert.match(x,new RegExp(name));assert.equal((x.match(/C｜自托管钱包\s*填写页/g)||[]).length,2);const dexIdentity=tables.find(value=>value.includes('协议 / 平台名称')&&value.includes('Curve'));assert.equal(dexIdentity,'协议 / 平台名称 Curve 关联钱包名称');assert.deepEqual(locationConditionLabels(out.bytes)[1],accounts[1].selected_recovery_conditions.map(item=>item.label));assert.doesNotMatch(x,/关键原有 \/ 备用设备汇总/);});
test('Module 3 single emits only selected canonical category',async()=>{const markers={cex:['交易所名称','协议 / 平台名称'],dex:['协议 / 平台名称','交易所名称'],hot:['钱包名称 / 品牌','交易所名称'],cold:['钱包名称 / 品牌','多签钱包名称'],multi:['多签钱包名称','钱包名称 / 品牌']};for(const [id,[required,forbidden]] of Object.entries(markers)){const x=xmlText((await generate('locations',id)).bytes);assert.match(x,new RegExp(required.replace(/[\/]/g,'\\/')));assert.doesNotMatch(x,new RegExp(forbidden.replace(/[\/]/g,'\\/')));assert.match(x,new RegExp(accounts.find(a=>a.account_id===id).platform_or_wallet));}});
test('Module 3 uses current online labels and order instead of canonical fixed rows',async()=>{const out=await generate('locations','cex');assert.deepEqual(locationConditionLabels(out.bytes)[0],accounts[0].selected_recovery_conditions.map(item=>item.label));assert.doesNotMatch(xmlText(out.bytes),/交易所登录密码|交易 \/ 资金密码|交易所KYC \/ 身份资料/);});
test('Ledger five conditions preserve exact labels and order in summary and single',async()=>{const ledger={account_id:'ledger',platform_or_wallet:'Ledger',category:'自托管钱包',account_type_label:'冷钱包 / 硬件钱包',selected_recovery_conditions:[{id:'recovery_phrase',label:'Seed Phrase / 助记词'},{id:'hardware_device',label:'Hardware Wallet / 硬件钱包 / 恢复设备'},{id:'device_pin',label:'设备密码 / PIN'},{id:'payment_password',label:'支付密码 / 交易密码（适用时）'},{id:'additional_passphrase',label:'Passphrase / 额外口令'}]};for(const accountId of[null,'ledger']){const out=await generate('locations',accountId,[ledger]);assert.deepEqual(locationConditionLabels(out.bytes)[0],ledger.selected_recovery_conditions.map(item=>item.label));assert.doesNotMatch(locationConditionLabels(out.bytes)[0].join(' '),/其他恢复材料/);}});
test('Cypherock X1 five conditions preserve exact labels and order',async()=>{const cypherock={account_id:'cypherock',platform_or_wallet:'Cypherock X1',category:'自托管钱包',account_type_label:'冷钱包 / 硬件钱包',selected_recovery_conditions:[{id:'hardware_device',label:'Hardware Wallet / 硬件钱包 / 恢复设备'},{id:'device_pin',label:'设备密码 / PIN'},{id:'recovery_phrase',label:'Seed Phrase / 助记词'},{id:'recovery_card',label:'Recovery Card / 备份卡'},{id:'security_device',label:'Security Key / 额外安全设备'}]};for(const accountId of[null,'cypherock'])assert.deepEqual(locationConditionLabels((await generate('locations',accountId,[cypherock])).bytes)[0],cypherock.selected_recovery_conditions.map(item=>item.label));});
test('Core hot wallet keeps the exact online wallet password label',async()=>{const core={account_id:'core',platform_or_wallet:'Core',category:'自托管钱包',account_type_label:'热钱包 / 软件钱包',selected_recovery_conditions:[{id:'recovery_phrase',label:'Seed Phrase / 助记词'},{id:'wallet_password',label:'钱包密码 / 解锁密码'}]};for(const accountId of[null,'core'])assert.deepEqual(locationConditionLabels((await generate('locations',accountId,[core])).bytes)[0],core.selected_recovery_conditions.map(item=>item.label));});
test('Connected Wallet stays out of the name field and becomes its own condition row',async()=>{const dex={account_id:'curve',platform_or_wallet:'Curve',category:'DEX / DeFi',account_type_label:'DEX / DeFi',selected_recovery_conditions:[{id:'connected_wallet',label:'关联钱包 / Connected Wallet'}]};for(const accountId of[null,'curve']){const out=await generate('locations',accountId,[dex]),tables=tableTexts(out.bytes),identity=tables.find(value=>value.includes('协议 / 平台名称')&&value.includes('Curve'));assert.equal(identity,'协议 / 平台名称 Curve 关联钱包名称');assert.deepEqual(locationConditionLabels(out.bytes)[0],['关联钱包 / Connected Wallet']);}});
test('Bybit CEX conditions appear once in online order and never in other/fallback',async()=>{const bybit={account_id:'bybit',platform_or_wallet:'Bybit',category:'中心化交易所',account_type_label:'中心化交易所',selected_recovery_conditions:[{id:'email',label:'注册邮箱'},{id:'phone',label:'注册手机号'},{id:'password',label:'登录密码'},{id:'authenticator',label:'2FA / Authenticator'}]};for(const accountId of[null,'bybit']){const out=await generate('locations',accountId,[bybit]);assert.deepEqual(locationConditionLabels(out.bytes)[0],bybit.selected_recovery_conditions.map(item=>item.label));assert.doesNotMatch(xmlText(out.bytes),/其他恢复材料|其他关键恢复条件/);}});
test('Module 4 summary injects numbered lines and preserves both scenarios',async()=>{const x=xmlText((await generate('instructions')).bytes);for(const name of accounts.map(a=>a.platform_or_wallet))assert.match(x,new RegExp(name));assert.match(x,/01\s+注册邮箱\s+02\s+2FA \/ Authenticator\s+03\s+Passkey/);assert.match(x,/原有 \/ 备用设备仍可用/);assert.match(x,/原有设备不可用 \/ 使用新设备恢复/);assert.match(x,/步骤\s+操作内容\s+必要提示 \/ 结果/);});
test('Module 4 single Binance emits only the A customer block',async()=>{const x=xmlText((await generate('instructions','cex')).bytes);assert.match(x,/A｜中心化交易所\s+仅当当前账户属于托管型中心化交易所时填写/);assert.match(x,/Binance/);assert.doesNotMatch(x,/B｜DEX \/ DeFi\s+仅当/);assert.doesNotMatch(x,/C｜自托管钱包\s+仅当/);assert.match(x,/原有 \/ 备用设备仍可用/);assert.match(x,/原有设备不可用 \/ 使用新设备恢复/);});
test('Module 4 summary and single include every selected condition exactly once with continuous numbering',async()=>{for(const accountId of[null,'cex']){const list=accountId?[accounts.find(account=>account.account_id===accountId)]:accounts.slice(0,4),out=await generate('instructions',accountId,list),confirmations=tableTexts(out.bytes).filter(value=>value.includes('确认结果 / 说明')&&/恢复条件已准备/.test(value));assert.equal(confirmations.length,list.length);for(const [index,account] of list.entries()){const table=confirmations[index];account.selected_recovery_conditions.forEach((condition,i)=>{assert.equal((table.match(new RegExp(condition.label.replace(/[\/]/g,'\\/'),'g'))||[]).length,1);assert.match(table,new RegExp(`${String(i+1).padStart(2,'0')} ${condition.label.replace(/[\/]/g,'\\/')}`));});}}});
test('every download regenerates from latest upstream conditions',async()=>{const before=xmlText((await generate('instructions','cex')).bytes),changed=accounts.map(a=>a.account_id==='cex'?{...a,selected_recovery_conditions:[{id:'email',label:'注册邮箱'}]}:a),after=xmlText((await generate('instructions','cex',changed)).bytes);assert.match(before,/Passkey/);assert.doesNotMatch(after,/Passkey/);assert.match(after,/01\s+注册邮箱/);});
test('browser integration uses current Module 4 V2.1 and Module 5/6 canonical assets',async()=>{const app=await readFile(new URL('web/v2/v2-app.js',root),'utf8'),generator=await readFile(new URL('src/product-v2/dynamic-docx-templates.js',root),'utf8');assert.doesNotMatch(app,/data-template-module="conditions"/);assert.match(app,/await createDynamicDocxTemplate\(payload,\{moduleId,accountId\}\)/);for(const name of['Module5_协助人_Canonical_V2','Module6_给未来恢复人的嘱托_Canonical_V3\\.1'])assert.match(app,new RegExp(name));for(const name of['Module4_恢复与转移步骤_恢复步骤汇总_Canonical_V2\\.1','Module4_恢复与转移步骤_单一平台恢复步骤_Canonical_V2\\.1'])assert.match(generator,new RegExp(name));assert.doesNotMatch(app,/formalTemplateAssets=\{accounts:/);assert.match(app,/buildFutureModule3TemplatePayload\(store/);assert.match(app,/buildFutureModule4TemplatePayload\(store/);});
