import test from 'node:test';
import assert from 'node:assert/strict';
import {projectRecoveredReport} from '../../src/product-v2/recovered-report.js';
import {buildRecoveryWorkspaceHtml} from '../../web/map-view.js';
import {embedSystemSummaryDocuments} from '../../src/product-v2/snapshot-mapper.js';
import {createVaultArtifacts,recoverVaultArtifacts} from '../../src/ui/vault-pipeline.js';
import {cryptoEngine} from '../../src/crypto/crypto-engine.js';

const base={schema_version:2,vault_title:'测试 Recovery Map',plan_type:'crypto-assets',reviewed_at:'2026-08-28T00:00:00.000Z',standard_modules:[['assets-accounts',10],['recovery-conditions',20],['locations-finding',30],['recovery-order-exceptions',40],['contacts-assistance',50],['evidence-messages',60]].map(([id,order])=>({id,order})),custom_modules:[],assets:[{id:'hyperliquid',type:'DEX',label:'Hyperliquid',exists:true,platform_hint:'hyperliquid',condition_refs:['condition-hyperliquid-connected_wallet'],location_refs:['location-hyperliquid'],contact_refs:[],step_refs:['step-hyperliquid'],attachment_refs:['hyper-file','module-location'],custom_field_refs:[]}],recovery_conditions:[{id:'condition-hyperliquid-connected_wallet',type:'connected_wallet',exists:true,asset_refs:['hyperliquid'],location_refs:['location-hyperliquid'],fallback_path_refs:[],notes:'',custom_field_refs:['condition-label']}],fallback_paths:[],locations:[{id:'location-hyperliquid',label:'位置说明',type:'summary',finding_instructions:'书房资料夹',access_prerequisites:[],attachment_refs:['hyper-file','module-location'],custom_field_refs:[]}],assistance:{needed:false},contacts:[],recovery_steps:[{id:'step-hyperliquid',sequence:1,risk_level:'low',action:'按官方流程恢复。',completion_check:'完成',failure_action:'',stop_condition:'',asset_refs:['hyperliquid'],condition_refs:['condition-hyperliquid-connected_wallet'],location_refs:['location-hyperliquid'],contact_refs:[],warning_refs:[],attachment_refs:[]}],warnings:[],attachments:[{id:'hyper-file',display_name:'Hyperliquid说明.txt',media_type:'text/plain',byte_length:1,sha256:'a'.repeat(64),module_refs:['locations-finding'],owner_entity_refs:['hyperliquid','scope-account'],purpose:'位置说明',sensitive_acknowledged:true},{id:'module-location',display_name:'位置汇总.txt',media_type:'text/plain',byte_length:1,sha256:'b'.repeat(64),module_refs:['locations-finding'],owner_entity_refs:['location-hyperliquid','scope-module'],purpose:'位置汇总',sensitive_acknowledged:true}],personal_message:{text:'先核对版本。',attachment_refs:[],disclaimer_acknowledged:true},custom_fields:[{id:'scope-account',module_ref:'locations-finding',label:'附件适用范围',field_type:'text',value:'ACCOUNT:hyperliquid'},{id:'scope-module',module_ref:'locations-finding',label:'附件适用范围',field_type:'text',value:'MODULE_SUMMARY'},{id:'condition-label',module_ref:'recovery-conditions',label:'恢复条件显示名称',field_type:'text',value:'关联钱包 / Connected Wallet'}]};
const snapshot={snapshot_version:1,knowledge_graph:base};

test('recovery projection keeps module summary separate from account attachment',()=>{const report=projectRecoveredReport(snapshot);assert.equal(report.accounts[0].attachments.length,1);assert.equal(report.accounts[0].attachments[0].account_label,'Hyperliquid');assert.equal(report.module_attachments.length,1);assert.equal(report.module_attachments[0].account_id,null);assert.equal(report.accounts[0].conditions[0].label,'关联钱包 / Connected Wallet');});
test('workspace follows the approved recovery information architecture and all panels are collapsed',()=>{const html=buildRecoveryWorkspaceHtml(snapshot),markers=['<h2>你的 Recovery Map 已成功恢复</h2>','<strong>如何理解和使用这份 Recovery Map</strong>','<strong>账户与钱包总览</strong>','<strong>填写人给你的特别说明与嘱托</strong>','<strong>按账户逐一恢复</strong>','<strong>协助人</strong>','<strong>填写人原始档案</strong>','<strong>需要帮助？</strong>'];let cursor=-1;for(const marker of markers){const next=html.indexOf(marker);assert.ok(next>cursor,`${marker} should follow the approved order`);cursor=next;}assert.doesNotMatch(html,/<details[^>]+open/);assert.doesNotMatch(html,/01 · RECOVERY WORKSPACE|系统生成汇总文件|按模块查看全部资料|如何使用这份 Recovery Map/);for(const title of ['资产与账户','恢复所需条件与资料','位置与查找','恢复与转移步骤','协助人','给未来恢复人的嘱托'])assert.match(html,new RegExp(title));});
test('workspace guide explains the approved recovery path, materials, and system boundary',()=>{const html=buildRecoveryWorkspaceHtml(snapshot);for(const phrase of ['第一次使用，请按这个顺序','先看账户与钱包总览','先看填写人的特别说明与嘱托','一次只处理一个账户','按照三个问题处理当前账户','不确定时先停止','完成当前账户，再进入下一个','Recovery Map 的六个部分','有什么 → 需要什么 → 在哪里 → 怎么恢复 → 谁可以帮助 → 还有什么特别想告诉你','如何理解不同资料和附件','LEGAVIK依据填写时已有的模块和账户关联帮助你查找资料','在线查看使用手册','下载使用手册'])assert.match(html,new RegExp(phrase));assert.equal((html.match(/class="recovery-guide-item"/g)||[]).length,4);assert.match(html,/\.\/assets\/LEGAVIK-Recovery-Guide-V1\.pdf/);});
test('message area prioritizes Module 6 attachments when no online message exists',()=>{const messageSnapshot=structuredClone(snapshot);messageSnapshot.knowledge_graph.personal_message.text='';messageSnapshot.knowledge_graph.attachments.push({id:'message-video',display_name:'留言.mp4',media_type:'video/mp4',byte_length:10,sha256:'c'.repeat(64),module_refs:['evidence-messages'],owner_entity_refs:['scope-message'],purpose:'补充说明',sensitive_acknowledged:true});messageSnapshot.knowledge_graph.custom_fields.push({id:'scope-message',module_ref:'evidence-messages',label:'附件适用范围',field_type:'text',value:'MODULE_SUMMARY'});const html=buildRecoveryWorkspaceHtml(messageSnapshot);assert.match(html,/没有留下在线文字说明，但留下了 1 个相关附件，请优先查看/);assert.match(html,/视频 1/);});
test('system canonical summaries are embedded as recoverable encrypted payload candidates',async()=>{const docs={module_1:{filename:'Module1.docx',mime_type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',bytes:new Uint8Array([1,2])},module_2:{filename:'Module2.docx',mime_type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',bytes:new Uint8Array([3,4])}},result=await embedSystemSummaryDocuments(base,docs),report=projectRecoveredReport({snapshot_version:1,knowledge_graph:result.knowledge});assert.equal(report.system_files.length,2);assert.deepEqual(Object.keys(result.payloads),['system-generated-module-1','system-generated-module-2']);});
test('snapshot mapping with system files creates and recovers Snapshot Archive and Recovery Kit',async()=>{const docs={module_1:{filename:'Module1.docx',mime_type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',bytes:new Uint8Array([1,2])},module_2:{filename:'Module2.docx',mime_type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',bytes:new Uint8Array([3,4])}},knowledge=structuredClone(base),payloads={'hyper-file':new Uint8Array([7]),'module-location':new Uint8Array([8])};knowledge.attachments[0].sha256=await cryptoEngine.hashHex(payloads['hyper-file']);knowledge.attachments[1].sha256=await cryptoEngine.hashHex(payloads['module-location']);const embedded=await embedSystemSummaryDocuments(knowledge,docs);Object.assign(payloads,embedded.payloads);const artifacts=await createVaultArtifacts({knowledgeGraph:embedded.knowledge,attachmentPayloads:payloads,password:'River-Lantern-27-Mango',wizardConfigVersion:2,vaultId:'workspace-vault',snapshotId:'workspace-snapshot',createdAt:'2026-08-28T00:00:00.000Z'}),recovered=await recoverVaultArtifacts({kitBytes:artifacts.kitBytes,archiveBytes:artifacts.archiveBytes,password:'River-Lantern-27-Mango'});assert.ok(artifacts.snapshot);assert.ok(artifacts.archiveBytes.byteLength);assert.ok(artifacts.kitBytes.byteLength);assert.equal(projectRecoveredReport(recovered.snapshot).system_files.length,2);});
