import test from 'node:test';
import assert from 'node:assert/strict';
import {summarizeVersionUpdateSource,summarizeVersionUpdateRuntime} from '../../src/product-v2/version-update-diagnostics.js';

test('source diagnostic exposes only structural relationships',()=>{const snapshot={knowledge_graph:{schema_version:2,assets:[{id:'account-a',platform_hint:'binance',condition_refs:['condition-secret']}],recovery_conditions:[{id:'condition-secret',type:'email',asset_refs:['account-a'],location_refs:['location-a']}],locations:[{id:'location-a',label:'SECRET LOCATION',finding_instructions:'SECRET BODY',attachment_refs:['attachment-a']}],attachments:[{id:'attachment-a',display_name:'SECRET FILE'}]}};const result=summarizeVersionUpdateSource(snapshot),encoded=JSON.stringify(result);assert.equal(result.accounts[0].conditions[0].all_location_refs_resolve,true);assert.equal(result.accounts[0].conditions[0].has_related_attachment_reference,true);assert.doesNotMatch(encoded,/SECRET|email|condition-secret|location-a|attachment-a/);});

test('runtime diagnostic reports exact missing and duplicate match counts without content',()=>{const coverage=(id,condition)=>({coverage_id:id,account_id:'account-a',covered_condition_ids:[condition],description:'SECRET',location_name:'',attachment_ids:[]}),store={accounts:{'account-a':{account_id:'account-a',platform_id:'binance'}},condition_selections:{'account-a':{selected_condition_ids:['condition-a','condition-b']}},location_coverages:{one:coverage('one','condition-a'),two:coverage('two','condition-a')},attachments:{}},receipt={generation_allowed:false,validation_issues:[{issue_code:'LOCATION_COVERAGE_REQUIRED',account_id:'account-a',missing_parts:['condition-a:DUPLICATE','condition-b:MISSING']}]},result=summarizeVersionUpdateRuntime({source:{account_count:1},store,receipt}),account=result.validation.accounts[0];assert.deepEqual(account.conditions.map(item=>[item.coverage_match_count,item.validator_status]),[[2,'DUPLICATE'],[0,'MISSING']]);assert.doesNotMatch(JSON.stringify(result),/SECRET|condition-a|condition-b/);});

test('browser entry points retain source summary and frozen compatibility diagnostics',async()=>{const {readFile}=await import('node:fs/promises'),recover=await readFile(new URL('../../web/recover.js',import.meta.url),'utf8'),app=await readFile(new URL('../../web/v2/v2-app.js',import.meta.url),'utf8');assert.match(recover,/dataset\.versionUpdateSourceDiagnostics/);assert.match(recover,/sourceDiagnostics:recoveredSourceDiagnostics/);assert.match(app,/__CJAS_V4_MODULE3_DIAGNOSTICS__/);assert.match(app,/dataset\.module3Diagnostics/);assert.match(app,/versionUpdateSourceDiagnostics=event\.data\.sourceDiagnostics/);});

test('V4 legacy diagnostic gate remains enforced without customer-visible diagnostic branding',async()=>{const {readFile}=await import('node:fs/promises'),entry=await readFile(new URL('../../web/canonical-entry-recovery.js',import.meta.url),'utf8'),html=await readFile(new URL('../../web/recover.html',import.meta.url),'utf8');assert.match(entry,/location\.protocol==='https:'/);assert.match(entry,/mode'\)==='version-update'/);assert.match(entry,/version_number'\)==='4'/);assert.match(entry,/releaseIdentity===diagnosticRelease/);assert.match(entry,/当前入口已过期/);assert.match(entry,/打开最新安全入口/);assert.doesNotMatch(entry,/DIAGNOSTIC V4|diagnostic-v4-identity|document\.body\.prepend\(banner\)/);assert.match(html,/meta name="skrek-release"/);});
