import test from 'node:test';
import assert from 'node:assert/strict';
import {createVersionUpdateDraft,removeVersionUpdateAccount} from '../../src/product-v2/version-update-import.js';
import {ProductActions} from '../../src/product-v2/actions.js';
import {removeAttachment} from '../../src/product-v2/attachment-manager.js';
import {validateProductStore} from '../../src/product-v2/validator.js';
import {mapProductToKnowledgeV2,attachmentPayloads} from '../../src/product-v2/snapshot-mapper.js';
import templates from '../../config/recovery-map/v2/platform-templates-v2.json' with {type:'json'};
import rules from '../../config/recovery-map/v2/living-rules-v2.json' with {type:'json'};

const bytes=new TextEncoder().encode('structural fixture'),payload=Buffer.from(bytes).toString('base64url'),clock=()=> '2026-09-04T00:00:00.000Z';
const file=(id,moduleRef,scopeId)=>({id,display_name:`${id}.txt`,media_type:'text/plain',byte_length:bytes.length,sha256:'a'.repeat(64),module_refs:[moduleRef],owner_entity_refs:[scopeId],purpose:'支持资料'});
function source(){
  const ids=[['m3-summary','locations-finding','MODULE_SUMMARY'],['m5-summary','contacts-assistance','MODULE_SUMMARY'],['m6-summary','evidence-messages','MODULE_SUMMARY'],['b-file','contacts-assistance','ACCOUNT:account-b']];
  return{knowledge_graph:{schema_version:2,vault_title:'结构测试',assets:[{id:'account-a',label:'A',platform_hint:'binance',condition_refs:['condition-a']},{id:'account-b',label:'B',platform_hint:'coinbase',condition_refs:['condition-b']}],recovery_conditions:[{id:'condition-a',type:'email',asset_refs:['account-a'],location_refs:[]},{id:'condition-b',type:'phone',asset_refs:['account-b'],location_refs:[]}],locations:[],recovery_steps:[{id:'step-a',asset_refs:['account-a'],action:'步骤 A',stop_condition:'',attachment_refs:[]},{id:'step-b',asset_refs:['account-b'],action:'步骤 B',stop_condition:'',attachment_refs:[]}],assistance:{needed:false},contacts:[],personal_message:{text:'保留',attachment_refs:['m6-summary']},attachments:ids.map(([id,moduleRef])=>file(id,moduleRef,`scope-${id}`)),custom_fields:[{id:'metadata-account-a-region',value:'Australia'},{id:'metadata-account-a-account-type',value:'Personal'},{id:'metadata-account-b-region',value:'Australia'},{id:'metadata-account-b-account-type',value:'Personal'},...ids.map(([id,moduleRef,scope])=>({id:`scope-${id}`,module_ref:moduleRef,label:'附件适用范围',field_type:'text',value:scope}))]},attachment_payloads:Object.fromEntries(ids.map(([id])=>[id,payload]))};
}
const draft=id=>createVersionUpdateDraft(source(),{draftId:id,sourceVersionId:'v4',sourceVersionNumber:4,clock});
const structure=store=>Object.fromEntries(Object.values(store.attachments).map(item=>[item.attachment_id,{module_id:item.module_id,account_id:item.account_id,field_or_condition_id:item.field_or_condition_id,sha256:item.sha256,byte_length:item.byte_length}]));

test('A initial recovery without edits retains module 3/5/6 attachment scopes and passes validation',()=>{const store=draft('a');assert.equal(validateProductStore(store,{platformTemplates:templates,rules}).generation_allowed,true);for(const id of ['m3-summary','m5-summary','m6-summary'])assert.equal(store.attachments[id].field_or_condition_id,'module-summary');});
test('B/C heterogeneous account deletion preserves summaries, clears carrier coverage, and keeps validation stable',()=>{const before=draft('bc'),expected=structure(before),after=removeVersionUpdateAccount(before,'account-a',{confirmCascade:true,expected_revision:before.draft_revision,clock});assert.equal(after.condition_selections['account-a'],undefined);assert.deepEqual(after.condition_selections['account-b'].selected_condition_ids,['phone']);for(const id of ['m3-summary','m5-summary','m6-summary']){const actual=structure(after)[id];assert.deepEqual({module_id:actual.module_id,field_or_condition_id:actual.field_or_condition_id,sha256:actual.sha256,byte_length:actual.byte_length},{module_id:expected[id].module_id,field_or_condition_id:expected[id].field_or_condition_id,sha256:expected[id].sha256,byte_length:expected[id].byte_length});assert.equal(actual.account_id,'account-b');assert.deepEqual(after.attachments[id].covered_condition_ids,[]);}assert.equal(validateProductStore(after,{platformTemplates:templates,rules}).generation_allowed,true);});
test('D deleting one account-scoped attachment affects only its real scope',()=>{const before=draft('d'),after=removeAttachment(before,'b-file',{clock});assert.deepEqual(Object.keys(before.attachments).filter(id=>id!=='b-file'),Object.keys(after.attachments));for(const id of ['m3-summary','m5-summary','m6-summary'])assert.deepEqual(structure(after)[id],structure(before)[id]);});
test('E sequential edits across modules do not cross-bind attachments',()=>{let store=draft('e');store=ProductActions.setConditionSelection(store,'account-a',{selected_condition_ids:[]},{expected_revision:store.draft_revision,clock});store=ProductActions.setPersonalMessage(store,{text:'更新',attachment_ids:['m6-summary']},{expected_revision:store.draft_revision,clock});assert.equal(store.attachments['m5-summary'].module_id,'assistants');assert.equal(store.attachments['m6-summary'].module_id,'message');assert.equal(store.attachments['b-file'].account_id,'account-b');});
test('F/G rehydrate is deterministic and no-op validation cannot invent errors',()=>{const one=draft('one'),two=draft('two');assert.deepEqual(structure(two),structure(one));const a=validateProductStore(one,{platformTemplates:templates,rules}),b=validateProductStore(two,{platformTemplates:templates,rules});assert.deepEqual(a.validation_issues.map(x=>x.issue_code),b.validation_issues.map(x=>x.issue_code));});
test('H module 5/6 references survive carrier account deletion',()=>{const after=removeVersionUpdateAccount(draft('h'),'account-a',{confirmCascade:true,clock});assert.ok(after.attachments['m5-summary']);assert.ok(after.attachments['m6-summary']);assert.deepEqual(after.personal_message.attachment_ids,['m6-summary']);});
test('I Update customer review does not render internal missing parts and unknown errors use customer copy',async()=>{const {readFile}=await import('node:fs/promises'),app=await readFile(new URL('../../web/v2/v2-app.js',import.meta.url),'utf8');assert.doesNotMatch(app,/missing_parts\.map\(part=>`<li>/);assert.match(app,/versionUpdateContext\?'操作未完成，请检查当前页面后重试。'/);});
test('J heterogeneous deletion survives Snapshot round-trip without synthetic coverage growth or orphan refs',()=>{const removed=removeVersionUpdateAccount(draft('roundtrip'),'account-a',{confirmCascade:true,clock}),receipt=validateProductStore(removed,{platformTemplates:templates,rules});assert.equal(receipt.generation_allowed,true);const knowledge=mapProductToKnowledgeV2(removed,receipt,{platformTemplates:templates,reviewedAt:clock()}),payloads=attachmentPayloads(removed),snapshot={knowledge_graph:knowledge,attachment_payloads:Object.fromEntries(Object.entries(payloads).map(([id,value])=>[id,Buffer.from(value).toString('base64url')]))},rehydrated=createVersionUpdateDraft(snapshot,{draftId:'rehydrated',sourceVersionId:'version-v5',sourceVersionNumber:5,clock}),nextReceipt=validateProductStore(rehydrated,{platformTemplates:templates,rules});assert.equal(nextReceipt.generation_allowed,true);assert.deepEqual(Object.keys(rehydrated.accounts),['account-b']);assert.deepEqual(rehydrated.condition_selections['account-b'].selected_condition_ids,['phone']);assert.equal(Object.keys(rehydrated.location_coverages).length,0);for(const id of ['m3-summary','m5-summary','m6-summary']){assert.ok(rehydrated.attachments[id]);assert.deepEqual(rehydrated.attachments[id].covered_condition_ids,[]);}assert.equal(Object.values(rehydrated.attachments).some(item=>item.account_id==='account-a'),false);});
test('K deletion impact count excludes module summaries while retaining the warning flow',async()=>{const {readFile}=await import('node:fs/promises'),app=await readFile(new URL('../../web/v2/v2-app.js',import.meta.url),'utf8');assert.match(app,/item\.account_id===accountId&&item\.field_or_condition_id!=='module-summary'/);assert.match(app,/取消选择将同步移除该项目的/);assert.match(app,/恢复条件 \$\{summary\.conditions\} 项/);assert.match(app,/关联附件 \$\{summary\.attachments\} 个/);});
