const clone=value=>structuredClone(value);
const MODULES=['accounts','conditions','locations','steps'];
const CONDITION_LABELS={email:'注册邮箱',phone:'注册手机号',password:'登录密码存在性',authenticator:'Authenticator',passkey:'Passkey',security_key:'Security Key'};

export function createMap(){return{model_version:'reference-v2',revision:0,accounts:[],attachments:[]};}
export function addAccount(map,{id,platform,nickname=''}){const next=clone(map);if(next.accounts.some(item=>item.id===id))throw new Error('DUPLICATE_ACCOUNT');next.accounts.push({id,platform,nickname,selected_conditions:[],locations:{mode:'ITEMIZED',items:{},summary:{text:'',attachment_ids:[],covers:[]}},step:{text:'',attachment_ids:[]},saved:false});next.revision++;return next;}
export function updateAccount(map,id,change){const next=clone(map),account=next.accounts.find(item=>item.id===id);if(!account)throw new Error('ACCOUNT_NOT_FOUND');Object.assign(account,clone(change));next.revision++;return next;}
export function selectConditions(map,id,conditionIds){const next=clone(map),account=next.accounts.find(item=>item.id===id);if(!account)throw new Error('ACCOUNT_NOT_FOUND');account.selected_conditions=[...new Set(conditionIds)];for(const key of Object.keys(account.locations.items))if(!account.selected_conditions.includes(key))delete account.locations.items[key];account.locations.summary.covers=account.locations.summary.covers.filter(key=>account.selected_conditions.includes(key));next.attachments=next.attachments.map(file=>file.account_id===id?{...file,condition_ids:file.condition_ids.filter(key=>account.selected_conditions.includes(key))}:file);account.saved=false;next.revision++;return next;}
export function setItemLocation(map,accountId,conditionId,value){const next=clone(map),account=next.accounts.find(item=>item.id===accountId);if(!account?.selected_conditions.includes(conditionId))throw new Error('CONDITION_NOT_SELECTED');account.locations.items[conditionId]={type:value.type??'',name:value.name??'',text:value.text??'',attachment_ids:[...new Set(value.attachment_ids??[])]};account.saved=false;next.revision++;return next;}
export function setSummaryLocation(map,accountId,{text='',attachment_ids=[],covers=[]}){const next=clone(map),account=next.accounts.find(item=>item.id===accountId);if(!account)throw new Error('ACCOUNT_NOT_FOUND');if(covers.some(id=>!account.selected_conditions.includes(id)))throw new Error('SUMMARY_COVERS_UNSELECTED');account.locations.summary={text,attachment_ids:[...new Set(attachment_ids)],covers:[...new Set(covers)]};account.saved=false;next.revision++;return next;}
export function setStep(map,accountId,{text='',attachment_ids=[]}){const next=clone(map),account=next.accounts.find(item=>item.id===accountId);if(!account)throw new Error('ACCOUNT_NOT_FOUND');account.step={text,attachment_ids:[...new Set(attachment_ids)]};account.saved=false;next.revision++;return next;}
export function saveAccount(map,accountId){const next=clone(map),account=next.accounts.find(item=>item.id===accountId);if(!account)throw new Error('ACCOUNT_NOT_FOUND');account.saved=true;next.revision++;return next;}

export function addAttachment(map,file){const next=clone(map);if(!file.id||next.attachments.some(item=>item.id===file.id))throw new Error('INVALID_ATTACHMENT_ID');if(!next.accounts.some(item=>item.id===file.account_id))throw new Error('INVALID_ATTACHMENT_OWNER');if(!MODULES.includes(file.module_id)||!file.field_id||!file.purpose)throw new Error('INVALID_ATTACHMENT_SCOPE');if(!Number.isSafeInteger(file.byte_length)||file.byte_length<=0||!file.mime||!/^[a-f0-9]{64}$/.test(file.sha256??''))throw new Error('INVALID_ATTACHMENT_TECHNICAL');const account=next.accounts.find(item=>item.id===file.account_id);if((file.condition_ids??[]).some(id=>!account.selected_conditions.includes(id)))throw new Error('INVALID_ATTACHMENT_CONDITION');next.attachments.push({...clone(file),condition_ids:[...new Set(file.condition_ids??[])]});next.revision++;return next;}
export function replaceAttachment(map,id,replacement){const next=clone(map),old=next.attachments.find(item=>item.id===id);if(!old)throw new Error('ATTACHMENT_NOT_FOUND');next.attachments=next.attachments.filter(item=>item.id!==id);return addAttachment(next,{...old,...replacement,id});}
export function removeAttachment(map,id){const next=clone(map);next.attachments=next.attachments.filter(item=>item.id!==id);for(const account of next.accounts){account.locations.summary.attachment_ids=account.locations.summary.attachment_ids.filter(value=>value!==id);for(const location of Object.values(account.locations.items))location.attachment_ids=location.attachment_ids.filter(value=>value!==id);account.step.attachment_ids=account.step.attachment_ids.filter(value=>value!==id);}next.revision++;return next;}

const scopedFile=(map,id,accountId,moduleId,fieldId,conditionId)=>map.attachments.some(file=>file.id===id&&file.account_id===accountId&&file.module_id===moduleId&&file.field_id===fieldId&&(!conditionId||file.condition_ids.includes(conditionId)));
const target=(module,account,field,condition=null)=>({module_id:module,account_id:account.id,field_id:field,condition_id:condition,anchor:`${module}:${account.id}:${condition??field}`});
const issue=(code,account,module,field,message,fix,condition=null)=>({issue_id:`${code}:${account?.id??'map'}:${condition??field}`,code,blocking:true,platform:account?.platform??null,account_id:account?.id??null,account_label:account?`${account.platform}${account.nickname?` · ${account.nickname}`:''}`:'Recovery Map',module_id:module,field_id:field,condition_id:condition,condition_label:condition?CONDITION_LABELS[condition]??condition:null,message,why:'恢复人需要一条完整且明确的第一层恢复路径。',fix,navigation:account?target(module,account,field,condition):{module_id:module,account_id:null,field_id:field,condition_id:null,anchor:`${module}:map:${field}`}});

export function validateCanonical(map){const issues=[];if(!map.accounts.length)issues.push(issue('ACCOUNT_REQUIRED',null,'accounts','accounts','尚未添加账户。','添加至少一个账户。'));const duplicatePlatforms=new Set(map.accounts.filter((item,index,all)=>all.some((other,i)=>i!==index&&other.platform===item.platform)).map(item=>item.platform));for(const account of map.accounts){if(!account.platform)issues.push(issue('PLATFORM_REQUIRED',account,'accounts','platform','未选择平台。','选择平台。'));if(duplicatePlatforms.has(account.platform)&&!account.nickname.trim())issues.push(issue('NICKNAME_REQUIRED',account,'accounts','nickname','同平台多个账户无法区分。','为该账户填写唯一备注名称。'));if(!account.selected_conditions.length)issues.push(issue('CONDITION_REQUIRED',account,'conditions','selected_conditions','尚未选择恢复条件。','至少选择一个实际适用条件。'));const uncovered=[];for(const condition of account.selected_conditions){const item=account.locations.items[condition],itemFiles=item?.attachment_ids?.some(id=>scopedFile(map,id,account.id,'locations','item',condition)),itemComplete=Boolean(item?.type&&item?.name&&(item?.text.trim()||itemFiles)),summary=account.locations.summary,summaryFiles=summary.attachment_ids.some(id=>scopedFile(map,id,account.id,'locations','summary',condition)),summaryComplete=summary.covers.includes(condition)&&Boolean(summary.text.trim()||summaryFiles);if(!itemComplete&&!summaryComplete)uncovered.push(condition);}if(uncovered.length)issues.push({...issue('LOCATION_COVERAGE_REQUIRED',account,'locations','coverage',`${uncovered.map(id=>CONDITION_LABELS[id]??id).join('、')}尚未形成有效位置覆盖。`,'逐项填写位置，或用汇总文字/附件明确覆盖。',uncovered[0]),missing_condition_ids:uncovered});const stepFiles=account.step.attachment_ids.some(id=>scopedFile(map,id,account.id,'steps','step'));if(!account.step.text.trim()&&!stepFiles)issues.push(issue('STEP_REQUIRED',account,'steps','step','缺少恢复与转移步骤。','填写步骤文字或添加归属正确的步骤附件。'));if(!account.saved)issues.push(issue('ACCOUNT_NOT_SAVED',account,'steps','saved','该账户有未确认保存的修改。','保存该账户。'));}
  for(const file of map.attachments){const account=map.accounts.find(item=>item.id===file.account_id);if(!account||!MODULES.includes(file.module_id)||!file.field_id||!file.purpose||file.byte_length<=0||!file.mime||!/^[a-f0-9]{64}$/.test(file.sha256??''))issues.push(issue('ATTACHMENT_INVALID',account??null,file.module_id??'attachments','attachment','附件技术信息或归属无效。','删除附件并从对应账户字段重新添加。'));}
  const unique=[...new Map(issues.map(item=>[item.issue_id,item])).values()];return{valid:unique.length===0,issues:unique};}

export function dashboard(map){const validation=validateCanonical(map),byModule=Object.fromEntries(MODULES.map(id=>[id,{state:'未开始',issues:[]}])) ;for(const item of validation.issues)byModule[item.module_id]?.issues.push(item);for(const id of MODULES){const has=id==='accounts'?map.accounts.length>0:id==='conditions'?map.accounts.some(a=>a.selected_conditions.length):id==='locations'?map.accounts.some(a=>Object.keys(a.locations.items).length||a.locations.summary.covers.length):map.accounts.some(a=>a.step.text||a.step.attachment_ids.length);byModule[id].state=!has?'未开始':byModule[id].issues.length?'进行中':'已完成';}return{revision:map.revision,valid:validation.valid,modules:byModule,uncompleted:validation.issues.length};}
export function review(map){return validateCanonical(map);}
export function generationGate(map){const result=validateCanonical(map);return{allowed:result.valid,issue_ids:result.issues.map(item=>item.issue_id)};}
export function report(map){const validation=validateCanonical(map);return{title:'Recovery Map Reference Report',revision:map.revision,status:validation.valid?'已完成':'未完成',accounts:map.accounts.map(account=>({id:account.id,label:`${account.platform}${account.nickname?` · ${account.nickname}`:''}`,conditions:account.selected_conditions.map(id=>({id,label:CONDITION_LABELS[id]??id,location:itemOrSummary(map,account,id)})),step:account.step,attachments:map.attachments.filter(file=>file.account_id===account.id)})),issues:validation.issues};}
function itemOrSummary(map,account,condition){const item=account.locations.items[condition],summary=account.locations.summary;if(item?.type&&item?.name&&(item.text||item.attachment_ids.some(id=>scopedFile(map,id,account.id,'locations','item',condition))))return{mode:'ITEMIZED',...item};if(summary.covers.includes(condition)&&(summary.text||summary.attachment_ids.some(id=>scopedFile(map,id,account.id,'locations','summary',condition))))return{mode:'SUMMARY',text:summary.text,attachment_ids:summary.attachment_ids};return{mode:'MISSING'};}
export class MemoryDraftRepository{#value=null;save(map){this.#value=clone(map);return this.#value.revision;}load(){return this.#value?clone(this.#value):null;}}
