import test from 'node:test';
import assert from 'node:assert/strict';
import {createMap,addAccount,selectConditions,setItemLocation,setSummaryLocation,setStep,saveAccount,addAttachment,validateCanonical,dashboard,review,generationGate,report,MemoryDraftRepository} from './model.js';

const hash='a'.repeat(64),file=(id,account_id,module_id,field_id,condition_ids=[])=>({id,account_id,module_id,field_id,condition_ids,purpose:'恢复说明',display_name:`${id}.txt`,mime:'text/plain',byte_length:12,sha256:hash});
const finishStep=(map,id)=>saveAccount(setStep(map,id,{text:'从官方入口恢复，核对账户后安全转移。'}),id);

test('Story 1: Binance four conditions all use itemized locations',()=>{let map=addAccount(createMap(),{id:'binance-a',platform:'Binance'});map=selectConditions(map,'binance-a',['email','phone','password','authenticator']);for(const id of map.accounts[0].selected_conditions)map=setItemLocation(map,'binance-a',id,{type:'设备或资料',name:`${id}位置`,text:'脱敏查找说明'});map=finishStep(map,'binance-a');assert.equal(validateCanonical(map).valid,true);assert.equal(report(map).accounts[0].conditions.every(item=>item.location.mode==='ITEMIZED'),true);});
test('Story 2: OKX four conditions use one summary attachment',()=>{let map=addAccount(createMap(),{id:'okx-a',platform:'OKX'}),conditions=['email','phone','password','authenticator'];map=selectConditions(map,'okx-a',conditions);map=addAttachment(map,file('okx-summary','okx-a','locations','summary',conditions));map=setSummaryLocation(map,'okx-a',{attachment_ids:['okx-summary'],covers:conditions});map=finishStep(map,'okx-a');assert.equal(generationGate(map).allowed,true);assert.equal(report(map).accounts[0].conditions.every(item=>item.location.mode==='SUMMARY'),true);});
test('Story 3: Coinbase five conditions mix summary coverage and two itemized locations',()=>{let map=addAccount(createMap(),{id:'coinbase-a',platform:'Coinbase'}),conditions=['email','phone','password','authenticator','passkey'];map=selectConditions(map,'coinbase-a',conditions);map=setSummaryLocation(map,'coinbase-a',{text:'前三项使用同一脱敏保管说明',covers:conditions.slice(0,3)});for(const id of conditions.slice(3))map=setItemLocation(map,'coinbase-a',id,{type:'设备',name:`${id}设备`,text:'设备识别线索'});map=finishStep(map,'coinbase-a');const modes=report(map).accounts[0].conditions.map(item=>item.location.mode);assert.deepEqual(modes,['SUMMARY','SUMMARY','SUMMARY','ITEMIZED','ITEMIZED']);assert.equal(validateCanonical(map).valid,true);});
test('Story 4: two Binance accounts keep conditions, locations, steps and attachments isolated',()=>{let map=addAccount(createMap(),{id:'binance-a',platform:'Binance',nickname:'主账户'});map=addAccount(map,{id:'binance-b',platform:'Binance',nickname:'备用账户'});for(const[id,condition]of[['binance-a','email'],['binance-b','authenticator']]){map=selectConditions(map,id,[condition]);map=addAttachment(map,file(`file-${id}`,id,'locations','item',[condition]));map=setItemLocation(map,id,condition,{type:'设备',name:`${id}位置`,attachment_ids:[`file-${id}`]});map=finishStep(map,id);}const output=report(map);assert.equal(validateCanonical(map).valid,true);assert.deepEqual(output.accounts.map(item=>item.attachments.map(file=>file.account_id)),[['binance-a'],['binance-b']]);assert.notDeepEqual(output.accounts[0].conditions,output.accounts[1].conditions);});
test('Dashboard Review Report and Generation Gate share one Canonical Validator',()=>{let map=addAccount(createMap(),{id:'binance-a',platform:'Binance'});const ids=review(map).issues.map(item=>item.issue_id);assert.deepEqual(generationGate(map).issue_ids,ids);assert.equal(dashboard(map).uncompleted,ids.length);assert.deepEqual(report(map).issues.map(item=>item.issue_id),ids);});
test('Review issue has exact module account condition field and stable navigation anchor',()=>{let map=addAccount(createMap(),{id:'okx-a',platform:'OKX'});map=selectConditions(map,'okx-a',['email']);const issue=review(map).issues.find(item=>item.code==='LOCATION_COVERAGE_REQUIRED');assert.deepEqual(issue.navigation,{module_id:'locations',account_id:'okx-a',field_id:'coverage',condition_id:'email',anchor:'locations:okx-a:email'});});
test('save and re-enter restores the canonical Draft without UI reconstruction',()=>{let map=addAccount(createMap(),{id:'binance-a',platform:'Binance'});map=selectConditions(map,'binance-a',['email']);const repository=new MemoryDraftRepository(),revision=repository.save(map),loaded=repository.load();assert.equal(loaded.revision,revision);assert.deepEqual(loaded,map);loaded.accounts[0].selected_conditions.push('phone');assert.notDeepEqual(repository.load(),loaded);});
test('unselected conditions never create location issues',()=>{let map=addAccount(createMap(),{id:'binance-a',platform:'Binance'});map=selectConditions(map,'binance-a',['email']);const issue=review(map).issues.find(item=>item.code==='LOCATION_COVERAGE_REQUIRED');assert.deepEqual(issue.missing_condition_ids,['email']);});
test('invalid attachment ownership fails closed at the unified manager boundary',()=>{const map=addAccount(createMap(),{id:'binance-a',platform:'Binance'});assert.throws(()=>addAttachment(map,file('bad','missing','locations','summary',[])),/INVALID_ATTACHMENT_OWNER/);});
