const empty=()=>({assets:[],locations:[],contacts:[],devices:[],orders:[],hints:[],warnings:[],attachments:[],custom_categories:[],custom_fields:[]});
const text=(value,fallback='')=>String(value??fallback).trim();const id=(prefix,index)=>`${prefix}-${index+1}`;
export function mapWizardDraftToKnowledge(draft,{vaultTitle='我的恢复计划',now=new Date().toISOString(),attachmentMetadata=[]}={}){
  const map={schema_version:1,vault_title:text(vaultTitle,'我的恢复计划'),reviewed_at:now,next_review_at:'',global_instructions:'按顺序执行并在不确定时停止。',...empty()};const modules=draft?.modules??{};
  for(const [index,item] of (modules['devices-locations']??[]).entries()){const locationId=id('location',index),deviceId=id('device',index);map.locations.push({id:locationId,label:text(item['device-location'],`存放位置 ${index+1}`),location_type:'physical',description:text(item['device-location']),access_prerequisites:[],verification_note:'找到后先核对设备特征',custom_field_refs:[]});map.devices.push({id:deviceId,label:text(item['primary-device'],`设备 ${index+1}`),device_type:'recovery-device',usual_location_ref:locationId,identifying_features:text(item['primary-device']),prerequisites:[],risk_note:'不要在不可信设备上输入认证信息',asset_refs:[],order_refs:[],custom_field_refs:[]});}
  for(const [index,item] of (modules['contacts-assistance']??[]).entries())if(item['has-assistant']!=='no')map.contacts.push({id:id('contact',index),label:text(item['assistant-role'],`协助人 ${index+1}`),role:text(item['assistant-role'],'可信协助人'),contact_method:'由用户线下保存',when_to_contact:'自行恢复遇到阻碍时',reason_to_contact:'提供定位或流程协助',knows:'恢复流程的一部分',does_not_know:'完整认证信息',alternate_contact_ref:'',critical:true,custom_field_refs:[]});
  for(const [index,item] of (modules['recovery-orders-warnings']??[]).entries()){const orderId=id('order',index),warningId=id('warning',index);map.warnings.push({id:warningId,label:`风险警告 ${index+1}`,risk_level:'high',trigger:'执行恢复步骤前',instruction:text(item['risk-warning'],'确认环境可信后再继续'),stop_condition:'发现异常或信息不一致时立即停止',contact_refs:map.contacts[0]?[map.contacts[0].id]:[],order_refs:[orderId],custom_field_refs:[]});map.orders.push({id:orderId,label:`恢复步骤 ${index+1}`,sequence:index+1,action:text(item['first-action']),prerequisites:['确认设备和环境可信'],prerequisite_order_refs:index?[id('order',index-1)]:[],expected_result:text(item['expected-result']),failure_action:text(item['failure-action']),risk_level:'high',asset_refs:[],location_refs:map.locations[0]?[map.locations[0].id]:[],contact_refs:map.contacts[0]?[map.contacts[0].id]:[],device_refs:map.devices[0]?[map.devices[0].id]:[],warning_refs:[warningId],hint_refs:[],attachment_refs:[],custom_field_refs:[]});}
  const assetItems=[...(modules['wallet-assets']??[]).filter(x=>x['wallet-exists']!=='no').map(x=>({label:x['wallet-label'],category:'链上资产',custom:x['wallet-custom']})),...(modules['exchange-custody']??[]).filter(x=>x['exchange-used']!=='no').map(x=>({label:x['exchange-location'],category:'托管平台'})),...(modules['digital-accounts']??[]).filter(x=>x['digital-exists']!=='no').map(x=>({label:x['digital-label'],category:'数字账户与网络资产',custom:x['digital-custom']})),...(modules['business-systems']??[]).filter(x=>x['business-exists']!=='no').map(x=>({label:x['business-label'],category:'企业关键资料',custom:x['business-custom']}))];
  for(const [index,item] of assetItems.entries()){const customRefs=[];for(const [fieldIndex,field] of (item.custom??[]).entries()){const customId=`custom-asset-${index+1}-${fieldIndex+1}`;map.custom_fields.push({id:customId,label:text(field.label,`自定义字段 ${fieldIndex+1}`),value:text(field.value),description:'用户补充信息',owner_refs:[id('asset',index)]});customRefs.push(customId);}map.assets.push({id:id('asset',index),label:text(item.label,`资产线索 ${index+1}`),category:item.category,existence_note:'用户确认存在',recovery_goal:'能够定位并按安全步骤恢复访问能力',location_refs:map.locations[0]?[map.locations[0].id]:[],contact_refs:map.contacts[0]?[map.contacts[0].id]:[],device_refs:map.devices[0]?[map.devices[0].id]:[],order_refs:map.orders[0]?[map.orders[0].id]:[],hint_refs:[],warning_refs:map.warnings[0]?[map.warnings[0].id]:[],attachment_refs:attachmentMetadata.map(a=>a.id),custom_field_refs:customRefs});}
  for(const category of draft?.customCategories??[])map.custom_categories.push({id:category.id,label:text(category.label),description:text(category.description),enabled:true});map.attachments=attachmentMetadata.map(a=>({...a,owner_refs:map.assets[0]?[map.assets[0].id]:[],purpose:text(a.purpose,'帮助识别恢复所需资料'),sensitive_acknowledged:true,custom_field_refs:[]}));return map;
}
