import test from 'node:test';import assert from 'node:assert/strict';
import { mapWizardDraftToKnowledge } from '../../src/ui/knowledge-mapper.js';import { createVaultArtifacts,recoverVaultArtifacts } from '../../src/ui/vault-pipeline.js';import { cryptoEngine } from '../../src/crypto/crypto-engine.js';
const password='CEO local rehearsal 2026';
function draft(label){return {modules:{'wallet-assets':[{'wallet-exists':'yes','wallet-label':label,'wallet-custom':[]}],'exchange-custody':[{'exchange-used':'no'}],'devices-locations':[{'primary-device':'备用电脑','device-location':'上锁文件柜'}],'contacts-assistance':[{'has-assistant':'yes','assistant-role':'可信律师'}],'recovery-orders-warnings':[{'first-action':'核对设备标记','expected-result':'标记一致','failure-action':'停止并联系律师','risk-warning':'环境异常时停止'}]},customCategories:[]};}
async function version(n,label,attachmentBytes=new TextEncoder().encode('中文附件')){const createdAt=n===1?'2026-07-31T00:00:00.000Z':'2026-08-01T00:00:00.000Z',attachmentId=`attachment-${n}`,metadata={id:attachmentId,display_name:'恢复说明 中文.txt',media_type:'text/plain',size:attachmentBytes.length,sha256:await cryptoEngine.hashHex(attachmentBytes)},knowledgeGraph=mapWizardDraftToKnowledge(draft(label),{now:createdAt,attachmentMetadata:[metadata]});return createVaultArtifacts({knowledgeGraph,attachmentPayloads:{[attachmentId]:attachmentBytes},password,wizardConfigVersion:1,vaultId:'vault-demo',snapshotId:`snapshot-version-${n}`,createdAt});}
test('UI model to Snapshot, Kit, archive and new-session recovery',async()=>{const v1=await version(1,'长期资产 V1'),recovered=await recoverVaultArtifacts({kitBytes:new Uint8Array(v1.kitBytes),archiveBytes:new Uint8Array(v1.archiveBytes),password});assert.equal(recovered.snapshot.snapshot_id,'snapshot-version-1');assert.equal(recovered.snapshot.knowledge_graph.assets[0].label,'长期资产 V1');assert.equal(recovered.snapshot.knowledge_graph.attachments[0].display_name,'恢复说明 中文.txt');});
test('wrong password, damaged Kit and damaged archive fail closed',async()=>{const v1=await version(1,'长期资产 V1');await assert.rejects(()=>recoverVaultArtifacts({kitBytes:v1.kitBytes,archiveBytes:v1.archiveBytes,password:'wrong password 123'}));const badKit=new Uint8Array(v1.kitBytes);badKit[0]^=1;await assert.rejects(()=>recoverVaultArtifacts({kitBytes:badKit,archiveBytes:v1.archiveBytes,password}));const badArchive=new Uint8Array(v1.archiveBytes);badArchive[badArchive.length-1]^=1;await assert.rejects(()=>recoverVaultArtifacts({kitBytes:v1.kitBytes,archiveBytes:badArchive,password}));});
test('Version 1 and Version 2 are independent and cross combinations fail',async()=>{const v1=await version(1,'长期资产 V1'),v2=await version(2,'长期资产 V2');assert.equal((await recoverVaultArtifacts({kitBytes:v1.kitBytes,archiveBytes:v1.archiveBytes,password})).snapshot.knowledge_graph.assets[0].label,'长期资产 V1');assert.equal((await recoverVaultArtifacts({kitBytes:v2.kitBytes,archiveBytes:v2.archiveBytes,password})).snapshot.knowledge_graph.assets[0].label,'长期资产 V2');await assert.rejects(()=>recoverVaultArtifacts({kitBytes:v1.kitBytes,archiveBytes:v2.archiveBytes,password}));await assert.rejects(()=>recoverVaultArtifacts({kitBytes:v2.kitBytes,archiveBytes:v1.archiveBytes,password}));});
test('tampered attachment inside encrypted snapshot cannot be forged without authentication failure',async()=>{const v1=await version(1,'长期资产 V1');const tampered=new Uint8Array(v1.archiveBytes);tampered[Math.floor(tampered.length/2)]^=1;await assert.rejects(()=>recoverVaultArtifacts({kitBytes:v1.kitBytes,archiveBytes:tampered,password}));});
