import {validateRecoveryPassword} from '../../src/ui/password-policy.js';
import {cryptoEngine} from '../../src/crypto/crypto-engine.js';
import {createGenericArtifacts,identifyAndValidateFile,quoteProjection} from '../ar-generic-file-mainnet-pilot/pilot-core.js?v=final-whitelist-v2';
import {FILE_FORMAT_LABELS,FILE_INPUT_ACCEPT} from '../ar-generic-file-mainnet-pilot/file-format-policy.js?v=final-whitelist-v2';
import {materialFilename,saveMaterial} from '../ar-generic-file-mainnet-pilot/material-delivery.js';
import {verifyGatewaysParallel} from '../ar-generic-file-mainnet-pilot/gateway-verifier.js';
import {assertBatchSelection,BATCH_LIMITS,mapConcurrent} from './batch-core.js';

const NETWORK='Arweave Mainnet',GATEWAY='https://arweave.net',READ_GATEWAYS=['https://arweave.net','https://ardrive.net'];
const state={items:[],arweave:null,directory:null,address:null,balance:null,batchStartedAt:null,materialsSaved:false};
const $=s=>document.querySelector(s),elapsed=s=>Number((performance.now()-s).toFixed(1)),now=()=>new Date().toISOString(),size=n=>n<1048576?`${(n/1024).toFixed(2)} KB`:`${(n/1048576).toFixed(2)} MiB`,setStatus=t=>{$('#status').textContent=t;};
const policyPromise=fetch('../../config/security/recovery-password-v1.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('密码安全策略无法读取。')));
$('#files').accept=FILE_INPUT_ACCEPT;

function render(){
  $('#rows').innerHTML='';for(const item of state.items){const tr=document.createElement('tr');for(const value of [item.file.name,item.identity?.fileType?.toUpperCase()??'—',size(item.file.size),item.status,item.evidence?.txid??'—',item.evidence?.actual_fee_ar?.toFixed(12)??'—']){const td=document.createElement('td');td.textContent=String(value);tr.appendChild(td);}$('#rows').appendChild(tr);}
  const passed=state.items.filter(x=>x.status==='MAINNET VERIFIED').length,failed=state.items.filter(x=>x.status==='FAILED').length;$('#overall').textContent=`文件 ${state.items.length} · Mainnet验证 ${passed} · 失败 ${failed}`;
  $('#technical').textContent=JSON.stringify({limits:BATCH_LIMITS,file_count:state.items.length,total_original_bytes:state.items.reduce((s,x)=>s+x.file.size,0),total_archive_bytes:state.items.reduce((s,x)=>s+(x.artifacts?.archiveBytes.length??0),0),items:state.items.map(({file,identity,status,evidence,timings,error})=>({filename:file.name,file_type:identity?.fileType,status,evidence,timings,error}))},null,2);
}

async function loadSdk(){if(!globalThis.Arweave){const script=document.createElement('script');script.src='https://unpkg.com/arweave@1.14.4/bundles/web.bundle.min.js';document.head.appendChild(script);await new Promise((resolve,reject)=>{script.onload=resolve;script.onerror=()=>reject(new Error('Arweave SDK加载失败。'));});}state.arweave=Arweave.init({host:'arweave.net',port:443,protocol:'https',timeout:30000});}
async function writeDirectory(name,bytes){const handle=await state.directory.getFileHandle(name,{create:true}),writable=await handle.createWritable();await writable.write(bytes);await writable.close();}
async function saveBytes(bytes,name,mime='application/octet-stream'){if(state.directory){await writeDirectory(name,bytes);return;}await saveMaterial(bytes,name,mime,{preferPicker:true});}
function evidenceBytes(item){return new TextEncoder().encode(JSON.stringify(item.evidence,null,2));}

async function selectFiles(){const files=[...$('#files').files];const summary=assertBatchSelection(files);state.items=[];state.materialsSaved=false;state.directory=null;const identified=await mapConcurrent(files,BATCH_LIMITS.local_concurrency,async file=>{const bytes=new Uint8Array(await file.arrayBuffer()),identity=identifyAndValidateFile(file,bytes);return{file,identity};});for(let i=0;i<files.length;i++){const result=identified[i];state.items.push(result.status==='PASS'?{...result.value,status:'PENDING',timings:{}}:{file:files[i],status:'FAILED',error:result.error.message,timings:{}});}$('#selection').textContent=`已选择 ${summary.file_count} 个文件，共 ${size(summary.total_original_bytes)}。格式：${state.items.map(x=>x.identity?.fileType?.toUpperCase()??'无效').join('、')}`;render();}

async function prepare(){const valid=state.items.filter(x=>x.status==='PENDING');if(!valid.length||valid.length!==state.items.length)throw new Error('Batch中存在无效文件，请修正后重试。');let password=$('#password').value,confirmation=$('#confirmation').value;const policy=await policyPromise,check=validateRecoveryPassword(password,confirmation,$('#ack').checked,{policy,vaultName:'CJAS Batch Mainnet Pilot'});if(!check.valid)throw new Error(check.issues[0].message);try{const results=await mapConcurrent(valid,BATCH_LIMITS.local_concurrency,async item=>{const started=performance.now(),bytes=new Uint8Array(await item.file.arrayBuffer()),artifacts=await createGenericArtifacts({bytes,filename:item.file.name,mimeType:item.file.type,password});item.artifacts=artifacts;item.status='ENCRYPTED';item.timings.local_processing_ms=elapsed(started);item.evidence={status:'LOCAL_ENCRYPTION_PASS',network:NETWORK,broadcasts:0,cost_ar:0,source_filename:artifacts.filename,source_mime:artifacts.mimeType,source_size:bytes.length,source_sha256:artifacts.sourceSha256,archive_size:artifacts.archiveBytes.length,archive_sha256:artifacts.archiveSha256,recovery_kit_identifier:artifacts.pilotId,format_version:'CJAS-GENERIC-FILE-ARCHIVE-V1',max_authorized_fee_ar:BATCH_LIMITS.max_fee_ar_per_file,timings_ms:{...artifacts.timings}};return item;});for(const result of results)if(result.status==='FAIL'){const item=valid[results.indexOf(result)];item.status='FAILED';item.error=result.error.message;}$('#save-materials').disabled=false;$('#quote').disabled=false;render();setStatus('Batch本地加密完成。请选择文件夹保存全部Recovery Kit与Local Encrypted Backup。');}finally{password='';confirmation='';$('#password').value='';$('#confirmation').value='';}}

async function saveMaterials(){if(typeof window.showDirectoryPicker==='function'){state.directory=await window.showDirectoryPicker({mode:'readwrite'});for(const item of state.items.filter(x=>x.status==='ENCRYPTED')){await writeDirectory(materialFilename('Recovery-Kit',item.artifacts,'.cjas'),item.artifacts.kitBytes);await writeDirectory(materialFilename('Local-Encrypted-Backup',item.artifacts,'.cjasfilearchive'),item.artifacts.archiveBytes);}state.materialsSaved=true;setStatus('全部Recovery Kit与Local Encrypted Backup已保存到所选文件夹。');}else{for(const item of state.items.filter(x=>x.status==='ENCRYPTED')){await saveMaterial(item.artifacts.kitBytes,materialFilename('Recovery-Kit',item.artifacts,'.cjas'));await saveMaterial(item.artifacts.archiveBytes,materialFilename('Local-Encrypted-Backup',item.artifacts,'.cjasfilearchive'));}state.materialsSaved=true;setStatus('材料下载已触发；请确认浏览器完成全部下载。');}}

async function quoteBatch(){if(!state.materialsSaved)throw new Error('请先保存全部Recovery Kit与Local Encrypted Backup。');await loadSdk();if(!globalThis.arweaveWallet)throw new Error('未检测到已登录并解锁的ArConnect/Wander。');const permissions=await arweaveWallet.getPermissions().catch(()=>[]);if(!permissions.includes('ACCESS_ADDRESS'))await arweaveWallet.connect(['ACCESS_ADDRESS'],{name:'CJAS Mixed Batch Mainnet Pilot'});state.address=await arweaveWallet.getActiveAddress();const balanceResponse=await fetch(`${GATEWAY}/wallet/${state.address}/balance`,{cache:'no-store'});state.balance=Number(await balanceResponse.text())/1e12;const ready=state.items.filter(x=>x.status==='ENCRYPTED'),results=await mapConcurrent(ready,BATCH_LIMITS.network_concurrency,async item=>{const started=performance.now(),response=await fetch(`${GATEWAY}/price/${item.artifacts.archiveBytes.length}`,{cache:'no-store'});if(!response.ok)throw new Error(`报价HTTP ${response.status}`);const quote=Number(await response.text())/1e12;if(!Number.isFinite(quote)||quote>BATCH_LIMITS.max_fee_ar_per_file)throw new Error(`报价 ${quote} AR 超过单文件上限。`);item.evidence.quote_ar=quote;item.evidence.quote_request_ms=elapsed(started);item.evidence.wallet_public_address=state.address;item.quoted=true;return quote;});for(let i=0;i<results.length;i++)if(results[i].status==='FAIL'){ready[i].status='FAILED';ready[i].error=results[i].error.message;}const total=state.items.reduce((s,x)=>s+(x.evidence?.quote_ar??0),0);if(total>state.balance)throw new Error('钱包余额不足以完成本批次，未进入签名。');$('#quote-result').textContent=`报价文件 ${state.items.filter(x=>x.quoted).length} · 总报价 ${total.toFixed(12)} AR · 钱包余额 ${state.balance.toFixed(12)} AR · 预计余额 ${(state.balance-total).toFixed(12)} AR · 每文件上限 0.12 AR`;$('#broadcast').disabled=state.items.some(x=>!x.quoted||x.status!=='ENCRYPTED');render();setStatus('全部报价完成。请核对总费用；开始后钱包将逐笔显示必要签名。');}

async function signItem(item){const current=await cryptoEngine.hashHex(item.artifacts.archiveBytes);if(current!==item.evidence.archive_sha256)throw new Error('Archive SHA-256已变化，禁止签名。');const tx=await state.arweave.createTransaction({data:item.artifacts.archiveBytes});tx.addTag('Content-Type','application/octet-stream');tx.addTag('App-Name','CJAS-AR-Generic-Batch-Mainnet-Pilot');tx.addTag('Format','CJAS-Generic-File-Archive-V1');tx.addTag('Source-File-Type',item.artifacts.fileType);const fee=Number(tx.reward)/1e12;if(fee>BATCH_LIMITS.max_fee_ar_per_file)throw new Error(`实际费用 ${fee} AR 超过单文件上限。`);item.status='BROADCASTING';render();const started=performance.now();await state.arweave.transactions.sign(tx);item.timings.wallet_signature_ms=elapsed(started);item.tx=tx;item.evidence.actual_fee_ar=fee;}
async function broadcastItem(item){if(item.evidence.broadcasts)throw new Error('检测到重复广播风险。');item.evidence.broadcasts=1;item.status='BROADCASTING';const started=performance.now(),response=await state.arweave.transactions.post(item.tx);item.timings.broadcast_to_txid_ms=elapsed(started);if(![200,202].includes(response.status))throw new Error(`广播失败：HTTP ${response.status}`);Object.assign(item.evidence,{status:'BROADCAST_ACCEPTED',txid:item.tx.id,broadcasted_at:now(),evidence_ready_at:now(),broadcast_to_txid_ms:item.timings.broadcast_to_txid_ms,signature_wait_ms:item.timings.wallet_signature_ms,cost_ar:item.evidence.actual_fee_ar});item.status='EVIDENCE READY';await saveBytes(evidenceBytes(item),materialFilename('Mainnet-Recovery-Evidence',item.artifacts,'.json'),'application/json');return item;}
async function verifyItem(item){const started=performance.now();for(let round=1;round<=24;round++){const result=await verifyGatewaysParallel({gateways:READ_GATEWAYS,txid:item.evidence.txid,expectedSize:item.evidence.archive_size,expectedHash:item.evidence.archive_sha256,hashBytes:b=>cryptoEngine.hashHex(b),timeoutMs:12000});if(result.verified){item.timings.mainnet_verification_ms=elapsed(started);Object.assign(item.evidence,{status:'READY_FOR_INDEPENDENT_RECOVERY',first_downloadable_at:now(),first_downloadable_ms:item.timings.mainnet_verification_ms,download_gateway:result.gateway,mainnet_download_size:result.bytes.length,mainnet_download_sha256:item.evidence.archive_sha256,mainnet_hash_match:true});item.status='MAINNET VERIFIED';await saveBytes(evidenceBytes(item),materialFilename('Mainnet-Recovery-Evidence',item.artifacts,'.json'),'application/json');return;}await new Promise(r=>setTimeout(r,5000));}throw new Error('Mainnet传播验证尚未完成，可稍后使用已保存材料恢复。');}
async function broadcastBatch(){if(state.items.some(x=>x.status!=='ENCRYPTED'||!x.quoted))throw new Error('并非全部文件均已通过报价。');state.batchStartedAt=performance.now();const permissions=await arweaveWallet.getPermissions().catch(()=>[]);if(!permissions.includes('SIGN_TRANSACTION'))await arweaveWallet.connect(['ACCESS_ADDRESS','SIGN_TRANSACTION'],{name:'CJAS Mixed Batch Mainnet Pilot'});$('#broadcast').disabled=true;for(const item of state.items){setStatus(`等待钱包确认 ${item.file.name}（${state.items.indexOf(item)+1}/${state.items.length}）`);try{await signItem(item);}catch(error){item.status='FAILED';item.error=error.message;render();throw error;}render();}setStatus('全部必要签名完成，正在受控并发广播。');const posts=await mapConcurrent(state.items,BATCH_LIMITS.network_concurrency,broadcastItem);for(let i=0;i<posts.length;i++)if(posts[i].status==='FAIL'){state.items[i].status='FAILED';state.items[i].error=posts[i].error.message;}render();const accepted=state.items.filter(x=>x.status==='EVIDENCE READY');setStatus('Mainnet Recovery Evidence已保存，正在并行验证Mainnet完整性。');const checks=await mapConcurrent(accepted,BATCH_LIMITS.network_concurrency,verifyItem);for(let i=0;i<checks.length;i++)if(checks[i].status==='FAIL'){accepted[i].status='FAILED';accepted[i].error=checks[i].error.message;}render();setStatus(state.items.every(x=>x.status==='MAINNET VERIFIED')?'Batch Mainnet创建完成。可进入独立Batch恢复。':'Batch部分失败；成功文件结果已保留。');}

async function run(fn){try{setStatus('处理中……');await fn();}catch(error){setStatus(error.message);render();}}
$('#files').onchange=()=>run(selectFiles);$('#prepare').onclick=()=>run(prepare);$('#save-materials').onclick=()=>run(saveMaterials);$('#quote').onclick=()=>run(quoteBatch);$('#broadcast').onclick=()=>run(broadcastBatch);render();
