import {cryptoEngine} from '../../src/crypto/crypto-engine.js';
import {Pbkdf2Provider} from '../../src/crypto/kdf-provider.js';
import {recoveryKitBuilder} from '../../src/recovery-kit/recovery-kit-builder.js';
import {decodeGenericArchive,genericArchiveAad} from '../ar-generic-file-mainnet-pilot/generic-archive.js?v=final-whitelist-v2';
import {createFileDelivery} from '../ar-generic-file-mainnet-pilot/recovery-delivery.js';
import {verifyGatewaysParallel} from '../ar-generic-file-mainnet-pilot/gateway-verifier.js';
import {BATCH_LIMITS,mapConcurrent,pairRecoveryMaterials} from './batch-core.js';

const GATEWAYS=['https://arweave.net','https://ardrive.net'],state={directory:null,results:[]},$=s=>document.querySelector(s),elapsed=s=>Number((performance.now()-s).toFixed(1)),hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');
async function readEvidenceFiles(files){return Promise.all([...files].map(async file=>({name:file.name,evidence:JSON.parse(await file.text())})));}
async function readKitFiles(files){return Promise.all([...files].map(async file=>({name:file.name,bytes:new Uint8Array(await file.arrayBuffer())})));}
async function fetchArchive(evidence){const started=performance.now();for(let round=1;round<=24;round++){const result=await verifyGatewaysParallel({gateways:GATEWAYS,txid:evidence.txid,expectedSize:evidence.archive_size,expectedHash:evidence.archive_sha256,hashBytes:b=>cryptoEngine.hashHex(b),timeoutMs:12000});if(result.verified)return{...result,total_ms:elapsed(started)};await new Promise(r=>setTimeout(r,5000));}throw new Error('Mainnet仍在传播，请稍后使用同一组材料重试。');}
async function saveRecovered(result){if(state.directory){const handle=await state.directory.getFileHandle(result.filename,{create:true}),writable=await handle.createWritable();await writable.write(result.bytes);await writable.close();return;}createFileDelivery({bytes:result.bytes,filename:result.filename,mimeType:result.mime}).download();}
async function recoverPair(pair){const started=performance.now(),downloaded=await fetchArchive(pair.evidence),archive=decodeGenericArchive(downloaded.bytes),password=$('#password').value,key=await recoveryKitBuilder.unwrapKit({kitBytes:pair.kitEntry.bytes,password,kdfProvider:new Pbkdf2Provider(),expectedSnapshotId:pair.kitEntry.parsed.snapshot_id,expectedCiphertextSha256:pair.evidence.archive_sha256});try{const bytes=await cryptoEngine.decryptSnapshot({algorithm:'AES-256-GCM',nonce:archive.nonce,aad:archive.aad,ciphertext:archive.ciphertext},{dataKey:key,expectedAad:genericArchiveAad()}),sha=await cryptoEngine.hashHex(bytes),match=bytes.length===pair.evidence.source_size&&sha===pair.evidence.source_sha256&&bytes.length===archive.originalSize&&sha===hex(archive.originalSha256Bytes);if(!match)throw new Error('恢复文件SHA-256或字节长度不一致。');const result={filename:archive.filename,mime:archive.mimeType,bytes,status:'PASS',gateway:downloaded.gateway,size:bytes.length,sha256:sha,sha_match:true,byte_match:true,total_recovery_ms:elapsed(started),gateway_total_ms:downloaded.total_ms};if(state.directory)await saveRecovered(result);return result;}finally{cryptoEngine.wipeSensitiveReference(key);}}
function render(){const body=$('#rows');body.innerHTML='';for(const result of state.results){const row=document.createElement('tr');for(const value of [result.filename??result.material??'未知',result.status,result.gateway??'—',result.total_recovery_ms?`${result.total_recovery_ms} ms`:'—',result.sha_match&&result.byte_match?'SHA + byte PASS':'—']){const td=document.createElement('td');td.textContent=String(value);row.appendChild(td);}const action=document.createElement('td');if(result.status==='PASS'){const button=document.createElement('button');button.textContent='下载此文件';button.onclick=()=>run(()=>saveRecovered(result));action.appendChild(button);}row.appendChild(action);body.appendChild(row);}$('#download-all').disabled=!state.results.length||state.results.some(x=>x.status!=='PASS');$('#technical').textContent=JSON.stringify({concurrency:BATCH_LIMITS.network_concurrency,results:state.results.map(({bytes,...result})=>result)},null,2);}
async function recoverBatch(){const evidenceFiles=$('#evidence-files').files,kitFiles=$('#kit-files').files;let password=$('#password').value;if(!evidenceFiles.length||!kitFiles.length||!password)throw new Error('请选择全部Mainnet Recovery Evidence、Recovery Kit并输入Batch Recovery Password。');const overall=performance.now();try{const pairs=pairRecoveryMaterials(await readEvidenceFiles(evidenceFiles),await readKitFiles(kitFiles)),outputs=await mapConcurrent(pairs,BATCH_LIMITS.network_concurrency,recoverPair);state.results=outputs.map((output,index)=>output.status==='PASS'?output.value:{material:pairs[index].evidenceEntry.name,status:'FAIL',error:output.error.message});render();const pass=state.results.filter(x=>x.status==='PASS').length;$('#status').textContent=`Batch恢复完成：${pass}/${pairs.length} PASS · 总耗时 ${elapsed(overall)} ms。${pass===pairs.length?'全部SHA-256及byte-for-byte一致。':'失败文件已明确保留，未静默跳过。'}`;}finally{password='';$('#password').value='';}}
async function run(fn){try{$('#status').textContent='处理中……';await fn();}catch(error){$('#status').textContent=error.message;render();}}
$('#destination').onclick=()=>run(async()=>{if(typeof window.showDirectoryPicker!=='function')throw new Error('当前浏览器不支持文件夹选择，将使用逐文件下载fallback。');state.directory=await window.showDirectoryPicker({mode:'readwrite'});$('#status').textContent='恢复保存文件夹已选择。';});$('#recover').onclick=()=>run(recoverBatch);render();
$('#download-all').onclick=()=>run(async()=>{if(!state.results.length||state.results.some(x=>x.status!=='PASS'))throw new Error('全部文件恢复PASS后才可批量下载。');if(!state.directory&&typeof window.showDirectoryPicker==='function')state.directory=await window.showDirectoryPicker({mode:'readwrite'});for(const result of state.results)await saveRecovered(result);$('#status').textContent=`已交付 ${state.results.length} 个恢复文件。`;});
