import { createVaultArtifacts,recoverVaultArtifacts } from '../../src/ui/vault-pipeline.js';
import { mapWizardDraftToKnowledge } from '../../src/ui/knowledge-mapper.js';
import { recoverAttachmentForDownload } from '../../src/recovery/attachment-recovery.js';
import { recoveryKitBuilder } from '../../src/recovery-kit/recovery-kit-builder.js';
import { createRecoveryDelivery,formatFileSize } from './recovery-delivery.js';

const NETWORK='Arweave Mainnet',GATEWAYS=['https://arweave.net','https://ar-io.net','https://g8way.io'],MAX_SINGLE_AR=0.01,MAX_TOTAL_AR=0.01;
const state={arweave:null,archive:null,kit:null,record:null,walletAddress:null,recoveryDelivery:null,kitDownloadRequested:false,evidenceDownloadRequested:false};
const $=selector=>document.querySelector(selector),status=message=>{$('#status').textContent=message;};
const now=()=>new Date().toISOString(),hex=bytes=>Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
async function sha256(bytes){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)));}
function safeDraft(){return{modules:{'wallet-assets':[{'wallet-exists':'yes','wallet-label':'AR Mainnet PDF Pilot','wallet-custom':[]}],'exchange-custody':[{'exchange-used':'no'}],'devices-locations':[{'primary-device':'CEO测试设备','device-location':'仅用于无敏感PDF测试'}],'contacts-assistance':[{'has-assistant':'no'}],'recovery-orders-warnings':[{'first-action':'核对PDF测试附件','expected-result':'SHA-256一致','failure-action':'立即停止','risk-warning':'不得使用真实恢复材料'}]},customCategories:[]};}
function downloadBytes(bytes,name,type){let url;try{url=URL.createObjectURL(new Blob([bytes],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.rel='noopener';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);return true;}catch{if(url)URL.revokeObjectURL(url);throw new Error('文件下载未能启动，请允许浏览器下载后重试。');}}
function setRecoveryStage(message){const item=document.createElement('li');item.textContent=message;$('#recovery-stages').appendChild(item);}
async function generate(){const file=$('#original').files[0],password=$('#create-password').value;if(!file||file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))throw new Error('请选择白名单内的 PDF 文件。');if(!$('#safe-confirm').checked)throw new Error('请先确认测试 PDF 不含任何真实敏感信息。');if(!password)throw new Error('请输入仅由 CEO 掌握的本次测试恢复密码。');const originalBytes=new Uint8Array(await file.arrayBuffer()),originalHash=await sha256(originalBytes),attachmentId='ar-pdf-pilot';const metadata={id:attachmentId,display_name:file.name,media_type:'application/pdf',size:originalBytes.length,sha256:originalHash};const graph=mapWizardDraftToKnowledge(safeDraft(),{now:now(),attachmentMetadata:[metadata]});const started=performance.now(),artifacts=await createVaultArtifacts({knowledgeGraph:graph,attachmentPayloads:{[attachmentId]:originalBytes},password,wizardConfigVersion:2,vaultId:'ar-mainnet-pdf-pilot',snapshotId:`ar-pdf-${Date.now()}`,createdAt:now()}),encryptionMs=performance.now()-started,archiveHash=await sha256(artifacts.archiveBytes);$('#create-password').value='';state.archive=artifacts.archiveBytes;state.kit=artifacts.kitBytes;state.record={pilot:'PDF',network:NETWORK,file_name:file.name,mime_type:'application/pdf',original_size:originalBytes.length,original_sha256:originalHash,archive_size:artifacts.archiveBytes.length,archive_sha256:archiveHash,encryption_ms:Number(encryptionMs.toFixed(1)),wallet_public_address:null,quote_ar:null,actual_fee_ar:null,upload_ms:null,txid:null,broadcasted_at:null,gateway_status:null,download_ms:null,decrypt_ms:null,recovered_sha256:null,sha256_match:null,independent_recovery:null};render();$('#quote').disabled=false;$('#save-kit').disabled=false;$('#save-archive').disabled=false;status('本地加密完成。密码已从输入框清除；Kit、Archive和密码不会上传。');}
async function loadSdk(){if(!globalThis.Arweave){const script=document.createElement('script');script.src='https://unpkg.com/arweave@1.14.4/bundles/web.bundle.min.js';document.head.append(script);await new Promise((resolve,reject)=>{script.onload=resolve;script.onerror=()=>reject(new Error('Arweave SDK 加载失败'));});}state.arweave=Arweave.init({host:'arweave.net',port:443,protocol:'https',timeout:30000});}
async function quote(){if(!state.archive)throw new Error('请先在浏览器本地生成 Archive。');await loadSdk();if(!globalThis.arweaveWallet)throw new Error('未检测到已登录并解锁的 ArConnect/Wander。');const permissions=await arweaveWallet.getPermissions().catch(()=>[]);if(!permissions.includes('ACCESS_ADDRESS')||!permissions.includes('SIGN_TRANSACTION'))await arweaveWallet.connect(['ACCESS_ADDRESS','SIGN_TRANSACTION'],{name:'CJAS PDF Pilot'});const address=await arweaveWallet.getActiveAddress();if(!address)throw new Error('无法取得 CEO 当前测试钱包公开地址。');const response=await fetch(`https://arweave.net/price/${state.archive.length}`);if(!response.ok)throw new Error(`报价失败：HTTP ${response.status}`);const quoteAR=Number(await response.text())/1e12;if(!Number.isFinite(quoteAR)||quoteAR>MAX_SINGLE_AR||quoteAR>MAX_TOTAL_AR)throw new Error(`实时报价 ${quoteAR.toFixed(9)} AR 超过 0.01 AR 上限，已停止。`);state.walletAddress=address;state.record.wallet_public_address=address;state.record.quote_ar=quoteAR;render();$('#upload').disabled=false;status('报价通过。下一步将创建交易并在费用复核后请求 CEO 钱包签名。');}
async function upload(){if(!state.archive||!state.walletAddress||state.record?.quote_ar==null)throw new Error('请先完成钱包地址和实时报价检查。');$('#upload').disabled=true;const started=performance.now(),tx=await state.arweave.createTransaction({data:state.archive});tx.addTag('Content-Type','application/octet-stream');tx.addTag('App-Name','CJAS-AR-Experience-Harness');tx.addTag('Format','CJAS-Vault-Archive');tx.addTag('Test-File-Type','PDF');const actualAR=Number(tx.reward)/1e12;if(!Number.isFinite(actualAR)||actualAR>MAX_SINGLE_AR||actualAR>MAX_TOTAL_AR)throw new Error(`交易实际费用 ${actualAR.toFixed(9)} AR 超出 0.01 AR 上限，未请求签名、未广播。`);await state.arweave.transactions.sign(tx);const response=await state.arweave.transactions.post(tx);if(![200,202].includes(response.status))throw new Error(`广播失败：HTTP ${response.status}`);state.record.actual_fee_ar=actualAR;state.record.upload_ms=Number((performance.now()-started).toFixed(1));state.record.txid=tx.id;state.record.broadcasted_at=now();state.record.gateway_status='BROADCAST_ACCEPTED';render();$('#evidence-ready').hidden=false;try{exportEvidence();}catch{}status(`广播成功：${tx.id}。主网恢复凭证已生成，请保存；关闭前还必须保存 Recovery Kit。`);}
async function gatewayDownload(txid){const failures=[];for(const gateway of GATEWAYS){const started=performance.now();try{const response=await fetch(`${gateway}/${txid}`,{signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);return{bytes:new Uint8Array(await response.arrayBuffer()),gateway,ms:performance.now()-started,status:response.status};}catch(error){failures.push(`${gateway}: ${error.message}`);}}throw new Error(`网关下载失败：${failures.join('；')}`);}
async function importEvidence(){setRecoveryStage('正在读取恢复凭证');const file=$('#evidence-file').files[0];if(!file)throw new Error('请选择此前导出的 Mainnet Evidence JSON。');let parsed;try{parsed=JSON.parse(await file.text());}catch{throw new Error('主网恢复凭证无法识别，请重新选择。');}if(parsed?.pilot!=='PDF'||parsed?.network!==NETWORK||!parsed?.txid||!parsed?.archive_sha256)throw new Error('主网恢复凭证类型或结构不正确。');state.record=parsed;render();status('恢复凭证已读取。当前页面将仅按 TxID 从 Arweave Mainnet 下载。');}
async function recover(){const original=$('#recovery-original').files[0],kit=$('#kit').files[0],password=$('#password').value;if(!state.record?.txid||!kit||!password)throw new Error('请选择主网恢复凭证和 Recovery Kit，并输入恢复密码。原始 PDF 为可选。');$('#recovery-stages').textContent='';$('#recovery-success').hidden=true;state.recoveryDelivery=null;const kitBytes=new Uint8Array(await kit.arrayBuffer());try{recoveryKitBuilder.parseKit(kitBytes);}catch{throw new Error('Recovery Kit 文件类型或内部结构不正确。');}setRecoveryStage('正在连接 Arweave Mainnet');setRecoveryStage('正在下载加密档案');const downloaded=await gatewayDownload(state.record.txid);setRecoveryStage('正在校验档案完整性');const archiveHash=await sha256(downloaded.bytes);if(archiveHash!==state.record.archive_sha256)throw new Error('下载 Archive SHA-256 不一致，已停止解密。');setRecoveryStage('正在浏览器本地解密');const started=performance.now();let recovered;try{recovered=await recoverVaultArtifacts({kitBytes,archiveBytes:downloaded.bytes,password});}catch{throw new Error('恢复密码不正确、Recovery Kit 损坏，或材料不属于同一版本。');}finally{$('#password').value='';}setRecoveryStage('正在生成恢复文件');const attachment=await recoverAttachmentForDownload(recovered.snapshot,'ar-pdf-pilot'),recoveredHash=await sha256(attachment.bytes);if(recoveredHash!==state.record.original_sha256)throw new Error('恢复 PDF 与凭证中的原始 SHA-256 不一致。');let originalMatch=null;if(original){const originalHash=await sha256(new Uint8Array(await original.arrayBuffer()));if(originalHash!==recoveredHash)throw new Error('恢复文件与所选原始 PDF SHA-256 不一致。');originalMatch=true;}state.recoveryDelivery=createRecoveryDelivery({bytes:attachment.bytes,filename:attachment.filename,mimeType:attachment.mimeType,sha256:recoveredHash});state.record.gateway_status=`HTTP ${downloaded.status}`;state.record.gateway=downloaded.gateway;state.record.download_ms=Number(downloaded.ms.toFixed(1));state.record.decrypt_ms=Number((performance.now()-started).toFixed(1));state.record.recovered_filename=attachment.filename;state.record.recovered_mime=attachment.mimeType;state.record.recovered_size=attachment.bytes.length;state.record.recovered_sha256=recoveredHash;state.record.sha256_match=true;state.record.original_file_selected=Boolean(original);state.record.original_file_match=originalMatch;state.record.independent_recovery='PASS';setRecoveryStage('恢复完成');render();$('#success-name').textContent=attachment.filename;$('#success-size').textContent=formatFileSize(attachment.bytes.length);$('#success-integrity').textContent=originalMatch?'已验证；恢复文件与原始文件字节完全一致':'已验证；与主网恢复凭证 SHA-256 一致';$('#recovery-success').hidden=false;status('恢复成功。请点击“下载恢复文件”取得并打开原始 PDF。');}
function render(){const r=state.record;$('#generation-result').textContent=r?`${r.file_name} · ${r.mime_type} · 原始 ${r.original_size} B · Archive ${r.archive_size} B · 加密 ${r.encryption_ms} ms · 原始 SHA-256 ${r.original_sha256} · Archive SHA-256 ${r.archive_sha256}`:'';$('#quote-result').textContent=r?.wallet_public_address?`钱包公开地址：${r.wallet_public_address} · 密文：${r.archive_size} B · 实时报价：${r.quote_ar.toFixed(9)} AR · 当前累计费用：${(r.actual_fee_ar??0).toFixed(9)} AR`:'';$('#evidence').textContent=JSON.stringify(r??{pilot:'PDF',network:NETWORK,total_fee_ar:0,broadcasts:0},null,2);$('#evidence-ready').hidden=!r?.txid;$('#credential-reminder').textContent=r?.txid&&(!state.kitDownloadRequested||!state.evidenceDownloadRequested)?`关闭上传会话前请保存：${!state.kitDownloadRequested?'Recovery Kit ':''}${!state.evidenceDownloadRequested?'Mainnet Evidence JSON':''}`:'';}
function exportEvidence(){if(!state.record)throw new Error('当前没有可导出的 Evidence。');downloadBytes(new TextEncoder().encode(JSON.stringify(state.record,null,2)),`cjas-pdf-pilot-evidence-${Date.now()}.json`,'application/json');state.evidenceDownloadRequested=true;render();}
async function run(action){try{status('处理中……');await action();}catch(error){status(error.message);}}
$('#generate').onclick=()=>run(generate);$('#quote').onclick=()=>run(quote);$('#upload').onclick=()=>run(upload);$('#import-evidence').onclick=()=>run(importEvidence);$('#recover').onclick=()=>run(recover);$('#export').onclick=()=>run(exportEvidence);$('#save-kit').onclick=()=>{if(state.kit&&downloadBytes(state.kit,'CJAS-PDF-Pilot.cjas','application/octet-stream')){state.kitDownloadRequested=true;render();}};$('#save-archive').onclick=()=>state.archive&&downloadBytes(state.archive,'CJAS-PDF-Pilot.cjasvault','application/octet-stream');$('#download-recovered').onclick=()=>run(()=>state.recoveryDelivery?state.recoveryDelivery.download():Promise.reject(new Error('尚无可下载的恢复文件。')));$('#download-again').onclick=()=>run(()=>state.recoveryDelivery?state.recoveryDelivery.download():Promise.reject(new Error('尚无可再次下载的恢复文件。')));addEventListener('beforeunload',event=>{if(state.record?.txid&&(!state.kitDownloadRequested||!state.evidenceDownloadRequested)){event.preventDefault();event.returnValue='';}});render();
