import {validateRecoveryPassword} from '../../src/ui/password-policy.js';
import {cryptoEngine} from '../../src/crypto/crypto-engine.js';
import {FILE_INPUT_ACCEPT} from '../ar-generic-file-mainnet-pilot/file-format-policy.js?v=final-whitelist-v2';
import {saveMaterial} from '../ar-generic-file-mainnet-pilot/material-delivery.js';
import {verifyGatewaysParallel} from '../ar-generic-file-mainnet-pilot/gateway-verifier.js';
import {createUnifiedVaultArtifacts,UNIFIED_LIMITS,uploadSignedTransaction,validateIncomingFiles} from './pilot-core.js';

const GATEWAY='https://arweave.net',READ_GATEWAYS=['https://arweave.net','https://ardrive.net'],state={items:[],artifacts:null,evidence:null,arweave:null,broadcastAttempted:false,kitSaved:false,backupSaved:false};
const $=s=>document.querySelector(s),elapsed=s=>Number((performance.now()-s).toFixed(1)),size=n=>n<1048576?`${(n/1024).toFixed(2)} KB`:`${(n/1048576).toFixed(2)} MiB`,setStatus=t=>{$('#status').textContent=t;},now=()=>new Date().toISOString();
const policyPromise=fetch('../../config/security/recovery-password-v1.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('密码安全策略无法读取。')));$('#add-files').accept=FILE_INPUT_ACCEPT;
function materialNames(){const id=state.artifacts.snapshotId;return{kit:`Recovery-Kit-CJAS-${id}.cjas`,backup:`Local-Encrypted-Backup-CJAS-${id}.cjasvault`,evidence:`Mainnet-Recovery-Evidence-CJAS-${id}.json`};}
function render(){const body=$('#files');body.innerHTML='';for(const item of state.items){const row=document.createElement('tr');for(const value of [item.file.name,item.identity.fileType.toUpperCase(),size(item.file.size)]){const td=document.createElement('td');td.textContent=value;row.appendChild(td);}const action=document.createElement('td'),remove=document.createElement('button');remove.className='danger';remove.textContent='删除';remove.onclick=()=>{if(state.artifacts)return setStatus('统一Archive生成后不可修改文件集合，请开始新会话。');state.items=state.items.filter(value=>value!==item);render();};action.appendChild(remove);row.appendChild(action);body.appendChild(row);}const total=state.items.reduce((sum,item)=>sum+item.file.size,0);$('#capacity').textContent=`当前 ${state.items.length} 个文件 · ${size(total)} / 50 MiB`;$('#technical').textContent=JSON.stringify({file_count:state.items.length,total_original_bytes:total,archive_size:state.artifacts?.archiveBytes.length??null,evidence:state.evidence},null,2);}
async function addFiles(){if(state.artifacts)throw new Error('统一Archive生成后不可继续添加，请开始新会话。');const added=await validateIncomingFiles($('#add-files').files,state.items);state.items.push(...added);$('#add-files').value='';render();setStatus(`已追加 ${added.length} 个文件，原有文件未被覆盖。`);}
async function create(){if(state.artifacts)throw new Error('本会话已生成统一Archive；如需修改文件集合，请开启新会话。');if(!state.items.length)throw new Error('请先添加文件。');let password=$('#password').value,confirmation=$('#confirmation').value;const policy=await policyPromise,check=validateRecoveryPassword(password,confirmation,$('#ack').checked,{policy,vaultName:'CJAS Unified Multi-File Archive Pilot'});if(!check.valid)throw new Error(check.issues[0].message);try{const started=performance.now();state.artifacts=await createUnifiedVaultArtifacts({items:state.items,password});state.evidence={status:'LOCAL_ENCRYPTION_PASS',network:'Arweave Mainnet',broadcasts:0,cost_ar:0,source_filename:'CJAS Unified Multi-File Collection',source_mime:'application/vnd.cjas.snapshot+json',source_size:state.artifacts.totalOriginalBytes,source_sha256:state.artifacts.snapshot.integrity.snapshot_payload_sha256,archive_filename:state.artifacts.archiveName,archive_size:state.artifacts.archiveBytes.length,archive_sha256:state.artifacts.ciphertextSha256,recovery_kit_identifier:state.artifacts.snapshotId,format_version:'CJAS-VAULT-ARCHIVE-V1',timings_ms:{local_create_ms:elapsed(started)},txid:null};$('#create-result').textContent=`统一生成完成：${state.artifacts.fileCount}个文件 · 原始总量 ${size(state.artifacts.totalOriginalBytes)} · Archive ${size(state.artifacts.archiveBytes.length)}`;for(const id of ['save-kit','save-backup','quote'])$(`#${id}`).disabled=false;render();setStatus('统一Archive与Recovery Kit已生成。请先保存两份本地材料，再查看报价。');}finally{password='';confirmation='';$('#password').value='';$('#confirmation').value='';}}
async function loadSdk(){if(!globalThis.Arweave){const script=document.createElement('script');script.src='https://unpkg.com/arweave@1.14.4/bundles/web.bundle.min.js';document.head.appendChild(script);await new Promise((resolve,reject)=>{script.onload=resolve;script.onerror=()=>reject(new Error('Arweave SDK加载失败。'));});}state.arweave=Arweave.init({host:'arweave.net',port:443,protocol:'https',timeout:30000});}
async function quote(){if(!state.kitSaved||!state.backupSaved)throw new Error('请先保存Recovery Kit与Local Encrypted Backup。');await loadSdk();if(!globalThis.arweaveWallet)throw new Error('未检测到已登录并解锁的ArConnect/Wander。');const permissions=await arweaveWallet.getPermissions().catch(()=>[]);if(!permissions.includes('ACCESS_ADDRESS'))await arweaveWallet.connect(['ACCESS_ADDRESS'],{name:'CJAS Unified Multi-File Archive Pilot'});const address=await arweaveWallet.getActiveAddress(),started=performance.now(),[price,balance]=await Promise.all([fetch(`${GATEWAY}/price/${state.artifacts.archiveBytes.length}`,{cache:'no-store'}),fetch(`${GATEWAY}/wallet/${address}/balance`,{cache:'no-store'})]),quoteAR=Number(await price.text())/1e12,balanceAR=Number(await balance.text())/1e12;if(!Number.isFinite(quoteAR)||quoteAR<0)throw new Error('未能取得有效的Arweave Mainnet报价，未进入签名。');if(balanceAR<quoteAR)throw new Error('当前钱包余额不足以支付本次实时报价，未进入签名。');Object.assign(state.evidence,{quote_ar:quoteAR,quote_request_ms:elapsed(started),wallet_public_address:address,balance_before_ar:balanceAR,projected_balance_ar:balanceAR-quoteAR,status:'READY_FOR_SINGLE_BROADCAST'});$('#quote-result').textContent=`统一Archive ${size(state.artifacts.archiveBytes.length)} · 实时报价 ${quoteAR.toFixed(12)} AR · 钱包余额 ${balanceAR.toFixed(12)} AR · 预计余额 ${(balanceAR-quoteAR).toFixed(12)} AR · 当前Pilot未设固定费用上限`;$('#broadcast').disabled=false;render();setStatus('实时报价已显示；请确认费用后再请求本次唯一签名。');}
async function broadcast(){if(state.broadcastAttempted)throw new Error('本会话已尝试广播，禁止重复。');if(state.evidence.status!=='READY_FOR_SINGLE_BROADCAST')throw new Error('尚未取得有效实时报价。');const hash=await cryptoEngine.hashHex(state.artifacts.archiveBytes);if(hash!==state.evidence.archive_sha256)throw new Error('Archive SHA-256已变化，禁止广播。');const permissions=await arweaveWallet.getPermissions().catch(()=>[]);if(!permissions.includes('SIGN_TRANSACTION'))await arweaveWallet.connect(['ACCESS_ADDRESS','SIGN_TRANSACTION'],{name:'CJAS Unified Multi-File Archive Pilot'});state.broadcastAttempted=true;$('#broadcast').disabled=true;const tx=await state.arweave.createTransaction({data:state.artifacts.archiveBytes});tx.addTag('Content-Type','application/octet-stream');tx.addTag('App-Name','CJAS-Unified-Multi-File-Archive-Pilot');tx.addTag('Format','CJAS-Vault-Archive-V1');const fee=Number(tx.reward)/1e12;if(!Number.isFinite(fee)||fee<0)throw new Error('无法确认本次交易实际费用，未签名、未广播。');if(state.evidence.balance_before_ar<fee)throw new Error('当前钱包余额不足以支付本次交易，未签名、未广播。');setStatus(`等待CEO确认本次唯一钱包签名；交易费用 ${fee.toFixed(12)} AR。`);const sign=performance.now();await state.arweave.transactions.sign(tx);const signatureMs=elapsed(sign);setStatus('签名完成，正在分块上传统一Archive；不会创建第二笔交易。');const uploaded=await uploadSignedTransaction({arweave:state.arweave,transaction:tx,onProgress:entry=>setStatus(`正在上传统一Archive：${entry.pct_complete}%（${entry.uploaded_chunks}/${entry.total_chunks}块）`)});Object.assign(state.evidence,{status:'BROADCAST_ACCEPTED',txid:uploaded.txid,broadcasts:1,cost_ar:fee,actual_fee_ar:fee,signature_wait_ms:signatureMs,broadcast_to_txid_ms:uploaded.upload_ms,upload_strategy:uploaded.upload_strategy,upload_chunk_count:uploaded.chunk_count,upload_chunk_timings:uploaded.chunks,broadcasted_at:now(),evidence_ready_at:now()});$('#save-evidence').disabled=false;render();setStatus('TxID已取得，Mainnet Recovery Evidence已可保存；正在后台验证Mainnet完整性。');const started=performance.now();for(let round=1;round<=24;round++){const result=await verifyGatewaysParallel({gateways:READ_GATEWAYS,txid:tx.id,expectedSize:state.evidence.archive_size,expectedHash:state.evidence.archive_sha256,hashBytes:bytes=>cryptoEngine.hashHex(bytes),timeoutMs:12000});if(result.verified){Object.assign(state.evidence,{status:'READY_FOR_INDEPENDENT_RECOVERY',first_downloadable_at:now(),first_downloadable_ms:elapsed(started),download_gateway:result.gateway,mainnet_download_size:result.bytes.length,mainnet_download_sha256:state.evidence.archive_sha256,mainnet_hash_match:true});render();$('#broadcast-result').textContent=`TxID ${tx.id} · Mainnet Archive大小与SHA-256验证PASS`;setStatus('统一Archive Mainnet验证完成，可以独立恢复。');return;}await new Promise(resolve=>setTimeout(resolve,5000));}throw new Error('Mainnet仍在传播；Evidence已可保存，请稍后恢复，无需重新广播。');}
async function saveEvidence(){const bytes=new TextEncoder().encode(JSON.stringify(state.evidence,null,2));await saveMaterial(bytes,materialNames().evidence,'application/json',{preferPicker:true});setStatus('Mainnet Recovery Evidence已保存。');}
async function run(fn){try{setStatus('处理中……');await fn();}catch(error){setStatus(error.message);render();}}
$('#add').onclick=()=>run(addFiles);$('#create').onclick=()=>run(create);$('#save-kit').onclick=()=>run(async()=>{const result=await saveMaterial(state.artifacts.kitBytes,materialNames().kit);state.kitSaved=Boolean(result.saved);if(state.kitSaved)setStatus('Recovery Kit已保存。');});$('#save-backup').onclick=()=>run(async()=>{const result=await saveMaterial(state.artifacts.archiveBytes,materialNames().backup);state.backupSaved=Boolean(result.saved);if(state.backupSaved)setStatus('Local Encrypted Backup已保存。');});$('#save-evidence').onclick=()=>run(saveEvidence);$('#quote').onclick=()=>run(quote);$('#broadcast').onclick=()=>run(broadcast);render();
