import {cryptoEngine} from '../../src/crypto/crypto-engine.js';
import {recoveryKitBuilder} from '../../src/recovery-kit/recovery-kit-builder.js';
import {createFileDelivery} from '../ar-generic-file-mainnet-pilot/recovery-delivery.js';
import {verifyGatewaysParallel} from '../ar-generic-file-mainnet-pilot/gateway-verifier.js';
import {recoverUnifiedFiles,validateUnifiedEvidence} from './pilot-core.js';
const GATEWAYS=['https://arweave.net','https://ardrive.net'],state={files:[],directory:null},$=s=>document.querySelector(s),elapsed=s=>Number((performance.now()-s).toFixed(1));
async function fetchArchive(evidence){const started=performance.now();for(let round=1;round<=24;round++){const result=await verifyGatewaysParallel({gateways:GATEWAYS,txid:evidence.txid,expectedSize:evidence.archive_size,expectedHash:evidence.archive_sha256,hashBytes:bytes=>cryptoEngine.hashHex(bytes),timeoutMs:12000});if(result.verified)return{bytes:result.bytes,gateway:result.gateway,totalMs:elapsed(started)};await new Promise(resolve=>setTimeout(resolve,5000));}throw new Error('Mainnet仍在传播，请稍后使用同一组材料重试。');}
async function saveFile(file){if(state.directory){const handle=await state.directory.getFileHandle(file.filename,{create:true}),writable=await handle.createWritable();await writable.write(file.bytes);await writable.close();return;}createFileDelivery({bytes:file.bytes,filename:file.filename,mimeType:file.mimeType}).download();}
function render(){const body=$('#files');body.innerHTML='';for(const file of state.files){const row=document.createElement('tr');for(const value of [file.filename,file.mimeType,`${file.size.toLocaleString('en-AU')} bytes`,file.sha256]){const td=document.createElement('td');td.textContent=value;row.appendChild(td);}const action=document.createElement('td'),button=document.createElement('button');button.textContent='下载此文件';button.onclick=()=>run(()=>saveFile(file));action.appendChild(button);row.appendChild(action);body.appendChild(row);}$('#results').hidden=!state.files.length;}
async function recover(){const evidenceFile=$('#evidence').files[0],kitFile=$('#kit').files[0];let password=$('#password').value;if(!evidenceFile||!kitFile||!password)throw new Error('请选择Mainnet Recovery Evidence、Recovery Kit并输入Recovery Password。');const total=performance.now(),timings={};try{const read=performance.now(),evidence=validateUnifiedEvidence(JSON.parse(await evidenceFile.text())),kitBytes=new Uint8Array(await kitFile.arrayBuffer()),kit=recoveryKitBuilder.parseKit(kitBytes);timings.materials_read_ms=elapsed(read);if(kit.snapshot_id!==evidence.recovery_kit_identifier)throw new Error('这两份恢复材料不属于同一次创建。');const downloaded=await fetchArchive(evidence);timings.gateway_download_ms=downloaded.totalMs;const decrypted=await recoverUnifiedFiles({archiveBytes:downloaded.bytes,kitBytes,password});timings.decrypt_and_integrity_ms=decrypted.recoveryMs;state.files=decrypted.files;timings.total_recovery_ms=elapsed(total);$('#technical').textContent=JSON.stringify({status:'PASS',txid:evidence.txid,gateway:downloaded.gateway,file_count:state.files.length,total_recovered_bytes:state.files.reduce((sum,file)=>sum+file.size,0),all_sha_match:state.files.every(file=>file.sha_match),all_byte_match:state.files.every(file=>file.byte_match),timings_ms:timings},null,2);render();$('#status').textContent=`统一多文件恢复PASS：${state.files.length}个文件全部SHA-256及byte-for-byte一致。`;}finally{password='';$('#password').value='';}}
async function downloadAll(){if(!state.files.length)throw new Error('尚无恢复文件。');if(typeof window.showDirectoryPicker==='function')state.directory=await window.showDirectoryPicker({mode:'readwrite'});for(const file of state.files)await saveFile(file);$('#status').textContent=`已交付全部 ${state.files.length} 个恢复文件。`;}
async function run(fn){try{$('#status').textContent='处理中……';await fn();}catch(error){$('#status').textContent=error.message;}}
$('#recover').onclick=()=>run(recover);$('#download-all').onclick=()=>run(downloadAll);render();
