import {cryptoEngine} from '../../src/crypto/crypto-engine.js';
import {Pbkdf2Provider} from '../../src/crypto/kdf-provider.js';
import {RecoveryKitBuilder} from '../../src/recovery-kit/recovery-kit-builder.js';
import {EXPERIENCE_KDF_PARAMETERS} from '../../src/ui/vault-pipeline.js';
import {decodeGenericArchive,encodeGenericArchive,genericArchiveAad,GENERIC_ARCHIVE_LIMITS} from './generic-archive.js?v=final-whitelist-v2';
import {FILE_FORMAT_LABELS,resolveFileIdentity} from './file-format-policy.js?v=final-whitelist-v2';

const KIT=new RecoveryKitBuilder(),KDF=new Pbkdf2Provider(),hex=bytes=>Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join(''),fromHex=value=>Uint8Array.from(value.match(/.{2}/g)??[],part=>Number.parseInt(part,16)),elapsed=start=>Number((performance.now()-start).toFixed(1));
export function sanitizeFilename(name){const clean=String(name??'').split(/[\\/]/).pop().replace(/[\u0000-\u001f\u007f]/g,'').replace(/[:*?"<>|]/g,'_').trim();if(!clean||clean==='.'||clean==='..')throw new Error('文件名无效。');return clean.slice(0,240);}
function has(bytes,needle){const text=new TextDecoder('latin1').decode(bytes);return text.includes(needle);}
const starts=(bytes,values,offset=0)=>values.every((value,index)=>bytes[offset+index]===value);
const ftypOffset=bytes=>{const limit=Math.min(bytes.length-4,4096);for(let offset=4;offset<=limit;offset++)if(starts(bytes,[102,116,121,112],offset))return offset;return-1;};
const isoBmff=bytes=>bytes.length>=12&&ftypOffset(bytes)>=4;
const heifBrand=bytes=>{const offset=ftypOffset(bytes);if(offset<4)return false;const brands=new TextDecoder('latin1').decode(bytes.slice(offset+4,Math.min(bytes.length,offset+60)));return['heic','heix','hevc','hevx','heim','heis','hevm','hevs','mif1','msf1','heif'].some(brand=>brands.includes(brand));};
const textContent=bytes=>{if(bytes.includes(0)){const utf16le=starts(bytes,[255,254]),utf16be=starts(bytes,[254,255]);if(!utf16le&&!utf16be)return false;try{new TextDecoder(utf16le?'utf-16le':'utf-16be',{fatal:true}).decode(bytes.slice(2));return true;}catch{return false;}}try{new TextDecoder('utf-8',{fatal:true}).decode(bytes);return true;}catch{return false;}};
const waveContainer=bytes=>bytes.length>=12&&(has(bytes.slice(0,4),'RIFF')||has(bytes.slice(0,4),'RIFX')||has(bytes.slice(0,4),'RF64'))&&has(bytes.slice(8,12),'WAVE');
export function identifyAndValidateFile({name,type,size},bytes){
  if(!(bytes instanceof Uint8Array)||!Number.isSafeInteger(size)||size!==bytes.length||size<=0)throw new Error('请选择浏览器可读取的非空文件。');if(size>GENERIC_ARCHIVE_LIMITS.max_file_bytes)throw new Error('单文件不得超过 10 MiB（10,485,760 bytes）。');const filename=sanitizeFilename(name),identity=resolveFileIdentity(filename,type);
  if(!identity)throw new Error(`文件扩展名与 MIME 不在正式白名单内：${FILE_FORMAT_LABELS.join('、')}。`);const{fileType,mimeType}=identity;
  const valid=fileType==='pdf'?starts(bytes,[37,80,68,70,45]):fileType==='txt'?textContent(bytes):fileType==='png'?starts(bytes,[137,80,78,71,13,10,26,10]):fileType==='jpeg'?bytes.length>=4&&starts(bytes,[255,216])&&has(bytes.slice(Math.max(0,bytes.length-64)),String.fromCharCode(255,217)):fileType==='heic'?heifBrand(bytes):fileType==='mp3'?bytes.length>=3&&(starts(bytes,[73,68,51])||(bytes[0]===255&&(bytes[1]&0xe0)===0xe0)):fileType==='m4a'?isoBmff(bytes):fileType==='wav'?waveContainer(bytes):fileType==='mp4'||fileType==='mov'?isoBmff(bytes):bytes.length>=22&&starts(bytes,[80,75])&&[3,5,7].includes(bytes[2])&&[4,6,8].includes(bytes[3])&&has(bytes,'[Content_Types].xml')&&has(bytes,'word/document.xml');
  if(!valid)throw new Error(`该文件内容不是可识别的 ${identity.rule.label} 格式。`);return{fileType,filename,mimeType,size};
}
export async function createGenericArtifacts({bytes,filename,mimeType,password,createdAt=new Date().toISOString()}){
  const identity=identifyAndValidateFile({name:filename,type:mimeType,size:bytes.length},bytes),hashStart=performance.now(),sourceSha256=await cryptoEngine.hashHex(bytes),sourceHashMs=elapsed(hashStart);let dataKey,passwordReference=password;
  try{dataKey=cryptoEngine.generateDataKey();const encryptionStart=performance.now(),envelope=await cryptoEngine.encryptSnapshot(bytes,{dataKey,aad:genericArchiveAad()}),encryptionMs=elapsed(encryptionStart),archiveStart=performance.now(),archiveBytes=encodeGenericArchive({nonce:envelope.nonce,ciphertext:envelope.ciphertext,fileType:identity.fileType,filename:identity.filename,mimeType:identity.mimeType,originalSize:bytes.length,originalSha256Bytes:fromHex(sourceSha256)}),archiveGenerationMs=elapsed(archiveStart),archiveHashStart=performance.now(),archiveSha256=await cryptoEngine.hashHex(archiveBytes),archiveHashMs=elapsed(archiveHashStart),pilotId=`generic-${identity.fileType}-${sourceSha256.slice(0,16)}-${Date.now()}`,kitStart=performance.now(),kitBytes=await KIT.createKit({password:passwordReference,dataKey,snapshotId:pilotId,ciphertextSha256:archiveSha256,storageLocators:[`${identity.filename}.cjasfilearchive`],kdfProvider:KDF,kdfParameters:EXPERIENCE_KDF_PARAMETERS,createdAt,toolCompatibility:'CJAS-GENERIC-FILE-PILOT-V1'}),kitMs=elapsed(kitStart);
    return{...identity,pilotId,sourceSha256,archiveSha256,archiveBytes,kitBytes,overheadBytes:archiveBytes.length-bytes.length,overheadPercent:(archiveBytes.length-bytes.length)/bytes.length*100,timings:{source_hash_ms:sourceHashMs,aes_256_gcm_ms:encryptionMs,archive_generation_ms:archiveGenerationMs,archive_hash_ms:archiveHashMs,recovery_kit_ms:kitMs}};
  }finally{passwordReference='';if(dataKey)cryptoEngine.wipeSensitiveReference(dataKey);}
}
export async function recoverGenericFile({archiveBytes,kitBytes,password}){const archiveSha256=await cryptoEngine.hashHex(archiveBytes),parsed=decodeGenericArchive(archiveBytes),kit=KIT.parseKit(kitBytes),dataKey=await KIT.unwrapKit({kitBytes,password,kdfProvider:KDF,expectedSnapshotId:kit.snapshot_id,expectedCiphertextSha256:archiveSha256});try{const bytes=await cryptoEngine.decryptSnapshot({algorithm:'AES-256-GCM',nonce:parsed.nonce,aad:parsed.aad,ciphertext:parsed.ciphertext},{dataKey,expectedAad:genericArchiveAad()}),sha256=await cryptoEngine.hashHex(bytes);if(bytes.length!==parsed.originalSize||sha256!==hex(parsed.originalSha256Bytes))throw new Error('恢复文件完整性校验失败。');return{bytes,filename:parsed.filename,mimeType:parsed.mimeType,fileType:parsed.fileType,sha256};}finally{cryptoEngine.wipeSensitiveReference(dataKey);}}
export function quoteProjection({quoteAR,archiveBytes,balanceAR}){const mib=archiveBytes/(1024*1024);return{quote_ar:quoteAR,ar_per_mib:quoteAR/mib,projected_balance_ar:balanceAR-quoteAR,estimated_50_mib_ar:quoteAR/mib*50};}
