import test from 'node:test';import assert from 'node:assert/strict';
import { cryptoEngine } from '../../src/crypto/crypto-engine.js';import { Argon2idProvider,Pbkdf2Provider,detectKdfCapabilities } from '../../src/crypto/kdf-provider.js';import { recoveryKitBuilder } from '../../src/recovery-kit/recovery-kit-builder.js';
const encoder=new TextEncoder(),provider=new Pbkdf2Provider({minIterations:1000}),params={iterations:1000,hash:'SHA-256'},password='正确恢复密码-测试';
test('CryptoEngine AES-GCM round trip',async()=>{const key=cryptoEngine.generateDataKey(),plain=encoder.encode('结构化快照');const encrypted=await cryptoEngine.encryptSnapshot(plain,{dataKey:key});assert.deepEqual(await cryptoEngine.decryptSnapshot(encrypted,{dataKey:key}),plain);});
test('tampered ciphertext fails closed',async()=>{const key=cryptoEngine.generateDataKey(),encrypted=await cryptoEngine.encryptSnapshot(encoder.encode('data'),{dataKey:key});encrypted.ciphertext[0]^=1;await assert.rejects(cryptoEngine.decryptSnapshot(encrypted,{dataKey:key}),/authentication failed/);});
test('wipeSensitiveReference performs best-effort zeroing',()=>{const key=new Uint8Array([1,2,3]);const result=cryptoEngine.wipeSensitiveReference(key);assert.deepEqual([...key],[0,0,0]);assert.equal(result.best_effort_only,true);});
test('KDF capability detection does not silently substitute',()=>{const caps=detectKdfCapabilities([provider,new Argon2idProvider()]);assert.equal(caps[0].available,true);assert.equal(caps[1].available,false);});
test('Argon2id unavailable fails explicitly',async()=>await assert.rejects(new Argon2idProvider().deriveKey('password',new Uint8Array(16),{memory_kib:8192,iterations:1,parallelism:1}),/unavailable/));
test('PBKDF2 rejects unsafe parameters',async()=>await assert.rejects(provider.deriveKey('password',new Uint8Array(16),{iterations:999,hash:'SHA-256'}),/iterations/));

async function kit(snapshotId='snapshot-001',hash='a'.repeat(64)){const dataKey=cryptoEngine.generateDataKey();const bytes=await recoveryKitBuilder.createKit({password,dataKey,snapshotId,ciphertextSha256:hash,storageLocators:['local:one'],kdfProvider:provider,kdfParameters:params,createdAt:'2026-07-31T12:00:00Z'});return {bytes,dataKey};}
test('Recovery Kit round trip unwraps the Data Key',async()=>{const {bytes,dataKey}=await kit();const recovered=await recoveryKitBuilder.unwrapKit({kitBytes:bytes,password,kdfProvider:provider,expectedSnapshotId:'snapshot-001',expectedCiphertextSha256:'a'.repeat(64)});assert.deepEqual(recovered,dataKey);});
test('Recovery Kit explicitly records kdf_id and parameters',async()=>{const {bytes}=await kit();const parsed=recoveryKitBuilder.parseKit(bytes);assert.equal(parsed.kdf.kdf_id,'PBKDF2-HMAC-SHA-256');assert.deepEqual(parsed.kdf.parameters,params);});
test('wrong password fails closed',async()=>{const {bytes}=await kit();await assert.rejects(recoveryKitBuilder.unwrapKit({kitBytes:bytes,password:'错误密码',kdfProvider:provider,expectedSnapshotId:'snapshot-001',expectedCiphertextSha256:'a'.repeat(64)}),/incorrect or Kit is damaged/);});
test('cross-version Kit fails before decryption',async()=>{const {bytes}=await kit();await assert.rejects(recoveryKitBuilder.unwrapKit({kitBytes:bytes,password,kdfProvider:provider,expectedSnapshotId:'snapshot-002',expectedCiphertextSha256:'b'.repeat(64)}),/does not belong/);});
test('tampered Kit fails closed',async()=>{const {bytes}=await kit();const changed=new Uint8Array(bytes);changed[changed.length-1]^=1;assert.throws(()=>recoveryKitBuilder.parseKit(changed));});
test('unknown Kit version is rejected',async()=>{const {bytes}=await kit();const changed=new Uint8Array(bytes);changed[7]=9;assert.throws(()=>recoveryKitBuilder.parseKit(changed),/Unsupported/);});
test('malicious Kit length is rejected before parsing',async()=>{const {bytes}=await kit();const changed=new Uint8Array(bytes);new DataView(changed.buffer).setUint32(8,0xffffffff,false);assert.throws(()=>recoveryKitBuilder.parseKit(changed),/length mismatch/);});
test('unknown Kit fields are rejected',async()=>{const {bytes}=await kit();const parsed=recoveryKitBuilder.parseKit(bytes);parsed.extra='bad';assert.throws(()=>recoveryKitBuilder.validateKit(parsed),/Unknown Kit field/);});
