import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { parseClaimJsonl,resolvePlatformKnowledge,selectFactorQuestions,permittedRecoveryPaths } from '../../src/knowledge/recovery-activation-resolver.js';
import { evaluateActivationRules } from '../../src/review/activation-rules.js';
import { createRecoveryDraftV2,saveModuleEntries,saveRecoveryDrill } from '../../src/ui/recovery-dashboard-model.js';
import { mapActivatedDraftV2,synchronizeActivationConditions } from '../../src/ui/knowledge-activation-mapper.js';
import { createVaultArtifacts,recoverVaultArtifacts } from '../../src/ui/vault-pipeline.js';

const root=new URL('../../',import.meta.url),json=async path=>JSON.parse(await readFile(new URL(path,root),'utf8'));
const activation=await json('config/recovery-map/v2/activation-phase1-zh-CN.json'),presentation=await json('config/recovery-map/v2/presentation-zh-CN.json'),moduleConfig=await json('config/recovery-map/v2/modules.json');
const claims=(await Promise.all(['Binance','OKX','Coinbase'].map(async platform=>parseClaimJsonl(await readFile(new URL(`knowledge/recovery/v2/platforms/${platform}/14-claims/claims.jsonl`,root),'utf8'))))).flat();
const account=(platform,region='Australia',extra={})=>({client_id:`asset-${platform}`,type:'中心化交易所/托管平台',label:`${platform} Account A`,exists:true,platform,registration_geography:region,account_class:'Personal',client_mode:'App',enabled_factors:['email','password','authenticator'],selected_path:'A_HOLDER_RECOVERY',...extra});
function draftFor(asset){let draft=createRecoveryDraftV2();draft=saveModuleEntries(draft,'assets-accounts',[asset]);draft=saveModuleEntries(draft,'locations-finding',[{client_id:'location-main',label:'安全位置',type:'物理位置',finding_instructions:'脱敏位置线索'}]);draft=saveModuleEntries(draft,'contacts-assistance',[{client_id:'contact-choice',needed:false}]);draft=saveModuleEntries(draft,'recovery-order-exceptions',[{client_id:'step-main',risk_level:'low',action:'本人打开官方入口',completion_check:'账户标识一致'}]);return synchronizeActivationConditions(draft,activation);}
function complete(draft){draft.modules['recovery-conditions'].entries.forEach(item=>Object.assign(item,{selected_conditions:['email','phone','password'],saved:true}));draft=synchronizeActivationConditions(draft,activation);draft.modules['locations-finding'].entries.forEach((item,index)=>Object.assign(item,{type:'物理位置',label:`脱敏位置 ${index+1}`,finding_instructions:'仅记录查找线索'}));draft.modules['recovery-order-exceptions'].entries.forEach(item=>Object.assign(item,{action:'本人通过官方入口恢复并核对账户',completion_check:'账户标识一致',risk_notes:'',saved:true}));return draft;}

test('three Phase 1 platforms generate factor questions without exposing internal-only claims',()=>{for(const platform of ['binance','okx','coinbase']){const value=selectFactorQuestions(account(platform,platform==='okx'?'United States':platform==='coinbase'?'EEA':'Australia'),activation,claims,{now:'2026-08-02'});assert.equal(value.questions.length,3);assert.ok(value.questions.every(question=>!question.claim_refs.includes('CBP-049')));}});
test('region resolver matches OKX US exactly and never reuses it for Australia',()=>{assert.equal(resolvePlatformKnowledge(account('okx','United States'),claims,{now:'2026-08-02'}).quality,'EXACT');const au=resolvePlatformKnowledge(account('okx','Australia'),claims,{now:'2026-08-02'});assert.equal(au.quality,'UNRESOLVED');assert.equal(au.claims.length,0);assert.equal(au.conservative,true);});
test('no unsafe global fallback exists for Binance or Coinbase Australia',()=>{for(const platform of ['binance','coinbase'])assert.equal(resolvePlatformKnowledge(account(platform,'Australia'),claims,{now:'2026-08-02'}).quality,'UNRESOLVED');});
test('Reviewed Draft Stale and Internal Only claims cannot drive deterministic questions',()=>{const unsafe=claims.filter(item=>['REVIEWED','DRAFT','STALE'].includes(item.lifecycle_status)||item.product_uses?.includes('INTERNAL_ONLY')).map(item=>item.knowledge_id),selected=resolvePlatformKnowledge(account('coinbase','EEA'),claims,{now:'2026-08-02'}).claims.map(item=>item.knowledge_id);assert.equal(selected.some(id=>unsafe.includes(id)),false);});
test('conditions are summarized once and remain linked to their exact asset',()=>{const a=account('binance'),b=account('coinbase');let draft=createRecoveryDraftV2();draft=saveModuleEntries(draft,'assets-accounts',[a,b]);draft=synchronizeActivationConditions(draft,activation);assert.equal(draft.modules['recovery-conditions'].entries.length,2);assert.equal(draft.modules['recovery-conditions'].entries.filter(item=>item.asset_ref===a.client_id).length,1);assert.equal(new Set(draft.modules['recovery-conditions'].entries.map(item=>item.client_id)).size,2);});
test('activation Review precisely locates condition selection and clears after a Draft fix',()=>{let draft=draftFor(account('okx','United States')),first=evaluateActivationRules(draft,{activationConfig:activation,claims,now:'2026-08-02'});const issue=first.blocking.find(item=>item.code==='CONDITION_SELECTION_REQUIRED');assert.equal(issue.navigation_target.module_id,'recovery-conditions');assert.equal(issue.entity_id,'condition-summary-asset-okx');draft=complete(draft);const second=evaluateActivationRules(draft,{activationConfig:activation,claims,now:'2026-08-02'});assert.equal(second.blocking.some(item=>item.code==='CONDITION_SELECTION_REQUIRED'),false);});
test('unified rules inherit platform account and exact generated location targets',()=>{let draft=draftFor(account('okx','United States'));draft.modules['recovery-conditions'].entries[0].selected_conditions=['email'];draft=synchronizeActivationConditions(draft,activation);const result=mapActivatedDraftV2(draft,{activationConfig:activation,claims,presentation,moduleConfig,now:'2026-08-02T00:00:00.000Z'}),issue=result.review.blocking.find(item=>item.code==='LOCATION_TYPE_REQUIRED');assert.equal(issue.platform_label,'OKX');assert.match(issue.asset_label,/OKX/);assert.equal(issue.navigation_target.module_id,'locations-finding');assert.equal(issue.navigation_target.field_id,'type');});
test('three product paths are personal-only and legal path never becomes takeover instructions',()=>{assert.deepEqual(permittedRecoveryPaths(account('binance')),['A_HOLDER_RECOVERY','B_OWNER_DIRECTED_EXIT','C_OFFICIAL_LEGAL_ESCALATION']);assert.deepEqual(permittedRecoveryPaths(account('binance','Australia',{account_class:'Institutional'})),['C_OFFICIAL_LEGAL_ESCALATION']);});
test('Drill state maps through existing custom_fields without Schema v2 changes',()=>{let draft=draftFor(account('okx','United States'));draft.modules['recovery-conditions'].entries[0].selected_conditions=['email'];draft=saveRecoveryDrill(draft,{materials_checked:true,holder_login_verified:true,small_transfer_status:'未验证'});const result=mapActivatedDraftV2(draft,{activationConfig:activation,claims,presentation,moduleConfig,now:'2026-08-02T00:00:00.000Z'});assert.ok(result.knowledge.custom_fields.some(item=>item.id==='drill-materials_checked'&&item.value==='true'));assert.equal(result.knowledge.schema_version,2);});
test('activated Recovery Map generates Kit and Archive and independently recovers',async()=>{const draft=complete(draftFor(account('okx','United States'))),mapped=mapActivatedDraftV2(draft,{activationConfig:activation,claims,presentation,moduleConfig,strict:true,now:'2026-08-02T00:00:00.000Z'}),password='River-Lantern-27-Mango',artifacts=await createVaultArtifacts({knowledgeGraph:mapped.knowledge,attachmentPayloads:{},password,wizardConfigVersion:2,vaultId:'activation-vault',snapshotId:'activation-snapshot',createdAt:'2026-08-02T00:00:00.000Z'}),recovered=await recoverVaultArtifacts({kitBytes:artifacts.kitBytes,archiveBytes:artifacts.archiveBytes,password});assert.deepEqual(recovered.snapshot.knowledge_graph,mapped.knowledge);assert.equal(recovered.snapshot.snapshot_schema_version,1);});
test('institutional account and missing safe knowledge fail closed',()=>{const draft=draftFor(account('coinbase','Australia',{account_class:'Institutional'})),review=evaluateActivationRules(draft,{activationConfig:activation,claims,now:'2026-08-02'});assert.ok(review.blocking.some(item=>item.code==='PERSONAL_ACCOUNT_ONLY'));});
test('UI activation config contains no secret value fields and browser source has no persistent Draft storage',async()=>{const configText=JSON.stringify(activation),source=await readFile(new URL('web/app-v2.js',root),'utf8');assert.doesNotMatch(configText,/authenticator_seed|api_secret|otp_value|password_value/i);assert.doesNotMatch(source,/localStorage|sessionStorage|indexedDB/);});
