import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { mapDraftV2ToKnowledge } from '../../src/ui/recovery-map-mapper-v2.js';
import { createRecoveryDraftV2,saveModuleEntries,addCustomModule,updateCustomModule,deleteCustomModule,attachmentCenterRows,associateAttachment } from '../../src/ui/recovery-dashboard-model.js';
import { calculateModuleStatesV2,MODULE_STATES } from '../../src/ui/module-status-v2.js';

const root=new URL('../../',import.meta.url),json=async path=>JSON.parse(await readFile(new URL(path,root),'utf8'));
const configs=async()=>({presentation:await json('config/recovery-map/v2/presentation-zh-CN.json'),moduleConfig:await json('config/recovery-map/v2/modules.json')});
function readyDraft(){let draft=createRecoveryDraftV2({vaultTitle:'中文 Vault 🚀'});draft=saveModuleEntries(draft,'assets-accounts',[{client_id:'asset-main',type:'软件钱包',label:'主要钱包',exists:true}]);draft=saveModuleEntries(draft,'recovery-conditions',[{client_id:'condition-main',type:'Authenticator',exists:true,notes:'设备线索'}]);draft=saveModuleEntries(draft,'locations-finding',[{client_id:'location-main',label:'安全位置',type:'物理位置',finding_instructions:'联系可信家人后查找'}]);draft=saveModuleEntries(draft,'contacts-assistance',[{client_id:'contact-choice',needed:false}]);draft=saveModuleEntries(draft,'recovery-order-exceptions',[{client_id:'step-main',risk_level:'low',action:'核对账户',completion_check:'名称一致'}]);return draft;}

test('Phase C Mapper is the fail-closed Draft to Schema v2 boundary',async()=>{const config=await configs(),draft=readyDraft(),mapped=mapDraftV2ToKnowledge(draft,{...config,strict:true,now:'2026-08-02T00:00:00.000Z'});assert.equal(mapped.knowledge.schema_version,2);assert.equal(mapped.review.valid,true);assert.deepEqual(mapped.knowledge.assets[0].condition_refs,['condition-main']);const broken=structuredClone(draft);broken.modules['assets-accounts'].entries[0].label=[];assert.throws(()=>mapDraftV2ToKnowledge(broken,{...config}),/must be text/);});

test('Dashboard draft saves, restores and protects standard modules',()=>{const original=createRecoveryDraftV2(),saved=saveModuleEntries(original,'assets-accounts',[{client_id:'asset-one',label:'A'}]);assert.equal(original.modules['assets-accounts'].entries.length,0);assert.equal(saved.modules['assets-accounts'].entries[0].label,'A');assert.throws(()=>deleteCustomModule(saved,'assets-accounts'),/标准模块不能删除/);});

test('optional custom module defaults off and supports add rename reorder delete',()=>{let draft=createRecoveryDraftV2();assert.equal(draft.custom_modules.length,0);draft=addCustomModule(draft,{id:'custom-one',name:'其他重要信息'});draft=addCustomModule(draft,{id:'custom-two',name:'第二项'});draft=updateCustomModule(draft,'custom-two',{name:'改名',move:-1});assert.equal(draft.custom_modules[0].name,'改名');draft=deleteCustomModule(draft,'custom-one');assert.equal(draft.modules['custom-one'],undefined);});

test('attachment center supports source and multi-module refs with exact capacity',()=>{const policy={limits:{max_version_bytes:100,max_attachments:20}},items=[{id:'attachment-one',display_name:'说明.png',byte_length:40,source_module_id:'assets-accounts',module_refs:['assets-accounts'],purpose:'位置'}],labels={'assets-accounts':'资产','locations-finding':'位置'},associated=associateAttachment(items,'attachment-one',['assets-accounts','locations-finding'],Object.keys(labels)),center=attachmentCenterRows(associated,labels,policy);assert.equal(center.rows[0].source_module,'资产');assert.equal(center.rows[0].association_count,2);assert.equal(center.used_bytes,40);assert.equal(center.remaining_bytes,60);});

test('module states switch without percentages and unified rules drive counts',async()=>{const config=await configs(),mapped=mapDraftV2ToKnowledge(readyDraft(),{...config,now:'2026-08-02T00:00:00.000Z'}),normal=calculateModuleStatesV2(mapped.knowledge),verified=calculateModuleStatesV2(mapped.knowledge,{rehearsalCompleted:true});assert.equal(normal.modules['assets-accounts'].state,MODULE_STATES.COMPLETED);assert.equal(verified.modules['assets-accounts'].state,MODULE_STATES.VERIFIED);assert.equal('percentage' in normal,false);});

test('presentation has six targeted Guidance blocks and UI starts with Dashboard through Mapper',async()=>{const presentation=await json('config/recovery-map/v2/presentation-zh-CN.json'),source=await readFile(new URL('web/app-v2.js',root),'utf8'),html=await readFile(new URL('web/index.html',root),'utf8');assert.equal(presentation.modules.length,6);for(const module of presentation.modules)assert.deepEqual(Object.keys(module.guidance),['why','what','avoid','omissions','attachments','unsure']);assert.match(html,/app-v2\.js/);assert.match(source,/mapActivatedDraftV2/);assert.doesNotMatch(source,/schema_version\s*:\s*2/);assert.match(source,/dashboard\(\);\s*$/);assert.doesNotMatch(source,/localStorage|sessionStorage|indexedDB/);});

test('Phase C UX exposes Recovery Graph, Version Card and attachment relationships',async()=>{const source=await readFile(new URL('web/app-v2.js',root),'utf8');for(const label of ['Recovery Map Graph','资产','恢复条件','位置','协助人','恢复步骤','附件','嘱托','Version Card','Current Version','Draft','Verified','Recovery Status','来源模块','用途','关联模块'])assert.match(source,new RegExp(label));assert.match(source,/data-open/);assert.match(source,/source_modules/);});

test('Schema v2 frozen source remains byte-identical in Phase C',async()=>{const bytes=await readFile(new URL('src/knowledge/schema-v2.js',root)),hash=createHash('sha256').update(bytes).digest('hex');assert.equal(hash,'1adf680ef61789d0ca9ef832506c6494089b155eb84b5498733a1ca30e239566');});
