import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createRecoveryDraftV2, saveModuleEntries, attachmentCenterRows } from '../../src/ui/recovery-dashboard-model.js';
import { synchronizeActivationConditions, accountDisplayName } from '../../src/ui/knowledge-activation-mapper.js';
import { evaluateActivationRules } from '../../src/review/activation-rules.js';

const root=new URL('../../',import.meta.url);
const activation=JSON.parse(await readFile(new URL('config/recovery-map/v2/activation-phase1-zh-CN.json',root),'utf8'));
const presentation=JSON.parse(await readFile(new URL('config/recovery-map/v2/presentation-zh-CN.json',root),'utf8'));
const source=await readFile(new URL('web/app-v2.js',root),'utf8');
const asset=(id='asset-binance',extra={})=>({client_id:id,platform:'binance',registration_geography:'Australia',account_class:'Personal',nickname:'主账户',...extra});
const synchronized=(assets=[asset()])=>{let draft=createRecoveryDraftV2();draft=saveModuleEntries(draft,'assets-accounts',assets);return synchronizeActivationConditions(draft,activation);};

test('V01 first module exposes only the approved account fields and platform defaults blank',()=>{const fields=presentation.modules.find(item=>item.id==='assets-accounts').fields.filter(item=>!item.hidden).map(item=>item.id);assert.deepEqual(fields,['platform','registration_geography','account_class','nickname']);assert.match(source,/<option value="">请选择<\/option>/);});
test('selecting a CEX does not silently choose personal or institutional account type',()=>{const draft=synchronized([asset('asset-new',{account_class:undefined})]);assert.equal(draft.modules['assets-accounts'].entries[0].account_class,'');});
test('custom platform gets one account summary without CEX region requirements',()=>{const draft=synchronized([asset('asset-custom',{platform:'custom',registration_geography:'',account_class:''})]);assert.equal(draft.modules['recovery-conditions'].entries.length,1);assert.deepEqual(draft.modules['recovery-conditions'].entries[0].selected_conditions,[]);const review=evaluateActivationRules(draft,{activationConfig:activation,claims:[]});assert.equal(review.blocking.some(item=>['ACCOUNT_REGION_REQUIRED','ACCOUNT_CLASS_REQUIRED'].includes(item.code)),false);});
test('duplicate platform accounts require nicknames and display distinct account labels',()=>{const assets=[asset('asset-one',{nickname:''}),asset('asset-two',{nickname:''})],draft=synchronized(assets),review=evaluateActivationRules(draft,{activationConfig:activation,claims:[]});assert.equal(review.blocking.filter(item=>item.code==='ACCOUNT_NICKNAME_REQUIRED').length,2);assert.notEqual(accountDisplayName(assets[0],assets,activation),accountDisplayName(assets[1],assets,activation));});
test('configured recovery conditions are choices on one summary linked to its account',()=>{const draft=synchronized(),summary=draft.modules['recovery-conditions'].entries[0];assert.equal(summary.asset_ref,'asset-binance');assert.deepEqual(summary.selected_conditions,[]);assert.ok(activation.platform_condition_templates.binance.includes('email'));});
test('selected conditions generate exact locations and deselection removes them safely',()=>{let draft=synchronized(),summary=draft.modules['recovery-conditions'].entries[0];summary.selected_conditions=['email'];draft=synchronizeActivationConditions(draft,activation);assert.equal(draft.modules['locations-finding'].entries.length,1);summary=draft.modules['recovery-conditions'].entries[0];summary.selected_conditions=[];draft=synchronizeActivationConditions(draft,activation);assert.equal(draft.modules['locations-finding'].entries.length,0);});
test('temporary summary states remain in Draft but block final Review with exact condition',()=>{for(const [field,state] of [['unknown_conditions','UNKNOWN'],['later_conditions','LATER']]){const draft=synchronized();draft.modules['recovery-conditions'].entries[0][field]=['email'];const issue=evaluateActivationRules(draft,{activationConfig:activation,claims:[]}).blocking.find(item=>item.code==='CONDITION_NOT_READY');assert.equal(issue.condition_label,'注册邮箱');assert.equal(issue.temporary_state,state);assert.equal(issue.navigation_target.field_id,'selected_conditions');}});
test('location accepts a valid scoped attachment instead of text but rejects unrelated attachment',()=>{let draft=synchronized();draft.modules['recovery-conditions'].entries[0].selected_conditions=['email'];draft=synchronizeActivationConditions(draft,activation);const location=draft.modules['locations-finding'].entries[0];Object.assign(location,{type:'设备',label:'备用设备'});draft.modules['recovery-order-exceptions'].entries[0]={...draft.modules['recovery-order-exceptions'].entries[0],action:'本人操作',saved:true};const file={id:'file-one',display_name:'guide.txt',byte_length:1,bytes:new Uint8Array([1]),sha256:'a'.repeat(64),media_type:'text/plain',module_refs:['locations-finding'],owner_entity_refs:[location.client_id],account_id:'asset-binance',field_id:'finding_instructions',purpose_id:'location-guide',source_module_id:'locations-finding'};assert.equal(evaluateActivationRules(draft,{activationConfig:activation,claims:[],attachments:[file]}).blocking.some(item=>item.code==='LOCATION_CONTENT_REQUIRED'),false);assert.equal(evaluateActivationRules(draft,{activationConfig:activation,claims:[],attachments:[{...file,owner_entity_refs:['other']}]}).blocking.some(item=>item.code==='LOCATION_CONTENT_REQUIRED'),true);});
test('per-platform step requires content and object save but risk text is optional',()=>{const draft=synchronized(),review=evaluateActivationRules(draft,{activationConfig:activation,claims:[]});for(const code of ['STEP_CONTENT_REQUIRED','PLATFORM_SAVE_REQUIRED'])assert.ok(review.blocking.some(item=>item.code===code));assert.equal(review.blocking.some(item=>item.code==='STEP_RISK_REQUIRED'),false);});
test('attachments retain platform account field purpose and multi-module map metadata',()=>{const items=[{id:'one',display_name:'说明.png',byte_length:9,platform_id:'binance',account_id:'asset-binance',field_id:'finding_instructions',purpose_id:'location-guide',source_module_id:'locations-finding',module_refs:['locations-finding','recovery-conditions'],purpose:'位置说明'}],center=attachmentCenterRows(items,{'locations-finding':'位置','recovery-conditions':'条件'},{limits:{max_version_bytes:50,max_attachments:20}});assert.equal(center.rows[0].association_count,2);assert.equal(center.rows[0].field_id,'finding_instructions');assert.equal(center.rows[0].account_id,'asset-binance');});
test('module one explicitly supports attachment scope for one account or all accounts',()=>{assert.match(source,/data-account-scope-for/);assert.match(source,/ALL_ACCOUNTS/);assert.match(source,/ownerRefs=allAccounts\?draft\.modules\['assets-accounts'\]\.entries\.map/);});
test('UI synchronizes the active Draft before upload, add-entry, rerender and module return',()=>{assert.match(source,/async function addFiles\(event\)\{try\{if\(!syncCurrentDraftFromDom\(\)\)return/);assert.match(source,/add\.onclick=\(\)=>\{if\(!syncCurrentDraftFromDom\(\)\)return/);assert.match(source,/cancel.*syncCurrentDraftFromDom/s);assert.match(source,/bindImmediateDraft/);});
test('Review returns to the exact module entity and field and modifications invalidate review',()=>{assert.match(source,/renderModule\(button\.dataset\.fix,\{focusEntity:button\.dataset\.entity,focusField:button\.dataset\.field\}\)/);assert.match(source,/const changed=\(\)=>\{draftRevision\+\+;reviewRevision=-1;artifacts=null;/);});
test('V01 UI contains no removed first-step choices or persistent secret storage',()=>{const visible=JSON.stringify(presentation.modules.find(item=>item.id==='assets-accounts').fields.filter(item=>!item.hidden));assert.doesNotMatch(visible,/client_mode|enabled_factors|selected_path/);assert.doesNotMatch(source,/localStorage|sessionStorage|indexedDB/);});
