import { knowledgeSchemaV2, STANDARD_MODULE_IDS, V2_COLLECTIONS } from './schema-v2.js';
import { normalizeMimeType } from '../shared/mime-type.js';

const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{2,127}$/,SHA=/^[a-f0-9]{64}$/,RISK=new Set(['low','medium','high','critical']);
const REQUIRED={standard_modules:['id','order'],custom_modules:['id','name','order','enabled'],assets:['id','type','label','exists'],recovery_conditions:['id','type','exists','asset_refs'],fallback_paths:['id','condition_ref','scenario','action'],locations:['id','label','type','finding_instructions'],contacts:['id','label','role','when_to_contact','assistance_boundary'],recovery_steps:['id','sequence','risk_level','action','completion_check'],warnings:['id','risk_level','instruction'],attachments:['id','display_name','media_type','byte_length','sha256','module_refs','owner_entity_refs','purpose','sensitive_acknowledged'],custom_fields:['id','module_ref','label','field_type','value']};
const REF_TARGETS={condition_refs:'recovery_conditions',location_refs:'locations',contact_refs:'contacts',step_refs:'recovery_steps',attachment_refs:'attachments',custom_field_refs:'custom_fields',asset_refs:'assets',fallback_path_refs:'fallback_paths',warning_refs:'warnings',alternate_contact_ref:'contacts',condition_ref:'recovery_conditions'};
const issue=(issues,path,code,message,module_id=null,field_id=null)=>issues.push({path,code,message,module_id,field_id,blocking:true});
const text=value=>typeof value==='string'&&value.trim().length>0&&[...value].length<=10000;
const refs=value=>Array.isArray(value)&&value.every(item=>typeof item==='string');
const list=value=>Array.isArray(value)?value:[];

export function validateKnowledgeMapV2(input){
  const issues=[];
  if(!input||typeof input!=='object'||Array.isArray(input))return{valid:false,issues:[{path:'$',code:'TYPE',message:'Knowledge Map必须是对象',blocking:true}]};
  const allowedRoot=new Set(knowledgeSchemaV2.root_fields);for(const key of Object.keys(input))if(!allowedRoot.has(key))issue(issues,`$.${key}`,'UNKNOWN_FIELD','存在未知根字段');
  if(input.schema_version!==2)issue(issues,'$.schema_version','UNSUPPORTED_VERSION','Knowledge Schema版本必须为2');
  if(!text(input.vault_title))issue(issues,'$.vault_title','REQUIRED','恢复计划名称为必填项');
  if(!text(input.plan_type))issue(issues,'$.plan_type','REQUIRED','恢复计划类型为必填项');
  if(!Number.isFinite(Date.parse(input.reviewed_at)))issue(issues,'$.reviewed_at','FORMAT','复核日期格式不正确');
  const ids=new Map();
  for(const collection of V2_COLLECTIONS){const values=input[collection];if(!Array.isArray(values)){issue(issues,`$.${collection}`,'TYPE',`${collection}必须是数组`);continue;}if(values.length>10000)issue(issues,`$.${collection}`,'LIMIT',`${collection}数量超限`);values.forEach((entity,index)=>{const path=`$.${collection}[${index}]`,moduleId=collection==='standard_modules'||collection==='custom_modules'?entity?.id:null;if(!entity||typeof entity!=='object'||Array.isArray(entity)){issue(issues,path,'TYPE','条目必须是对象',moduleId);return;}const allowed=new Set(knowledgeSchemaV2.collections[collection]);for(const key of Object.keys(entity))if(!allowed.has(key))issue(issues,`${path}.${key}`,'UNKNOWN_FIELD','条目包含未知字段',moduleId,key);for(const field of REQUIRED[collection])if(!(field in entity)||entity[field]===null||entity[field]==='')issue(issues,`${path}.${field}`,'REQUIRED','必填字段缺失',moduleId,field);if(!ID.test(entity.id??''))issue(issues,`${path}.id`,'INVALID_ID','条目标识格式不正确',moduleId,'id');else if(ids.has(entity.id))issue(issues,`${path}.id`,'DUPLICATE_ID','条目标识重复',moduleId,'id');else ids.set(entity.id,{collection,path});for(const[key,value]of Object.entries(entity))if(key.endsWith('_refs')||['asset_refs','owner_entity_refs','module_refs','applies_to_refs'].includes(key))if(!refs(value))issue(issues,`${path}.${key}`,'TYPE','引用字段必须是字符串数组',moduleId,key);});}
  const standard=list(input.standard_modules),customModules=list(input.custom_modules),standardIds=standard.map(item=>item?.id);for(const id of STANDARD_MODULE_IDS)if(!standardIds.includes(id))issue(issues,'$.standard_modules','STANDARD_MODULE_MISSING',`缺少标准模块：${id}`,id);if(new Set(standardIds).size!==standardIds.length)issue(issues,'$.standard_modules','DUPLICATE_MODULE','标准模块不得重复');for(const item of standard)if(!STANDARD_MODULE_IDS.includes(item?.id))issue(issues,'$.standard_modules','STANDARD_MODULE_INVALID','标准模块集合包含非标准ID',item?.id);
  for(const module of standard)if(!Number.isInteger(module?.order))issue(issues,'$.standard_modules.order','TYPE','标准模块顺序必须是整数',module?.id,'order');
  for(const custom of customModules){if(STANDARD_MODULE_IDS.includes(custom?.id))issue(issues,'$.custom_modules','STANDARD_MODULE_OVERRIDE','自定义模块不得替换标准模块',custom?.id);if(!text(custom?.name))issue(issues,'$.custom_modules.name','TYPE','自定义模块名称必须是文字',custom?.id,'name');if(!Number.isInteger(custom?.order))issue(issues,'$.custom_modules.order','TYPE','自定义模块顺序必须是整数',custom?.id,'order');if(typeof custom?.enabled!=='boolean')issue(issues,'$.custom_modules','TYPE','自定义模块enabled必须是布尔值',custom?.id,'enabled');}
  const allModuleIds=new Set([...STANDARD_MODULE_IDS,...customModules.map(item=>item?.id)]);
  for(const collection of V2_COLLECTIONS)for(const[index,entity]of(Array.isArray(input[collection])?input[collection]:[]).entries()){if(!entity||typeof entity!=='object')continue;const path=`$.${collection}[${index}]`;for(const[field,targetCollection]of Object.entries(REF_TARGETS)){if(!(field in entity))continue;const values=field.endsWith('_ref')?[entity[field]]:entity[field];if(!Array.isArray(values))continue;for(const ref of values){if(!ref)continue;const target=ids.get(ref);if(!target)issue(issues,`${path}.${field}`,'MISSING_REFERENCE',`引用不存在：${ref}`,null,field);else if(target.collection!==targetCollection)issue(issues,`${path}.${field}`,'WRONG_REFERENCE_TYPE',`引用类型应为${targetCollection}`,null,field);}}for(const ref of entity.module_refs??[])if(!allModuleIds.has(ref))issue(issues,`${path}.module_refs`,'MISSING_REFERENCE',`模块引用不存在：${ref}`,ref,'module_refs');for(const ref of entity.owner_entity_refs??[])if(!ids.has(ref))issue(issues,`${path}.owner_entity_refs`,'MISSING_REFERENCE',`实体引用不存在：${ref}`,null,'owner_entity_refs');for(const ref of entity.applies_to_refs??[])if(!ids.has(ref))issue(issues,`${path}.applies_to_refs`,'MISSING_REFERENCE',`实体引用不存在：${ref}`,null,'applies_to_refs');if('module_ref'in entity&&!allModuleIds.has(entity.module_ref))issue(issues,`${path}.module_ref`,'MISSING_REFERENCE',`模块引用不存在：${entity.module_ref}`,entity.module_ref,'module_ref');}
  if(!input.assistance||typeof input.assistance!=='object'||Array.isArray(input.assistance)||typeof input.assistance.needed!=='boolean')issue(issues,'$.assistance','TYPE','必须明确是否需要协助','contacts-assistance','needed');
  if(input.personal_message!==null&&input.personal_message!==undefined){const value=input.personal_message;if(!value||typeof value!=='object'||Array.isArray(value))issue(issues,'$.personal_message','TYPE','个人留言必须是对象或null','evidence-messages');else{for(const key of Object.keys(value))if(!['text','attachment_refs','disclaimer_acknowledged'].includes(key))issue(issues,`$.personal_message.${key}`,'UNKNOWN_FIELD','个人留言包含未知字段','evidence-messages',key);if('text'in value&&typeof value.text!=='string')issue(issues,'$.personal_message.text','TYPE','个人留言文字格式不正确','evidence-messages','text');if(!refs(value.attachment_refs??[]))issue(issues,'$.personal_message.attachment_refs','TYPE','个人留言附件引用必须是数组','evidence-messages','attachment_refs');else for(const ref of value.attachment_refs??[])if(ids.get(ref)?.collection!=='attachments')issue(issues,'$.personal_message.attachment_refs','MISSING_REFERENCE',`个人留言附件不存在：${ref}`,'evidence-messages','attachment_refs');if('disclaimer_acknowledged'in value&&typeof value.disclaimer_acknowledged!=='boolean')issue(issues,'$.personal_message.disclaimer_acknowledged','TYPE','免责声明确认必须是布尔值','evidence-messages','disclaimer_acknowledged');}}
  for(const asset of list(input.assets))if(typeof asset?.exists!=='boolean')issue(issues,'$.assets.exists','TYPE','资产存在性必须是布尔值','assets-accounts','exists');
  for(const condition of list(input.recovery_conditions))if(typeof condition?.exists!=='boolean')issue(issues,'$.recovery_conditions.exists','TYPE','恢复条件存在性必须是布尔值','recovery-conditions','exists');
  for(const step of list(input.recovery_steps)){if(!Number.isInteger(step?.sequence)||step.sequence<1)issue(issues,'$.recovery_steps.sequence','RANGE','步骤顺序必须为正整数','recovery-order-exceptions','sequence');if(!RISK.has(step?.risk_level))issue(issues,'$.recovery_steps.risk_level','ENUM','风险等级不正确','recovery-order-exceptions','risk_level');}
  for(const attachment of list(input.attachments)){if(!Number.isSafeInteger(attachment?.byte_length)||attachment.byte_length<0||attachment.byte_length>1024**3)issue(issues,'$.attachments.byte_length','RANGE','附件长度不正确','evidence-messages','byte_length');if(!SHA.test(attachment?.sha256??''))issue(issues,'$.attachments.sha256','FORMAT','附件SHA-256不正确','evidence-messages','sha256');if(typeof attachment?.sensitive_acknowledged!=='boolean')issue(issues,'$.attachments.sensitive_acknowledged','TYPE','附件敏感信息确认必须是布尔值','evidence-messages','sensitive_acknowledged');try{if(normalizeMimeType(attachment.media_type)!==attachment.media_type)issue(issues,'$.attachments.media_type','FORMAT','附件MIME不规范','evidence-messages','media_type');}catch{issue(issues,'$.attachments.media_type','FORMAT','附件MIME不正确','evidence-messages','media_type');}}
  return{valid:issues.length===0,issues};
}
