import {validateRecoveryPassword} from '../../src/ui/password-policy.js';
import {assertCustomerMp4,createMp4PilotArtifacts,quoteProjection} from './pilot-core.js';

const NETWORK='Arweave Mainnet',MAX_OVERHEAD_BYTES=4096,state={file:null,video:null,artifacts:null,evidence:null,previewUrl:null};
const $=selector=>document.querySelector(selector),elapsed=start=>Number((performance.now()-start).toFixed(1)),status=message=>{$('#status').textContent=message;};
const policyPromise=fetch('../../config/security/recovery-password-v1.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('密码安全策略无法读取。');return response.json();});
function size(bytes){return bytes<1024*1024?`${(bytes/1024).toFixed(2)} KB`:`${(bytes/(1024*1024)).toFixed(2)} MB`;}
function download(bytes,filename){let url;try{url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'}));const link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{if(url)URL.revokeObjectURL(url);throw new Error('下载未能启动，请允许浏览器下载后重试。');}}
async function videoMetadata(file){if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);state.previewUrl=URL.createObjectURL(file);const video=$('#preview');video.src=state.previewUrl;await new Promise((resolve,reject)=>{video.onloadedmetadata=resolve;video.onerror=()=>reject(new Error('浏览器无法读取该 MP4。'));});return{duration_seconds:Number(video.duration.toFixed(3)),resolution:`${video.videoWidth}×${video.videoHeight}`};}
async function selectFile(){const file=$('#mp4').files[0];if(!file){state.file=null;return;}const header=new Uint8Array(await file.slice(0,16).arrayBuffer());assertCustomerMp4(file,header);const metadata=await videoMetadata(file);state.file=file;state.video=metadata;$('#file-summary').textContent=`${file.name} · ${size(file.size)} · ${metadata.duration_seconds} 秒 · ${metadata.resolution}`;$('#file-summary').hidden=false;status('MP4 已就绪。请设置全新测试恢复密码。');}
async function encrypt(){if(!state.file)throw new Error('请先选择 MP4。');let password=$('#password').value,confirmation=$('#confirmation').value;const policy=await policyPromise,result=validateRecoveryPassword(password,confirmation,$('#ack').checked,{policy,vaultName:state.file.name});if(!result.valid)throw new Error(result.issues[0].message);const readStart=performance.now(),bytes=new Uint8Array(await state.file.arrayBuffer()),readMs=elapsed(readStart);try{const artifacts=await createMp4PilotArtifacts({bytes,filename:state.file.name,mimeType:state.file.type,password});if(artifacts.overheadBytes>MAX_OVERHEAD_BYTES)throw new Error('Archive 封装开销异常，已停止报价。');state.artifacts=artifacts;state.evidence={status:'LOCAL_ENCRYPTION_PASS',network:NETWORK,broadcasts:0,cost_ar:0,file:{name:state.file.name,mime:state.file.type,size_bytes:state.file.size,duration_seconds:state.video.duration_seconds,resolution:state.video.resolution,sha256:artifacts.originalSha256},archive:{size_bytes:artifacts.archiveBytes.length,sha256:artifacts.archiveSha256,overhead_bytes:artifacts.overheadBytes,overhead_percent:Number(artifacts.overheadPercent.toFixed(6))},timings_ms:{file_read:readMs,...artifacts.timings},quote:null};$('#encryption-result').textContent=`加密完成：原文件 ${size(state.file.size)}；Archive ${size(artifacts.archiveBytes.length)}；增量 ${artifacts.overheadPercent.toFixed(4)}%`;$('#encryption-result').hidden=false;$('#download-kit').disabled=false;$('#download-archive').disabled=false;$('#quote').disabled=false;render();status('本地加密完成。请下载 Recovery Kit 和本地 Archive，然后查看报价。');}finally{password='';confirmation='';$('#password').value='';$('#confirmation').value='';}}
async function quote(){if(!state.artifacts||!state.evidence)throw new Error('请先完成本地加密。');if(!globalThis.arweaveWallet)throw new Error('未检测到已登录并解锁的 ArConnect/Wander。');const permissions=await arweaveWallet.getPermissions().catch(()=>[]);if(!permissions.includes('ACCESS_ADDRESS'))await arweaveWallet.connect(['ACCESS_ADDRESS'],{name:'CJAS MP4 Mainnet Pilot'});const address=await arweaveWallet.getActiveAddress();if(!address)throw new Error('无法读取当前测试钱包公开地址。');const started=performance.now(),[price,balance]=await Promise.all([fetch(`https://arweave.net/price/${state.artifacts.archiveBytes.length}`,{cache:'no-store'}),fetch(`https://arweave.net/wallet/${address}/balance`,{cache:'no-store'})]);const requestMs=elapsed(started);if(!price.ok||!balance.ok)throw new Error(`Mainnet 报价读取失败：${price.status}/${balance.status}`);const quoteAR=Number(await price.text())/1e12,balanceAR=Number(await balance.text())/1e12,projection=quoteProjection({quoteAR,archiveBytes:state.artifacts.archiveBytes.length,balanceAR});state.evidence.quote={request_ms:requestMs,wallet_public_address:address,wallet_balance_ar:balanceAR,...projection};state.evidence.status='WAITING_FOR_BROADCAST_AUTHORIZATION';render();$('#quote-result').textContent=`Archive ${size(state.artifacts.archiveBytes.length)} · 报价 ${quoteAR.toFixed(12)} AR · 每 MiB ${projection.ar_per_mib.toFixed(12)} AR · 钱包余额 ${balanceAR.toFixed(12)} AR · 预计余额 ${projection.projected_balance_ar.toFixed(12)} AR · 50 MiB 推算 ${projection.estimated_50_mib_ar.toFixed(12)} AR`;$('#quote-result').hidden=false;status('报价完成。已停止，等待 CEO 单次广播授权。');}
function render(){$('#evidence').textContent=JSON.stringify(state.evidence??{status:'NOT_STARTED',broadcasts:0,cost_ar:0},null,2);}
async function run(action){try{status('处理中……');await action();}catch(error){status(error.message);}}
$('#mp4').onchange=()=>run(selectFile);$('#encrypt').onclick=()=>run(encrypt);$('#download-kit').onclick=()=>run(()=>download(state.artifacts.kitBytes,'CJAS-MP4-Mainnet-Pilot.cjas'));$('#download-archive').onclick=()=>run(()=>download(state.artifacts.archiveBytes,'CJAS-MP4-Mainnet-Pilot.cjasmp4archive'));$('#quote').onclick=()=>run(quote);addEventListener('beforeunload',()=>{if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);});render();
