import {cryptoEngine} from '../../src/crypto/crypto-engine.js';
import {decodeMp4Archive} from './mp4-archive.js';

const NETWORK='Arweave Mainnet',MAX_FEE_AR=0.11,GATEWAY='https://arweave.net',state={arweave:null,archive:null,record:null,broadcastAttempted:false,evidenceDownloaded:false};
const $=selector=>document.querySelector(selector),elapsed=start=>Number((performance.now()-start).toFixed(1)),now=()=>new Date().toISOString(),status=message=>{$('#status').textContent=message;};
const size=bytes=>`${(bytes/(1024*1024)).toFixed(2)} MiB`;
function downloadEvidence(){if(!state.record?.txid)throw new Error('尚未生成 Mainnet Evidence。');let url;try{url=URL.createObjectURL(new Blob([JSON.stringify(state.record,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`cjas-mp4-mainnet-evidence-${Date.now()}.json`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);state.evidenceDownloaded=true;}catch{if(url)URL.revokeObjectURL(url);throw new Error('Mainnet Evidence 下载未能启动。');}}
async function loadSdk(){if(!globalThis.Arweave){const script=document.createElement('script');script.src='https://unpkg.com/arweave@1.14.4/bundles/web.bundle.min.js';document.head.appendChild(script);await new Promise((resolve,reject)=>{script.onload=resolve;script.onerror=()=>reject(new Error('Arweave SDK 加载失败。'));});}state.arweave=Arweave.init({host:'arweave.net',port:443,protocol:'https',timeout:30000});}
async function importArchive(){const file=$('#archive').files[0];if(!file)throw new Error('请选择当前 MP4 Archive。');const bytes=new Uint8Array(await file.arrayBuffer()),parsed=decodeMp4Archive(bytes),sha256=await cryptoEngine.hashHex(bytes),originalMp4Sha256=Array.from(parsed.originalSha256Bytes,b=>b.toString(16).padStart(2,'0')).join('');state.archive=bytes;state.record={status:'ARCHIVE_READY',network:NETWORK,archive_filename:file.name,source_mp4_filename:parsed.filename,source_mp4_size:parsed.originalSize,original_mp4_sha256:originalMp4Sha256,archive_size:bytes.length,archive_sha256:sha256,max_authorized_fee_ar:MAX_FEE_AR,wallet_public_address:null,balance_before_ar:null,quote_ar:null,actual_fee_ar:null,signature_wait_ms:null,broadcast_to_txid_ms:null,total_upload_ms:null,txid:null,broadcasted_at:null,first_downloadable_at:null,first_downloadable_ms:null,balance_after_ar:null,broadcasts:0,cost_ar:0};$('#archive-result').textContent=`${file.name} · ${size(bytes.length)} · SHA-256 ${sha256}`;$('#archive-result').hidden=false;$('#quote').disabled=false;render();status('Archive 已通过内部结构校验。请复核钱包与费用。');}
async function quote(){if(!state.archive)throw new Error('请先导入当前 Archive。');await loadSdk();if(!globalThis.arweaveWallet)throw new Error('未检测到已登录并解锁的 ArConnect/Wander。');const permissions=await arweaveWallet.getPermissions().catch(()=>[]);if(!permissions.includes('ACCESS_ADDRESS')||!permissions.includes('SIGN_TRANSACTION'))await arweaveWallet.connect(['ACCESS_ADDRESS','SIGN_TRANSACTION'],{name:'CJAS MP4 Mainnet Pilot'});const address=await arweaveWallet.getActiveAddress();if(!address)throw new Error('无法读取当前测试钱包公开地址。');const [price,balance]=await Promise.all([fetch(`${GATEWAY}/price/${state.archive.length}`,{cache:'no-store'}),fetch(`${GATEWAY}/wallet/${address}/balance`,{cache:'no-store'})]);if(!price.ok||!balance.ok)throw new Error(`Mainnet 查询失败：${price.status}/${balance.status}`);const quoteAR=Number(await price.text())/1e12,balanceAR=Number(await balance.text())/1e12;if(!Number.isFinite(quoteAR)||quoteAR>MAX_FEE_AR)throw new Error(`实时报价 ${quoteAR.toFixed(12)} AR 超过 0.11 AR 授权上限，已停止。`);state.record.wallet_public_address=address;state.record.balance_before_ar=balanceAR;state.record.quote_ar=quoteAR;state.record.projected_balance_ar=balanceAR-quoteAR;state.record.status='AWAITING_CEO_SIGNATURE';$('#quote-result').textContent=`钱包 ${address} · 报价 ${quoteAR.toFixed(12)} AR · 上限 0.11 AR · 当前余额 ${balanceAR.toFixed(12)} AR · 预计余额 ${(balanceAR-quoteAR).toFixed(12)} AR`;$('#quote-result').hidden=false;$('#broadcast').disabled=false;render();status('费用复核通过。点击广播后将出现钱包弹窗，必须由 CEO 本人确认。');}
async function waitForDownloadable(txid,started){for(let attempt=0;attempt<60;attempt++){const response=await fetch(`${GATEWAY}/${txid}`,{cache:'no-store'}).catch(()=>null);if(response?.ok)return{at:now(),ms:elapsed(started),http_status:response.status};await new Promise(resolve=>setTimeout(resolve,5000));}return{at:null,ms:null,http_status:null};}
async function broadcast(){if(state.broadcastAttempted)throw new Error('本会话已经执行过广播尝试，禁止重复。');if(!state.archive||state.record?.status!=='AWAITING_CEO_SIGNATURE')throw new Error('请先完成 Archive 和费用复核。');state.broadcastAttempted=true;$('#broadcast').disabled=true;const totalStart=performance.now(),tx=await state.arweave.createTransaction({data:state.archive});tx.addTag('Content-Type','application/octet-stream');tx.addTag('App-Name','CJAS-AR-MP4-Mainnet-Pilot');tx.addTag('Format','CJAS-MP4-Archive-V1');tx.addTag('Source-Media-Type','video/mp4');const actualFeeAR=Number(tx.reward)/1e12;if(!Number.isFinite(actualFeeAR)||actualFeeAR>MAX_FEE_AR)throw new Error(`交易实际费用 ${actualFeeAR.toFixed(12)} AR 超过 0.11 AR，未请求签名、未广播。`);status('等待 CEO 在钱包弹窗中确认本次唯一签名。');const signStart=performance.now();await state.arweave.transactions.sign(tx);const signatureWaitMs=elapsed(signStart),postStart=performance.now();status('签名完成，正在广播当前 Archive。');const response=await state.arweave.transactions.post(tx),broadcastMs=elapsed(postStart);if(![200,202].includes(response.status))throw new Error(`广播失败：HTTP ${response.status}。禁止自动重试。`);state.record.status='BROADCAST_ACCEPTED';state.record.actual_fee_ar=actualFeeAR;state.record.signature_wait_ms=signatureWaitMs;state.record.broadcast_to_txid_ms=broadcastMs;state.record.total_upload_ms=elapsed(totalStart);state.record.txid=tx.id;state.record.broadcasted_at=now();state.record.broadcasts=1;state.record.cost_ar=actualFeeAR;render();status('广播已接受，正在等待 Mainnet 首次可下载。');const downloadable=await waitForDownloadable(tx.id,performance.now()),balanceResponse=await fetch(`${GATEWAY}/wallet/${state.record.wallet_public_address}/balance`,{cache:'no-store'}),balanceAfter=balanceResponse.ok?Number(await balanceResponse.text())/1e12:null;state.record.first_downloadable_at=downloadable.at;state.record.first_downloadable_ms=downloadable.ms;state.record.first_downloadable_http=downloadable.http_status;state.record.balance_after_ar=balanceAfter;state.record.status=downloadable.at?'MAINNET_DOWNLOADABLE':'BROADCAST_ACCEPTED_PENDING_GATEWAY';render();$('#broadcast-result').textContent=`TxID ${tx.id} · 实际费用 ${actualFeeAR.toFixed(12)} AR · ${downloadable.at?'Mainnet 已可下载':'仍待网关可下载'}`;$('#broadcast-result').hidden=false;$('#download-evidence').disabled=false;downloadEvidence();status('本次唯一广播已完成。Mainnet Evidence 已生成；请保存后停止，等待独立恢复授权。');}
function render(){$('#evidence').textContent=JSON.stringify(state.record??{status:'NOT_STARTED',broadcasts:0,cost_ar:0},null,2);}
async function run(action){try{status('处理中……');await action();}catch(error){status(error.message);}}
$('#archive').onchange=()=>run(importArchive);$('#quote').onclick=()=>run(quote);$('#broadcast').onclick=()=>run(broadcast);$('#download-evidence').onclick=()=>run(downloadEvidence);render();
