import {cryptoEngine} from '../../src/crypto/crypto-engine.js';
import {Pbkdf2Provider} from '../../src/crypto/kdf-provider.js';
import {recoveryKitBuilder} from '../../src/recovery-kit/recovery-kit-builder.js';
import {decodeMp4Archive,mp4ArchiveAad} from './mp4-archive.js';
import {createMp4Delivery} from './recovery-delivery.js';

const NETWORK='Arweave Mainnet',GATEWAY='https://arweave.net',EXPECTED_TXID='wELztFMbhqW-dRU58cfdl_R_lQpVCkK8VLfOQBmGrvw',EXPECTED_ARCHIVE_SIZE=9795318,EXPECTED_ARCHIVE_SHA256='61d395192fb52de0575d121a72667126863ec5f8731cecee6f6386307950c836';
const state={delivery:null,result:null};const $=selector=>document.querySelector(selector),elapsed=start=>Number((performance.now()-start).toFixed(1)),hex=bytes=>Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join(''),status=message=>{$('#status').textContent=message;};
function stage(message){const item=document.createElement('li');item.textContent=message;$('#stages').appendChild(item);}
function size(bytes){return`${bytes.toLocaleString('en-AU')} bytes (${(bytes/(1024*1024)).toFixed(2)} MiB)`;}
function validateEvidence(value){if(!value||value.network!==NETWORK||value.txid!==EXPECTED_TXID||value.archive_size!==EXPECTED_ARCHIVE_SIZE||value.archive_sha256!==EXPECTED_ARCHIVE_SHA256)throw new Error('Mainnet Evidence 与本次 MP4 Pilot 不匹配。');return value;}
async function downloadMainnet(txid){const started=performance.now(),response=await fetch(`${GATEWAY}/${txid}?cjas_recovery=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`Arweave Mainnet 下载失败：HTTP ${response.status}`);return{bytes:new Uint8Array(await response.arrayBuffer()),ms:elapsed(started),status:response.status,url:GATEWAY};}
async function recover(){const evidenceFile=$('#evidence-file').files[0],kitFile=$('#kit-file').files[0];let password=$('#password').value;if(!evidenceFile||!kitFile||!password)throw new Error('请选择 Mainnet Evidence 和 Recovery Kit，并输入恢复密码。');$('#stages').textContent='';$('#success').hidden=true;state.delivery=null;const totalStart=performance.now();try{
  stage('正在读取 Mainnet Evidence');let evidence;try{evidence=validateEvidence(JSON.parse(await evidenceFile.text()));}catch(error){if(error.message.includes('不匹配'))throw error;throw new Error('Mainnet Evidence 无法识别。');}
  stage('正在校验 Recovery Kit');const kitBytes=new Uint8Array(await kitFile.arrayBuffer());let kit;try{kit=recoveryKitBuilder.parseKit(kitBytes);}catch{throw new Error('Recovery Kit 文件类型或内部结构不正确。');}
  stage('正在从 Arweave Mainnet 下载 Archive');const downloaded=await downloadMainnet(evidence.txid);if(downloaded.bytes.length!==evidence.archive_size)throw new Error('Mainnet Archive 字节数不一致，已停止。');
  stage('正在校验 Archive SHA-256');const hashStart=performance.now(),archiveSha256=await cryptoEngine.hashHex(downloaded.bytes),archiveHashMs=elapsed(hashStart);if(archiveSha256!==evidence.archive_sha256)throw new Error('Mainnet Archive SHA-256 不一致，已停止。');
  const parsed=decodeMp4Archive(downloaded.bytes),authenticatedOriginalSha256=hex(parsed.originalSha256Bytes);
  stage('正在解锁 Recovery Kit');const unlockStart=performance.now(),dataKey=await recoveryKitBuilder.unwrapKit({kitBytes,password,kdfProvider:new Pbkdf2Provider(),expectedSnapshotId:kit.snapshot_id,expectedCiphertextSha256:archiveSha256}),kitUnlockMs=elapsed(unlockStart);
  try{stage('正在浏览器本地解密 MP4');const decryptStart=performance.now(),bytes=await cryptoEngine.decryptSnapshot({algorithm:'AES-256-GCM',nonce:parsed.nonce,aad:parsed.aad,ciphertext:parsed.ciphertext},{dataKey,expectedAad:mp4ArchiveAad()}),decryptMs=elapsed(decryptStart);const recoveredHash=await cryptoEngine.hashHex(bytes);if(bytes.length!==parsed.originalSize||recoveredHash!==authenticatedOriginalSha256)throw new Error('恢复 MP4 完整性校验失败。');stage('正在生成恢复文件');const generationStart=performance.now();state.delivery=createMp4Delivery({bytes,filename:parsed.filename,mimeType:parsed.mimeType,sha256:recoveredHash});const generationMs=elapsed(generationStart),totalMs=elapsed(totalStart);state.result={status:'PASS',network:NETWORK,txid:evidence.txid,gateway:downloaded.url,http_status:downloaded.status,archive_size:downloaded.bytes.length,archive_sha256:archiveSha256,download_ms:downloaded.ms,archive_hash_ms:archiveHashMs,kit_unlock_ms:kitUnlockMs,decrypt_ms:decryptMs,file_generation_ms:generationMs,total_to_downloadable_ms:totalMs,recovered_filename:parsed.filename,recovered_size:bytes.length,recovered_sha256:recoveredHash,evidence_original_sha256:evidence.original_mp4_sha256??null,authenticated_archive_header_original_sha256:authenticatedOriginalSha256,sha256_match:recoveredHash===authenticatedOriginalSha256,broadcasts:0,cost_ar:0};$('#result-name').textContent=parsed.filename;$('#result-size').textContent=size(bytes.length);$('#result-hash').textContent=recoveredHash;$('#success').hidden=false;$('#download').disabled=false;$('#download-again').disabled=false;$('#recovery-evidence').textContent=JSON.stringify(state.result,null,2);stage('恢复完成');state.delivery.download();status('恢复完成，已尝试自动下载；如浏览器阻止，请点击“下载恢复 MP4”。');}finally{cryptoEngine.wipeSensitiveReference(dataKey);}
}catch(error){state.delivery=null;throw error;}finally{password='';$('#password').value='';}}
async function run(action){try{status('处理中……');await action();}catch(error){status(error.message);}}
$('#recover').onclick=()=>run(recover);$('#download').onclick=()=>run(()=>state.delivery?state.delivery.download():Promise.reject(new Error('尚无可下载的恢复文件。')));$('#download-again').onclick=()=>run(()=>state.delivery?state.delivery.download():Promise.reject(new Error('尚无可再次下载的恢复文件。')));
