import { buildWizardConfiguration } from '../src/wizard/config-loader.js';
import { validatePlanCatalog, selectRecoveryPlan } from '../src/wizard/plan-selector.js';
import { mapWizardDraftToKnowledge } from '../src/ui/knowledge-mapper.js';
import { checkRecoveryConfidence } from '../src/confidence/confidence-checker.js';
import { cryptoEngine } from '../src/crypto/crypto-engine.js';
import { createVaultArtifacts } from '../src/ui/vault-pipeline.js';
import { validateRecoveryPassword } from '../src/ui/password-policy.js';
import { VaultMemorySession } from '../src/ui/vault-session.js';
import { RehearsalStateMachine, VAULT_STATES } from '../src/ui/rehearsal-machine.js';
import { saveBytesLocally } from '../src/ui/file-save.js';
import { assertAttachmentAllowed, assertVersionCapacity, attachmentCapacity, classifyAttachment, resolveAttachmentMime } from '../src/ui/attachment-policy.js';
import { canTriggerWithEnter } from '../src/ui/keyboard-policy.js';
import { LocalVersionHistory } from '../src/ui/version-history.js';
import { validateWizardDraft, safeCustomFields } from '../src/wizard/draft-validator.js';
import { assertReadyForGeneration } from '../src/review/readiness-rules.js';
import { ReviewRevisionTracker } from '../src/review/review-revision.js';
import { assertFinalGenerationState, runWithBusyButton, userErrorCode } from '../src/ui/generation-controller.js';
import { renderRecoveryMap } from './map-view.js';

const app=document.querySelector('#app'),session=new VaultMemorySession(),machine=new RehearsalStateMachine(),history=new LocalVersionHistory(),reviewTracker=new ReviewRevisionTracker();
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=prefix=>`${prefix}-${crypto.randomUUID()}`,formatBytes=value=>value>=1048576?`${(value/1048576).toFixed(1)} MB`:`${Math.ceil(value/1024)} KB`;
let content,reviewMessages,guidance,attachmentPolicy,passwordPolicy,planCatalog,templates,configuration,selectedPlan,knowledge,confidence;
let currentModule=0,currentStep=0,currentEntry=0,kitSaved=false,archiveSaved=false;

async function json(path){const response=await fetch(path);if(!response.ok)throw new Error('本地配置加载失败');return response.json();}
async function loadResources(){
  [content,reviewMessages,guidance,attachmentPolicy,passwordPolicy,planCatalog]=await Promise.all([json('../config/content/zh-CN.json'),json('../config/content/review-zh-CN.json'),json('../config/guidance/zh-CN-v1.json'),json('../config/attachments/v1.json'),json('../config/security/recovery-password-v1.json'),json('../config/plans/v1.json')]);
  validatePlanCatalog(planCatalog);const names=['wallet-assets','exchange-custody','digital-accounts','business-systems','devices-locations','contacts-assistance','recovery-orders-warnings'];templates=await Promise.all(names.map(name=>json(`../config/templates/${name}.json`)));
}
function showError(error){const node=document.querySelector('#message');if(node){node.className='error';node.textContent=reviewMessages?.[error?.code]||(['REVIEW_BLOCKED','INVALID_KNOWLEDGE_MAP'].includes(error?.code)?'请先修复恢复计划中的必填或格式问题':'操作未完成，请检查当前页面后重试。');}}
function setDraftValue(item,key,value){if(JSON.stringify(item[key])===JSON.stringify(value))return;item[key]=value;reviewTracker.changed();knowledge=null;confidence=null;}
function welcome(){app.innerHTML=`<section class="hero"><div class="eyebrow">Recovery Map Builder</div><h1>建立恢复地图，而不是把资产交给平台。</h1><p>CJAS 帮你整理未来如何找到资料、联系谁、先做什么，以及什么时候应该停止。平台不保存你的恢复密码，也不能控制你的资产。</p><div class="notice">请记录线索和恢复路径。不要上传完整私钥、完整助记词或全部控制条件。</div><div class="actions"><button id="start">选择恢复计划</button><a class="button secondary" href="./recover.html" target="_blank">我已有恢复材料</a></div></section>`;document.querySelector('#start').onclick=renderPlanSelection;}
function renderPlanSelection(){app.innerHTML=`<h1>选择恢复计划</h1><p>选择最接近当前需要的起点。之后仍可自由增加或移除模块。</p><div class="plan-grid">${planCatalog.plans.map(plan=>`<button class="plan-card ${plan.recommended?'recommended':''}" data-plan="${plan.id}"><span>${plan.recommended?'推荐':''}</span><strong>${escape(plan.title)}</strong><small>${escape(plan.description)}</small></button>`).join('')}</div><div id="message"></div><div class="actions"><button id="welcome-back" class="secondary">返回</button></div>`;document.querySelector('#welcome-back').onclick=welcome;document.querySelectorAll('[data-plan]').forEach(button=>button.onclick=()=>choosePlan(button.dataset.plan));}
function choosePlan(planId){selectedPlan=selectRecoveryPlan(planCatalog,planId,templates.map(item=>item.module_id));renderModuleSetup();}
function renderModuleSetup(){const active=new Set(selectedPlan.modules);app.innerHTML=`<h1>${escape(selectedPlan.title)}</h1><p>选择本次需要的模块，并按拖动之外的简单顺序按钮调整。模板只改变问题组合，不改变加密或恢复格式。</p><section class="card"><h2>恢复地图模块</h2><div class="module-list">${templates.map(template=>`<label><input type="checkbox" data-module="${template.module_id}" ${active.has(template.module_id)?'checked':''}> ${escape(content[template.title_key])}</label>`).join('')}</div><h3>自定义模块</h3><div class="entry"><input id="custom-module-name" placeholder="例如：家庭重要文件"><textarea id="custom-module-description" placeholder="这个模块要帮助未来的你找到什么？"></textarea><button id="add-custom-module" class="secondary" type="button">添加自定义模块</button></div><div>${session.draft.customCategories.map(item=>`<span class="chip">${escape(item.label)}</span>`).join(' ')}</div></section><div id="message"></div><div class="actions"><button id="plan-back" class="secondary">返回选择</button><button id="begin-wizard">开始填写</button></div>`;document.querySelector('#plan-back').onclick=renderPlanSelection;document.querySelector('#add-custom-module').onclick=()=>{const label=document.querySelector('#custom-module-name').value.trim(),description=document.querySelector('#custom-module-description').value.trim();if(!label)return showError({code:'REQUIRED'});session.draft.customCategories.push({id:uid('category'),label,description});reviewTracker.changed();renderModuleSetup();};document.querySelector('#begin-wizard').onclick=()=>{const modules=[...document.querySelectorAll('[data-module]:checked')].map(node=>node.dataset.module);if(!modules.length)return showError({code:'REQUIRED'});const previous=selectedPlan.modules;selectedPlan={...selectedPlan,modules};configuration=buildWizardConfiguration({config_version:2,flow_id:`week3-${selectedPlan.id}`,modules:modules.map((template,index)=>({template,enabled:true,order:(index+1)*10}))},templates,content);for(const module of configuration.modules)session.draft.modules[module.module_id]??=[{}];for(const key of Object.keys(session.draft.modules))if(!modules.includes(key))delete session.draft.modules[key];if(JSON.stringify(previous)!==JSON.stringify(modules))reviewTracker.changed();currentModule=0;currentStep=0;currentEntry=0;renderWizard();};}
function moduleGuidance(module){const item=guidance.modules[module.module_id]??{};return`<aside class="guidance"><h3>填写帮助</h3><p><strong>为什么：</strong>${escape(item.why)}</p><p><strong>建议填写：</strong>${escape(item.what)}</p><p><strong>不要填写：</strong>${escape(item.avoid)}</p><p><strong>示例：</strong>${escape(item.example)}</p><details><summary>常见遗漏、风险与“我不确定”</summary><p>${escape(item.omissions)}</p><p>${escape(item.risk)}</p><p>${escape(item.attachment)}</p><p>${escape(item.unsure)}</p></details></aside>`;}
function stepVisible(step,item){return !step.condition||item[step.condition.field]===step.condition.equals;}
function visibleSteps(module,item){return module.steps.filter(step=>stepVisible(step,item));}
function currentContext(){const module=configuration.modules[currentModule],entries=session.draft.modules[module.module_id],item=entries[currentEntry]??entries[0],steps=visibleSteps(module,item);if(currentStep>=steps.length)currentStep=Math.max(0,steps.length-1);return{module,entries,item,steps,step:steps[currentStep]};}
function customFieldsHtml(value=[]){return`<div data-custom-list>${safeCustomFields(value).map((field,index)=>`<div class="entry"><input data-custom-label="${index}" placeholder="字段名称" value="${escape(field.label)}"><input data-custom-value="${index}" placeholder="内容" value="${escape(field.value)}"><button class="danger" data-remove-custom="${index}" type="button">删除字段</button></div>`).join('')}</div><button id="add-custom" class="secondary" type="button">添加字段</button>`;}
function attachmentArea(){const capacity=attachmentCapacity(session.attachments.values(),attachmentPolicy),guides=attachmentPolicy.guides;return`<div class="attachment-panel"><p>支持 PDF/DOCX/TXT/JSON、JPG/PNG、MP3/M4A/WAV、MP4/MOV 和自定义 BIN。只上传已有文件，不提供录音或录像。</p><label>附件用途<select id="attachment-purpose">${guides.map(item=>`<option value="${item.id}">${escape(item.label)} · ${escape(item.purpose)}</option>`).join('')}</select></label><input id="attachment-file" type="file" accept=".pdf,.docx,.txt,.json,.jpg,.jpeg,.png,.mp3,.m4a,.wav,.mp4,.mov,.bin"><p class="capacity">已用 ${formatBytes(capacity.used_bytes)} / 50 MB · ${capacity.count} / 20 个，剩余 ${formatBytes(capacity.remaining_bytes)}</p><div class="attachment-list">${[...session.attachments.values()].map(value=>`<div class="file-row"><span>${escape(value.metadata.display_name)}</span><small>${escape(value.category)} · ${formatBytes(value.metadata.size)} · ${escape(value.metadata.purpose)}</small><button class="danger" data-remove-attachment="${value.metadata.id}" type="button">移除</button></div>`).join('')}</div><div class="notice">音频可留下口述说明；短视频可展示设备位置或步骤。不要在图片、音频或视频中暴露完整助记词、密码或全部控制条件。</div></div>`;}
function fieldHtml(step,item){const value=item[step.id]??'';if(step.type==='choice')return`<div class="choice">${step.options.map(option=>`<label><input type="radio" name="answer" value="${option}" ${value===option?'checked':''}>${option==='yes'?'是':'否'}</label>`).join('')}</div>`;if(step.type==='custom-fields')return customFieldsHtml(value);if(step.type==='attachment')return attachmentArea();return`<textarea id="answer" rows="5">${escape(value)}</textarea>`;}
function saveCurrent(){const{step,item}=currentContext();if(!step)return;if(step.type==='text')setDraftValue(item,step.id,document.querySelector('#answer')?.value.trim()??item[step.id]);if(step.type==='choice'){const checked=document.querySelector('input[name="answer"]:checked');if(checked)setDraftValue(item,step.id,checked.value);}if(step.type==='custom-fields'){const custom=[];document.querySelectorAll('[data-custom-label]').forEach(node=>{const index=node.dataset.customLabel,value=document.querySelector(`[data-custom-value="${index}"]`).value.trim();if(node.value.trim()||value)custom.push({label:node.value.trim(),value});});setDraftValue(item,step.id,custom);}}
function validateCurrent(){saveCurrent();const{step,item}=currentContext();if(step.required){const value=item[step.id];if(value===undefined||value===null||value===''||(Array.isArray(value)&&!value.length))throw new Error(`请完成：${step.label}`);}}
function moveNext(){try{validateCurrent();const context=currentContext();if(currentStep<context.steps.length-1){currentStep++;renderWizard();return;}if(currentModule<configuration.modules.length-1){currentModule++;currentStep=0;currentEntry=0;renderWizard();return;}prepareReview().catch(showError);}catch(error){showError(error);}}
function moveBack(){saveCurrent();if(currentStep>0)currentStep--;else if(currentModule>0){currentModule--;const context=currentContext();currentStep=Math.max(0,context.steps.length-1);}renderWizard();}
function renderWizard(){const{module,entries,item,steps,step}=currentContext(),overallIndex=configuration.modules.slice(0,currentModule).reduce((sum,value)=>sum+visibleSteps(value,session.draft.modules[value.module_id][0]).length,0)+currentStep+1,total=configuration.modules.reduce((sum,value)=>sum+visibleSteps(value,session.draft.modules[value.module_id][0]).length,0);app.innerHTML=`<div class="progress"><span style="width:${Math.min(100,overallIndex/Math.max(1,total)*100)}%"></span></div><div class="step-meta"><span>任务 ${overallIndex} / ${total}</span><span>${escape(module.title)} · 条目 ${currentEntry+1}</span></div><div class="wizard-layout"><section class="card"><p class="eyebrow">一次完成一个任务</p><h1>${escape(step.label)}</h1>${fieldHtml(step,item)}<div id="message"></div></section>${moduleGuidance(module)}</div><div class="actions"><button id="modules" class="secondary">调整模块</button>${currentModule||currentStep?'<button id="back" class="secondary">返回</button>':''}${step.skip_allowed?'<button id="skip" class="secondary">暂时跳过</button>':''}<button id="save-draft" class="secondary">保存草稿（仅本页）</button>${currentStep===steps.length-1?'<button id="add-entry" class="secondary">保存并新增同类条目</button>':''}<button id="next">${currentModule===configuration.modules.length-1&&currentStep===steps.length-1?'进入恢复计划检查':'下一步'}</button></div>`;bindWizardControls();}
function bindWizardControls(){document.querySelector('#modules').onclick=()=>{saveCurrent();renderModuleSetup();};document.querySelector('#back')?.addEventListener('click',moveBack);document.querySelector('#next').onclick=moveNext;document.querySelector('#skip')?.addEventListener('click',()=>{const{step,item}=currentContext();if(step.required)return showError({code:'REQUIRED'});setDraftValue(item,step.id,undefined);moveNext();});document.querySelector('#save-draft').onclick=()=>{saveCurrent();const node=document.querySelector('#message');node.className='success';node.textContent='草稿只保存在当前页面内存中。刷新或关闭页面后会清除。';};document.querySelector('#add-entry')?.addEventListener('click',()=>{try{validateCurrent();const{entries}=currentContext();entries.push({});reviewTracker.changed();currentEntry=entries.length-1;currentStep=0;renderWizard();}catch(error){showError(error);}});document.querySelector('#add-custom')?.addEventListener('click',()=>{saveCurrent();const{step,item}=currentContext(),fields=[...safeCustomFields(item[step.id]),{label:'',value:''}];setDraftValue(item,step.id,fields);renderWizard();});document.querySelectorAll('[data-remove-custom]').forEach(button=>button.onclick=()=>{saveCurrent();const{step,item}=currentContext(),fields=[...safeCustomFields(item[step.id])];fields.splice(Number(button.dataset.removeCustom),1);setDraftValue(item,step.id,fields);renderWizard();});document.querySelectorAll('input[name="answer"]').forEach(node=>node.onchange=()=>{saveCurrent();renderWizard();});document.querySelector('#attachment-file')?.addEventListener('change',addAttachments);document.querySelectorAll('[data-remove-attachment]').forEach(button=>button.onclick=()=>{if(session.attachments.delete(button.dataset.removeAttachment))reviewTracker.changed();renderWizard();});document.querySelector('#answer')?.addEventListener('keydown',event=>{if(event.key==='Enter'&&event.ctrlKey&&canTriggerWithEnter('wizard-next')){event.preventDefault();moveNext();}});}
async function addAttachments(event){try{for(const file of event.target.files){assertAttachmentAllowed(file,session.attachments.values(),attachmentPolicy);const bytes=new Uint8Array(await file.arrayBuffer()),id=uid('attachment'),guide=attachmentPolicy.guides.find(item=>item.id===document.querySelector('#attachment-purpose').value),group=classifyAttachment(file,attachmentPolicy);session.attachments.set(id,{bytes,category:group.category,metadata:{id,display_name:file.name.normalize('NFC'),media_type:resolveAttachmentMime(file,attachmentPolicy),size:file.size,sha256:await cryptoEngine.hashHex(bytes),purpose:guide.purpose,guide_id:guide.id}});reviewTracker.changed();}renderWizard();}catch(error){showError(error);event.target.value='';}}
async function attachmentInputs(){const metadata=[],payloads={};for(const[id,value]of session.attachments){const{guide_id, ...safeMetadata}=value.metadata;metadata.push(safeMetadata);payloads[id]=value.bytes;}return{metadata,payloads};}
async function calculateReview(){assertVersionCapacity(session.attachments.values(),attachmentPolicy);const draftResult=validateWizardDraft(configuration,session.draft);if(!draftResult.valid)return{knowledge:null,confidence:{status:'Critical Risk',issues:draftResult.issues}};const attachments=await attachmentInputs(),nextKnowledge=mapWizardDraftToKnowledge(session.draft,{vaultTitle:selectedPlan.title,attachmentMetadata:attachments.metadata}),observed=Object.fromEntries(attachments.metadata.map(item=>[item.id,item.sha256]));return{knowledge:nextKnowledge,confidence:checkRecoveryConfidence(nextKnowledge,{observedAttachmentHashes:observed})};}
async function prepareReview(){({knowledge,confidence}=await calculateReview());reviewTracker.reviewed();renderReview();}
function locateIssue(issue){const moduleIndex=configuration.modules.findIndex(module=>module.module_id===issue.module_id||module.steps.some(step=>step.id===(issue.field_id||issue.step_id)));if(moduleIndex>=0){const module=configuration.modules[moduleIndex],entryIndex=Math.min(issue.entry_index??0,session.draft.modules[module.module_id].length-1),index=visibleSteps(module,session.draft.modules[module.module_id][entryIndex]).findIndex(step=>step.id===(issue.field_id||issue.step_id));currentModule=moduleIndex;currentStep=Math.max(0,index);currentEntry=Math.max(0,entryIndex);renderWizard();return;}currentModule=0;currentStep=0;currentEntry=0;renderWizard();}
function renderReview(){if(!reviewTracker.isCurrent())return void prepareReview().catch(showError);const visible=confidence.issues.filter(item=>item.code!=='REHEARSAL_NOT_COMPLETED'),critical=visible.filter(item=>item.blocking===true||item.severity==='critical'),attention=visible.filter(item=>item.blocking!==true&&item.severity==='attention');const rows=items=>items.map((item,index)=>`<div class="issue"><span>${escape(reviewMessages[item.code]||'请检查此项内容')}</span>${item.field_id||item.step_id?`<button class="secondary" data-fix="${index}" data-group="${items===critical?'critical':'attention'}">返回修改</button>`:''}</div>`).join('');app.innerHTML=`<h1>恢复计划检查</h1><p>检查、生成门控和 Snapshot 使用相同的阻断定义。</p><section class="card"><h2>必须修复</h2>${rows(critical)||'<p class="success">没有阻止生成的问题。</p>'}</section><section class="card"><h2>建议补充</h2>${rows(attention)||'<p class="success">关键说明已经具备。</p>'}</section><section class="card"><h2>已准备好</h2><p>${critical.length?'修复以上问题后即可进入下一步。':'可以设置恢复密码；完成独立演练后状态才会变为已验证。'}</p></section><div id="message"></div><div class="actions"><button id="review-back" class="secondary">返回填写</button><button id="continue" ${critical.length?'disabled':''}>设置恢复密码</button></div>`;document.querySelector('#review-back').onclick=()=>{currentModule=0;currentStep=0;renderWizard();};document.querySelector('#continue').onclick=renderPassword;document.querySelectorAll('[data-fix]').forEach(button=>button.onclick=()=>locateIssue((button.dataset.group==='critical'?critical:attention)[Number(button.dataset.fix)]));}
function passwordResult(){return validateRecoveryPassword(document.querySelector('#password').value,document.querySelector('#confirmation').value,document.querySelector('#ack').checked,{policy:passwordPolicy,vaultName:selectedPlan.title});}
function updatePasswordFeedback(){const result=passwordResult(),labels={uppercase:'大写字母',lowercase:'小写字母',number:'数字',special:'特殊字符'},status=document.querySelector('#password-status');status.className=result.valid?'success':'notice';status.innerHTML=`<strong>${result.status}</strong><br>当前长度：${result.length} / ${passwordPolicy.min_code_points}–${passwordPolicy.max_code_points}<br>${Object.entries(result.categories).map(([key,present])=>`${present?'✓':'○'} ${labels[key]}`).join(' · ')}${result.issues.length?`<ul>${result.issues.map(item=>`<li>${escape(item.message)}</li>`).join('')}</ul>`:''}`;document.querySelector('#create').disabled=!result.valid;return result;}
function renderPassword(){app.innerHTML=`<h1>设置恢复密码</h1><p>恢复密码用于打开 Kit 中受保护的恢复能力。CJAS 不保存，也不能替你找回。</p><section class="card"><label class="field">恢复密码<input id="password" type="password" autocomplete="new-password"></label><label class="field">再次输入<input id="confirmation" type="password" autocomplete="new-password"></label><div id="password-status" class="notice" aria-live="polite"></div><label class="choice" for="ack"><input id="ack" type="checkbox"><span>我理解平台不能找回恢复密码。</span></label><div class="notice">必须显式点击生成按钮；按 Enter 不会生成。密码不会被自动修改、截断、记录或发送。</div><div id="message"></div></section><div class="actions"><button id="password-back" class="secondary">返回检查</button><button id="create" disabled>生成恢复材料</button></div>`;document.querySelector('#password-back').onclick=renderReview;document.querySelector('#create').onclick=createArtifacts;for(const input of document.querySelectorAll('input')){input.addEventListener('keydown',event=>{if(event.key==='Enter')event.preventDefault();});input.addEventListener(input.id==='ack'?'change':'input',updatePasswordFeedback);}updatePasswordFeedback();}
async function createArtifacts(){const password=document.querySelector('#password').value,policyResult=passwordResult();if(!policyResult.valid)return showError({code:policyResult.issues[0]?.code});const button=document.querySelector('#create');try{await runWithBusyButton(button,async()=>{assertFinalGenerationState({reviewCurrent:reviewTracker.isCurrent(),knowledge,acknowledged:document.querySelector('#ack').checked});const recalculated=await calculateReview();confidence=recalculated.confidence;assertReadyForGeneration(confidence);knowledge=recalculated.knowledge;const attachment=await attachmentInputs(),createdAt=new Date().toISOString();session.vaultId??=`vault-${crypto.randomUUID()}`;const version=session.versionNumber+1,snapshotId=`snapshot-v${version}-${crypto.randomUUID()}`;session.artifacts=await createVaultArtifacts({knowledgeGraph:knowledge,attachmentPayloads:attachment.payloads,password,wizardConfigVersion:configuration.config_version,vaultId:session.vaultId,snapshotId,createdAt});session.versionNumber=version;machine.reset();machine.transition(VAULT_STATES.SNAPSHOT,{snapshotId});const kitName=`LEGAVIK-Recovery-Kit-${snapshotId}.cjas`;history.add({version,snapshotId,createdAt,status:'Rehearsal Required',summary:`${knowledge.assets.length} 项资料 · ${knowledge.attachments.length} 个附件`,kitName,archiveName:`LEGAVIK-Encrypted-Archive-${snapshotId}.cjasvault`});session.artifacts.kitName=kitName;session.artifacts.archiveDownloadName=`LEGAVIK-Encrypted-Archive-${snapshotId}.cjasvault`;kitSaved=false;archiveSaved=false;renderDownloads();});}catch(error){showError({code:userErrorCode(error)});}}
function updateDownloadState(){if(kitSaved&&archiveSaved&&machine.state===VAULT_STATES.KIT)machine.transition(VAULT_STATES.REQUIRED);document.querySelector('#rehearse').disabled=machine.state!==VAULT_STATES.REQUIRED;}
function markSaved(kind){if(kind==='kit'){kitSaved=true;if(machine.state===VAULT_STATES.SNAPSHOT)machine.transition(VAULT_STATES.KIT);}else archiveSaved=true;updateDownloadState();}
async function saveArtifact(kind,bytes,name){const button=document.querySelector(`#${kind}-download`),status=document.querySelector(`#${kind}-status`),confirm=document.querySelector(`#${kind}-confirm`);button.disabled=true;confirm.hidden=true;status.textContent='正在准备保存…';try{const result=await saveBytesLocally({bytes,suggestedName:name,mimeType:'application/octet-stream'});if(result.status==='saved'){markSaved(kind);status.className='success';status.textContent='已保存。';}else if(result.status==='cancelled'){status.className='muted';status.textContent='已取消；此项仍未完成。';}else{status.className='muted';status.textContent='已发送到浏览器下载。请在下载列表找到文件后确认。';confirm.hidden=false;}}catch{status.className='error';status.textContent='保存失败，请重试。';}finally{button.disabled=false;}}
function renderDownloads(){const safari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);app.innerHTML=`<h1>保存恢复所需的三项条件</h1><section class="card"><h2>1. Recovery Kit</h2><p>此版本专属的密码保护恢复能力。</p><button id="kit-download">保存 ${escape(session.artifacts.kitName)}</button><button id="kit-confirm" class="secondary" hidden>我已在下载列表找到 Kit</button><p id="kit-status" class="muted">尚未保存</p></section><section class="card"><h2>2. 加密档案</h2><p>包含完整 Recovery Map 和附件的本地加密文件。</p><button id="archive-download">保存 ${escape(session.artifacts.archiveDownloadName)}</button><button id="archive-confirm" class="secondary" hidden>我已在下载列表找到档案</button><p id="archive-status" class="muted">尚未保存</p></section><section class="card"><h2>3. 恢复密码</h2><p>不要与 Kit 和加密档案放在同一未保护位置。平台不能找回。</p></section><div class="notice">Kit 与加密档案必须同时保管。停止续费或平台不可用不影响既有版本恢复。${safari?'Safari 会保存到默认下载目录，请打开浏览器下载列表定位文件。':'Chrome / Edge 推荐体验：可在系统窗口中选择保存路径。'}</div><div class="actions"><button id="rehearse" disabled>开始独立恢复演练</button></div>`;document.querySelector('#kit-download').onclick=()=>saveArtifact('kit',session.artifacts.kitBytes,session.artifacts.kitName);document.querySelector('#archive-download').onclick=()=>saveArtifact('archive',session.artifacts.archiveBytes,session.artifacts.archiveDownloadName);for(const kind of ['kit','archive'])document.querySelector(`#${kind}-confirm`).onclick=()=>{markSaved(kind);document.querySelector(`#${kind}-confirm`).hidden=true;document.querySelector(`#${kind}-status`).className='success';document.querySelector(`#${kind}-status`).textContent='已确认下载文件存在。';};document.querySelector('#rehearse').onclick=()=>window.open(`./recover.html?rehearsal=${encodeURIComponent(session.artifacts.snapshot.snapshot_id)}`,'cjas-rehearsal');}
window.addEventListener('message',event=>{if(event.origin!==location.origin||event.data?.type!=='cjas-rehearsal-pass'||machine.state!==VAULT_STATES.REQUIRED)return;try{machine.transition(VAULT_STATES.PASSED,{recoveredSnapshotId:event.data.snapshotId,attachmentsVerified:event.data.attachmentsVerified});machine.transition(VAULT_STATES.VERIFIED);history.markVerified(event.data.snapshotId);renderComplete();}catch{}});
function historyHtml(){return history.list().map(item=>`<div class="version-row ${item.current?'current':''}"><strong>Version ${item.version}${item.current?' · 当前版本':''}</strong><span>${escape(item.created_at)}</span><span>${escape(item.status)}</span><span>${escape(item.summary)}</span><small>${escape(item.kit_name)}<br>${escape(item.archive_name)}</small></div>`).join('');}
function renderComplete(){app.innerHTML=`<section class="hero"><div class="eyebrow">Verified</div><h1>Recovery Map Version ${session.versionNumber} 已验证。</h1><p>你现在拥有 Recovery Kit、加密档案、恢复密码和一个经过演练的完整版本。</p><div class="notice">每次更新都会生成新的完整 Version 和新 Kit；旧 Kit 继续恢复旧版本。建议定期演练和核对资料。</div><div class="actions"><button id="view">查看恢复地图</button><button id="new-version" class="secondary">基于当前内容创建新版本</button></div><div id="map"></div></section><section class="card"><h2>Version History（本地演示）</h2><p>历史仅保存在当前内存会话，不是独立恢复依赖。</p>${historyHtml()}</section>`;document.querySelector('#view').onclick=()=>renderRecoveryMap(document.querySelector('#map'),session.artifacts.snapshot);document.querySelector('#new-version').onclick=()=>{session.artifacts=null;currentModule=0;currentStep=0;currentEntry=0;machine.reset();renderWizard();};}
window.addEventListener('beforeunload',event=>{if(session.hasUnsavedWork()){event.preventDefault();event.returnValue='';}});
await loadResources();welcome();
