import {recoverAttachmentForDownload} from '../src/recovery/attachment-recovery.js';
import {saveBytesLocally} from '../src/ui/file-save.js';
import {projectRecoveredReport} from '../src/product-v2/recovered-report.js';
import {attachmentFriendlyType} from '../src/ui/attachment-display.js';
import {formatByteSize} from '../src/ui/format-byte-size.js';

const RECOVERY_GUIDE_URL='./assets/LEGAVIK-Recovery-Guide-V1.pdf';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const domId=value=>String(value??'account').replace(/[^a-zA-Z0-9_-]/g,'-');
const groupsFor=map=>map.schema_version===2?[]:[['资产线索',map.assets,'label'],['存放位置',map.locations,'description'],['设备',map.devices,'identifying_features'],['联系人',map.contacts,'role'],['恢复顺序',map.orders,'action'],['风险警告',map.warnings,'instruction']];
const isSharedRecoverySummary=file=>file.attachment_scope==='MODULE_SUMMARY'&&['locations','instructions'].includes(file.module_id);
const fileTypeCounts=files=>['文档','图片','语音','视频','其他'].map(type=>[type,files.filter(file=>attachmentFriendlyType(file)===type).length]).filter(([,count])=>count);
const fileTypeSummary=files=>fileTypeCounts(files).map(([type,count])=>`${type} ${count}`).join(' · ')||'暂无附件';
const status=value=>value?'已记录':'未记录';
const isGeneratedRecoveryAdvice=text=>/^按(?: .+ )?官方(?:恢复路径|流程).*[。.]?$/.test(String(text||'').trim());
const attachmentScopeLabel=file=>file.attachment_scope==='MODULE_SUMMARY'?'汇总资料':file.attachment_scope.startsWith('ACCOUNT:')?'本账户资料':'';

const attachmentHtml=(file,{accountLabel}={})=>`<article class="map-attachment${isSharedRecoverySummary(file)?' is-shared-summary':''}"><div class="map-attachment-main"><strong>${escape(file.file_name)}</strong><p>${attachmentFriendlyType(file)} · ${formatByteSize(file.byte_length)} · ${escape(file.module_label)}${attachmentScopeLabel(file)?` · ${attachmentScopeLabel(file)}`:''}</p>${file.account_id?`<p>所属账户：${escape(file.account_label)}</p>`:''}</div><div class="map-attachment-actions"><button class="quiet-file-action" data-attachment-id="${file.attachment_id}" data-attachment-action="download">下载</button></div>${isSharedRecoverySummary(file)?`<p class="shared-summary-note">这是一份模块汇总附件，填写人在本模块中用于集中记录多个账户相关信息。请打开后查找“${escape(accountLabel||'当前平台或钱包名称')}”对应部分。如已下载同一份汇总资料，无需重复下载。</p>`:''}</article>`;

const workspaceSection=(number,title,body,className='',summaryNote='')=>`<details class="card workspace-section ${className}" data-workspace-section="${number}"><summary><span class="section-number">${number}</span><strong>${title}</strong>${summaryNote?`<span class="section-summary-note">${summaryNote}</span>`:''}<span class="section-toggle"><span class="when-closed">▶ 展开</span><span class="when-open">▼ 收起</span></span></summary><div class="workspace-section-body">${body}</div></details>`;
const modulePanel=(number,title,body)=>`<details class="map-module card"><summary><span>${number}</span><strong>${title}</strong><span class="section-toggle"><span class="when-closed">▶ 展开</span><span class="when-open">▼ 收起</span></span></summary><div class="map-module-body">${body}</div></details>`;

const guideItem=(number,title,body)=>`<details class="recovery-guide-item"><summary><span>▶</span><strong>${number}｜${title}</strong></summary><div>${body}</div></details>`;
const guideHtml=()=>`<details class="card workspace-section recovery-guide" data-workspace-section="01"><summary><span class="section-number">01</span><strong>如何理解和使用这份 Recovery Map</strong><span class="recovery-guide-actions"><a href="${RECOVERY_GUIDE_URL}" target="_blank" rel="noopener" data-recovery-guide-action>在线查看使用手册</a><a href="${RECOVERY_GUIDE_URL}" download="LEGAVIK-Recovery-Guide-V1.pdf" data-recovery-guide-action>下载使用手册</a></span><span class="section-toggle"><span class="when-closed">▶ 展开</span><span class="when-open">▼ 收起</span></span></summary><div class="workspace-section-body recovery-guide-body">${guideItem('01','第一次使用，请按这个顺序','<ol class="recovery-guide-steps"><li><strong>STEP 1｜先看账户与钱包总览</strong><span>先了解包含哪些账户和钱包，不要立即移动资产。</span></li><li><strong>STEP 2｜先看填写人的特别说明与嘱托</strong><span>确认优先顺序、暂不操作的账户、应先联系的人和特殊安排。特别说明可能改变正常恢复顺序。</span></li><li><strong>STEP 3｜一次只处理一个账户</strong><span>完成或确认一个账户后，再处理下一个。</span></li><li><strong>STEP 4｜按照三个问题处理当前账户</strong><span>需要什么 → 在哪里 → 怎么恢复。先确认条件，再找到材料，最后执行步骤。</span></li><li><strong>STEP 5｜不确定时先停止</strong><span>不要猜测或进行不可逆操作；重新查看嘱托、相关附件和协助人信息，必要时寻求帮助。</span></li><li><strong>STEP 6｜完成当前账户，再进入下一个</strong><span>返回账户与钱包总览，继续逐一处理。</span></li></ol>')}${guideItem('02','Recovery Map 的六个部分','<p class="guide-lead"><strong>六个模块是填写人整理资料的方式，不是六套不同的恢复流程。</strong></p><div class="recovery-module-explainer"><p><b>01｜资产与账户</b><span>填写人记录了哪些平台、账户或钱包。</span></p><p><b>02｜恢复所需条件与资料</b><span>恢复每个账户实际需要哪些条件和材料。</span></p><p><b>03｜位置与查找</b><span>这些材料、设备或信息在哪里，以及如何找到。</span></p><p><b>04｜恢复与转移步骤</b><span>找到材料以后，应按什么步骤恢复或处理。</span></p><p><b>05｜协助人</b><span>填写人指定了谁、什么时候联系、可以协助什么。</span></p><p><b>06｜给未来恢复人的嘱托</b><span>填写人留下的特别提醒、个人安排或想说的话。</span></p></div><p class="recovery-path-line">有什么 → 需要什么 → 在哪里 → 怎么恢复 → 谁可以帮助 → 还有什么特别想告诉你</p>')}${guideItem('03','如何理解不同资料和附件','<div class="recovery-material-explainer"><p><b>在线填写信息</b><span>填写人在 LEGAVIK 页面直接填写的重要恢复信息。</span></p><p><b>本账户相关附件</b><span>填写人在当前账户下上传的相关资料。LEGAVIK 按填写时已有的账户和模块归属为你展示。</span></p><p><b>模块汇总附件</b><span>填写人在同一模块中用于集中记录多个账户相关信息的资料。打开后请查找当前账户或平台名称对应部分；如已下载同一份汇总资料，无需重复下载。</span></p></div><p class="system-navigation-boundary">LEGAVIK依据填写时已有的模块和账户关联帮助你查找资料，不读取、分析或重新解释填写人上传的附件内容。</p><p>填写人当时留下的完整原始信息和附件，均保留在“填写人原始档案”中。如需核对完整底档，可随时返回查看。</p>')}${guideItem('04','什么时候应该停止并寻求帮助','<p class="guide-lead"><strong>不确定时，宁可暂停，也不要猜测。</strong></p><ul class="recovery-stop-list"><li>信息与当前实际情况不一致；</li><li>不确定是否应该重置设备或重新绑定 2FA；</li><li>无法确认地址、网络或账户身份；</li><li>平台界面与填写人说明明显不同；</li><li>无法确认 Seed Phrase / 助记词或 Private Key / 私钥的使用是否安全；</li><li>不确定应该信任哪一项信息。</li></ul><p>建议依次查看：填写人的特别说明与嘱托 → 当前账户相关附件 → 填写人留下的协助人 → 适用时咨询 Spark / LEGAVIK。</p>')}</div></details>`;

const uniqueBy=(items,key)=>[...new Map(items.map(item=>[item[key],item])).values()];
const materialSources=({onlineHtml='',files=[],sharedFiles=[],accountLabel,emptyText})=>{const accountFiles=uniqueBy(files,'attachment_id'),summaries=uniqueBy(sharedFiles,'attachment_id');return `<div class="material-source-list">${onlineHtml?`<section class="material-source-block"><h5>在线填写信息</h5>${onlineHtml}</section>`:''}${accountFiles.length?`<section class="material-source-block"><h5>本账户相关附件</h5><p>以下资料由填写人在当前账户下上传。</p>${accountFiles.map(file=>attachmentHtml(file,{accountLabel})).join('')}</section>`:''}${summaries.length?`<section class="material-source-block"><h5>模块汇总附件</h5><p>这类资料由填写人在本模块中用于集中记录多个账户相关信息。</p>${summaries.map(file=>attachmentHtml(file,{accountLabel})).join('')}</section>`:''}${!onlineHtml&&!accountFiles.length&&!summaries.length?`<p class="muted">${emptyText}</p>`:''}</div>`;};

const accountPanel=(account,index,{sharedLocationFiles=[],sharedInstructionFiles=[]}={})=>{
  const locationFiles=account.attachments.filter(file=>file.module_id==='locations'),instructionFiles=account.attachments.filter(file=>file.module_id==='instructions'),otherFiles=account.attachments.filter(file=>!['locations','instructions'].includes(file.module_id));
  const locations=uniqueBy(account.conditions.flatMap(item=>item.coverage),'location_id'),locationHtml=locations.length?`<ul class="structured-location-list">${locations.map(value=>`<li><strong>${escape(value.label)}</strong>${value.description?`：${escape(value.description)}`:''}</li>`).join('')}</ul>`:'';
  const instructionText=isGeneratedRecoveryAdvice(account.instruction.instruction_text)?'':account.instruction.instruction_text;
  return `<details class="map-account" id="recovery-account-${domId(account.account_id)}" data-account-id="${escape(account.account_id)}"><summary><span>${String(index+1).padStart(2,'0')}</span><strong>${escape(account.label)}</strong><span class="section-toggle"><span class="when-closed">▶ 展开账户</span><span class="when-open">▼ 收起账户</span></span></summary><div class="map-account-body"><section class="account-recovery-part"><h4><span class="content-step">1.</span>账户信息</h4><dl class="account-facts"><div><dt>平台</dt><dd>${escape(account.platform)}</dd></div><div><dt>类型</dt><dd>${escape(account.account_type)}</dd></div><div><dt>地区</dt><dd>${escape(account.region)}</dd></div></dl></section><section class="account-recovery-part"><h4><span class="content-step">2.</span>恢复需要什么</h4><ol class="condition-list">${account.conditions.map((item,conditionIndex)=>`<li><span>${String(conditionIndex+1).padStart(2,'0')}</span>${escape(item.label)}</li>`).join('')||'<li>未记录恢复条件。</li>'}</ol></section><section class="account-recovery-part"><h4><span class="content-step">3.</span>这些材料在哪里</h4>${materialSources({onlineHtml:locationHtml,files:locationFiles,sharedFiles:sharedLocationFiles,accountLabel:account.label,emptyText:'未记录相关位置资料。'})}</section><section class="account-recovery-part"><h4><span class="content-step">4.</span>怎么恢复</h4>${materialSources({onlineHtml:instructionText?`<p class="instruction-summary">${escape(instructionText)}</p>`:'',files:instructionFiles,sharedFiles:sharedInstructionFiles,accountLabel:account.label,emptyText:'未记录相关恢复步骤资料。'})}</section><section class="account-recovery-part"><h4><span class="content-step">5.</span>其他相关附件</h4>${uniqueBy(otherFiles,'attachment_id').map(file=>attachmentHtml(file,{accountLabel:account.label})).join('')||'<p class="muted">无其他相关附件。</p>'}</section></div></details>`;
};

export function buildRecoveryWorkspaceHtml(snapshot){
  const report=projectRecoveredReport(snapshot),files=report.attachment_directory,byModule=id=>files.filter(file=>file.module_id===id),message=report.personal_message?.text||'',moduleFiles=id=>byModule(id).filter(file=>!file.attachment_scope.startsWith('ACCOUNT:'));
  const sharedLocationFiles=files.filter(file=>isSharedRecoverySummary(file)&&file.module_id==='locations'),sharedInstructionFiles=files.filter(file=>isSharedRecoverySummary(file)&&file.module_id==='instructions'),sharedFor=(collection,accountId)=>collection.filter(file=>!file.related_account_ids?.length||file.related_account_ids.includes(accountId));
  const moduleAccounts=(id,body)=>`${moduleFiles(id).map(file=>attachmentHtml(file)).join('')}${report.accounts.map(account=>`<section class="map-module-account"><h4>${escape(account.label)}</h4>${body(account)}${account.attachments.filter(file=>file.module_id===id).map(file=>attachmentHtml(file,{accountLabel:account.label})).join('')}</section>`).join('')}`;
  const overview=report.accounts.map((account,index)=>{
    const locationAccountFiles=account.attachments.filter(file=>file.module_id==='locations'),instructionAccountFiles=account.attachments.filter(file=>file.module_id==='instructions'),accountSharedLocations=sharedFor(sharedLocationFiles,account.account_id),accountSharedInstructions=sharedFor(sharedInstructionFiles,account.account_id),hasLocation=account.conditions.some(item=>item.coverage.length),hasInstruction=Boolean(account.instruction.instruction_text),hasAnyFiles=Boolean(account.attachments.length||accountSharedLocations.length||accountSharedInstructions.length);
    return `<tr><td>${String(index+1).padStart(2,'0')}</td><td><a href="#recovery-account-${domId(account.account_id)}" data-account-target="${escape(account.account_id)}">${escape(account.label)}</a></td><td>${escape(account.account_type)}</td><td>${status(account.conditions.length)}</td><td>${hasLocation?'已记录':locationAccountFiles.length||accountSharedLocations.length?'相关信息在附件中':'未记录'}</td><td>${hasInstruction?'已记录':instructionAccountFiles.length||accountSharedInstructions.length?'相关信息在附件中':'未记录'}</td><td>${hasAnyFiles?'有相关资料':'无相关附件'}</td></tr>`;
  }).join('');
  const messageFiles=byModule('message'),messageBody=message?`<p class="recovery-message-intro">开始恢复任何账户前，建议先查看填写人留下的特别说明与相关附件。</p><p class="recovery-message-text">${escape(message)}</p>`:messageFiles.length?`<p class="recovery-message-intro">开始恢复任何账户前，建议先查看填写人留下的特别说明与相关附件。</p><p>填写人没有留下在线文字说明，但留下了 ${messageFiles.length} 个相关附件，请优先查看。</p><p class="recovery-file-summary">${fileTypeSummary(messageFiles)}</p>`:'<p>未留下特别说明与嘱托。</p>';
  const overviewSection=workspaceSection('02','账户与钱包总览',`<div class="recovery-table-wrap"><table><thead><tr><th>#</th><th>平台 / 钱包</th><th>类型</th><th>恢复条件</th><th>位置信息</th><th>恢复步骤</th><th>附件</th></tr></thead><tbody>${overview||'<tr><td colspan="7">未记录账户或钱包。</td></tr>'}</tbody></table></div>`,'recovery-overview');
  const messageSection=workspaceSection('03','填写人给你的特别说明与嘱托',`${messageBody}${messageFiles.map(file=>attachmentHtml(file)).join('')}`,'recovery-message');
  const accountsSection=workspaceSection('04','按账户逐一恢复',`<p class="section-intro">从一个账户开始，依次核对恢复条件、保存位置、恢复步骤和相关附件。</p><div class="recovery-account-list">${report.accounts.map((account,index)=>accountPanel(account,index,{sharedLocationFiles:sharedFor(sharedLocationFiles,account.account_id),sharedInstructionFiles:sharedFor(sharedInstructionFiles,account.account_id)})).join('')||'<p>未记录账户。</p>'}</div>${report.assistance.assistants.length?'<p><button type="button" class="assistant-section-link" data-assistant-target>需要协助？查看填写人留下的协助人信息 →</button></p>':''}`,'recovery-account-view');
  const archiveBody=`<p class="section-intro">这里完整保留填写人当时留下的六个模块和原始附件。上面的账户恢复视图用于帮助你更快查找和处理；如需核对完整原始信息，可以随时回到这里查看。</p>${modulePanel('01','资产与账户',moduleAccounts('accounts',account=>`<p>${escape(account.platform)} · ${escape(account.region)} · ${escape(account.account_type)}</p>`))}${modulePanel('02','恢复所需条件与资料',moduleAccounts('conditions',account=>`<ol>${account.conditions.map(item=>`<li>${escape(item.label)}</li>`).join('')||'<li>未填写</li>'}</ol>`))}${modulePanel('03','位置与查找',moduleAccounts('locations',account=>`<ul>${account.conditions.map(item=>`<li><strong>${escape(item.label)}</strong>：${item.coverage.map(value=>escape(value.description||value.label)).join('；')||'未填写'}</li>`).join('')}</ul>`))}${modulePanel('04','恢复与转移步骤',moduleAccounts('instructions',account=>`<p>${escape(account.instruction.instruction_text||'未填写')}</p>`))}${modulePanel('05','协助人',`${report.assistance.assistants.map(item=>`<p><strong>${escape(item.label||item.role)}</strong><br>${escape(item.when_to_contact||'')}<br>${escape(item.assistance_boundary||'')}</p>`).join('')||'<p>未设置协助人</p>'}${byModule('assistants').map(file=>attachmentHtml(file)).join('')}`)}${modulePanel('06','给未来恢复人的嘱托',`<p>${escape(message||'未填写')}</p>${moduleFiles('message').map(file=>attachmentHtml(file)).join('')}`)}`;
  const assistantFiles=byModule('assistants'),hasAssistant=Boolean(report.assistance.assistants.length||assistantFiles.length),assistantBody=hasAssistant?`<p class="section-intro">以下为填写人在“协助人”模块中留下的信息。如需要帮助，请根据填写人的说明判断是否以及何时联系。</p>${report.assistance.assistants.map(item=>`<article class="account-helper"><strong>${escape(item.label||item.role)}</strong><dl><div><dt>身份 / 角色</dt><dd>${escape(item.role||'未记录')}</dd></div><div><dt>什么时候联系</dt><dd>${escape(item.when_to_contact||'未记录')}</dd></div><div><dt>可以协助什么 / 权限边界</dt><dd>${escape(item.assistance_boundary||'未记录')}</dd></div></dl></article>`).join('')}${assistantFiles.map(file=>attachmentHtml(file)).join('')}`:'<p>填写人未留下协助人信息。</p><p>如需进一步帮助，请继续查阅填写人留下的特别说明、相关附件或其他恢复资料。</p>';
  const assistantSection=workspaceSection('05','协助人',assistantBody,'recovery-assistance-section');
  const archiveSection=workspaceSection('06','填写人原始档案',archiveBody,'recovery-module-view');
  const helpSection=workspaceSection('07','需要帮助？',`<div class="recovery-help-order"><p>如果遇到无法确认的信息，请先停止操作，并依次查看：</p><ol><li>填写人的特别说明与嘱托</li><li>当前账户相关资料</li><li>协助人信息（如有）</li></ol><p><strong>不确定时，宁可暂停，也不要猜测。</strong></p></div><div class="spark-help"><h3>仍有疑问？可以咨询 Spark</h3><p>如果查看了填写人的特别说明、相关附件和协助人信息后，仍然无法确认下一步，也可以咨询 Spark，了解这份 Recovery Map 的使用方式，或帮助判断下一步应该查看哪些资料。</p><button type="button" class="secondary" disabled title="Spark Recovery Map 帮助入口尚未正式开放">咨询 Spark · Coming soon</button></div>`,'recovery-help');
  return `<section class="card recovery-workspace-hero"><h2>你的 Recovery Map 已成功恢复</h2><p>你正在查看经完整性验证并在当前浏览器解密的恢复资料。</p><dl class="recovery-stats"><div><dt>账户 / 钱包</dt><dd>${report.account_count}</dd></div><div><dt>恢复条件</dt><dd>${report.condition_count}</dd></div><div class="attachment-stat"><dt>附件</dt><dd>${report.attachment_count}<small>｜ ${escape(fileTypeSummary(files))}</small></dd></div><div><dt>最后更新</dt><dd>${escape(report.updated_at?new Date(report.updated_at).toLocaleDateString('zh-CN'):'未记录')}</dd></div></dl>${report.assistant_count?`<p class="recovery-helper-note">已记录 ${report.assistant_count} 位协助人 / 机构</p>`:''}</section>${guideHtml()}${overviewSection}${messageSection}${accountsSection}${assistantSection}${archiveSection}${helpSection}<div data-attachment-status></div>`;
}

export function renderRecoveryMap(container,snapshot,{allowAttachmentDownloads=false}={}){
  const map=snapshot.knowledge_graph;
  if(map.schema_version===2)container.innerHTML=buildRecoveryWorkspaceHtml(snapshot);else{const groups=groupsFor(map);container.innerHTML=`<section class="card"><h2>${escape(map.vault_title)}</h2><div class="map-grid">${groups.map(([title,items,field])=>`<div class="map-card"><h3>${title}</h3>${items.length?items.map(i=>`<p><strong>${escape(i.label||i.type||`步骤 ${i.sequence}`)}</strong><br>${escape(i[field])}</p>`).join(''):'<p class="muted">未填写</p>'}</div>`).join('')}</div></section>`;}
  container.querySelectorAll('[data-recovery-guide-action]').forEach(link=>link.addEventListener('click',event=>event.stopPropagation()));
  container.querySelectorAll('[data-account-target]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();const account=container.querySelector(`#recovery-account-${domId(link.dataset.accountTarget)}`),section=container.querySelector('[data-workspace-section="04"]');if(!account||!section)return;section.open=true;container.querySelectorAll('.map-account').forEach(candidate=>{candidate.open=candidate===account;});account.setAttribute('tabindex','-1');account.scrollIntoView({behavior:'smooth',block:'start'});account.focus({preventScroll:true});}));
  container.querySelectorAll('[data-assistant-target]').forEach(link=>link.addEventListener('click',()=>{const section=container.querySelector('[data-workspace-section="05"]');if(!section)return;section.open=true;section.setAttribute('tabindex','-1');section.scrollIntoView({behavior:'smooth',block:'start'});section.focus({preventScroll:true});}));
  if(allowAttachmentDownloads)container.querySelectorAll('[data-attachment-id]').forEach(button=>button.onclick=async()=>{const status=container.querySelector('[data-attachment-status]');button.disabled=true;status.className='muted';status.textContent='正在验证附件…';try{const attachment=await recoverAttachmentForDownload(snapshot,button.dataset.attachmentId),saved=await saveBytesLocally({bytes:attachment.bytes,suggestedName:attachment.filename,mimeType:attachment.mimeType});status.className=saved.status==='cancelled'?'muted':'success';status.textContent=saved.status==='cancelled'?'已取消保存，未生成下载文件。':saved.status==='saved'?'附件已保存。':'浏览器下载已开始，请在下载列表中确认文件。';}catch{status.className='error';status.textContent='附件验证失败，已阻止操作。';}finally{button.disabled=false;}});
}
