import {recoverVaultArtifacts} from '../src/ui/vault-pipeline.js';
import {recoveryKitBuilder} from '../src/recovery-kit/recovery-kit-builder.js';
import {assertKitEvidencePair,validateMainnetEvidence,verifyMainnetArchiveWithRetry} from '../src/ui/mainnet-connector.js';
import {renderRecoveryMap} from './map-view.js';
import {summarizeVersionUpdateSource} from '../src/product-v2/version-update-diagnostics.js';
import {canonicalCreateUrl,CURRENT_TEST_RELEASE} from '../src/ui/canonical-customer-links.js';

const app=document.querySelector('#app'),recoveryStages=['正在读取恢复材料','正在获取加密资料','正在验证资料完整性','正在解密 Recovery Map','正在恢复附件','恢复完成'];
document.documentElement.dataset.recoveryBundleRelease=CURRENT_TEST_RELEASE;
const query=new URLSearchParams(location.search),versionUpdate=query.get('mode')==='version-update';
let recoveryInFlight=false,recoveredForUpdate=null,recoveredPasswordForUpdate='',recoveredSourceDiagnostics=null;
Object.defineProperty(window,'__LEGAVIK_VERSION_UPDATE_SOURCE_DIAGNOSTICS__',{value:()=>recoveredSourceDiagnostics?structuredClone(recoveredSourceDiagnostics):null,enumerable:false,writable:false,configurable:false});

app.innerHTML=`${versionUpdate?`<section class="card version-update-intro"><p class="eyebrow">LEGAVIK VERSION UPDATE</p><h1>更新 Recovery Map</h1><p>更新前，需要先恢复当前版本。恢复完成后，您可以只修改发生变化的内容，没有变化的信息无需调整。更新完成后，系统会生成新的 Recovery Map。</p><p class="version-update-current"><strong>当前版本：V${query.get('version_number')??'—'}</strong></p><button id="start-version-update">开始更新</button></section><section class="recovery-heading" hidden><h1>安全加载当前 Recovery Map</h1><p>请使用当前版本对应的 Recovery Materials 完成验证和恢复。</p></section>`:''}<section class="card recovery-entry" ${versionUpdate?'hidden':''}><div class="field"><label for="evidence">Mainnet Recovery Evidence</label><input id="evidence" type="file" accept=".json,application/json"></div><div class="field"><label for="kit">Recovery Kit</label><input id="kit" type="file" accept=".cjas,application/octet-stream"></div><div class="field"><label for="password">Recovery Password</label><input id="password" type="password" autocomplete="off"></div><button id="recover">${versionUpdate?'安全加载当前版本':'开始独立恢复'}</button><div id="message" role="status" aria-live="polite"></div></section><section class="card recovery-progress-card" hidden><h2>恢复进度</h2><p class="recovery-wait-note">资料正在恢复中，请保持页面开启。</p><ol id="recovery-stages"></ol></section><div id="result"></div>`;
document.querySelector('#start-version-update')?.addEventListener('click',()=>{document.querySelector('.version-update-intro').hidden=true;document.querySelector('.recovery-heading').hidden=false;document.querySelector('.recovery-entry').hidden=false;});
app.dataset.runtimeState='READY';

const recoverButton=document.querySelector('#recover'),progressCard=document.querySelector('.recovery-progress-card');
function stage(active){progressCard.hidden=active<0;document.querySelector('#recovery-stages').innerHTML=recoveryStages.map((label,index)=>`<li class="${index<active?'done':index===active?'active':''}"${index===active?' aria-current="step"':''}><span>${String(index+1).padStart(2,'0')}</span><strong>${label}</strong></li>`).join('');if(active===recoveryStages.length-1)progressCard.querySelector('.recovery-wait-note').textContent='资料已完成验证、解密和附件恢复。';}
function setRecovering(value){recoveryInFlight=value;recoverButton.disabled=value;recoverButton.classList.toggle('is-processing',value);recoverButton.setAttribute('aria-busy',String(value));recoverButton.textContent=value?'正在恢复…':versionUpdate?'安全加载当前版本':'开始独立恢复';}
function customerRecoveryError(error){if(error?.code==='KIT_UNLOCK_FAILED'||/Recovery Password is incorrect or Kit is damaged/i.test(String(error?.message??'')))return'恢复密码不正确，或所选恢复材料不匹配，请检查后重试。';return error?.message??'恢复未完成，请检查所选恢复材料后重试。';}
function renderRecovered(snapshot){const result=document.querySelector('#result');document.querySelector('.recovery-entry').hidden=true;recoveredForUpdate=versionUpdate?snapshot:null;if(versionUpdate){recoveredSourceDiagnostics=summarizeVersionUpdateSource(snapshot);app.dataset.versionUpdateSourceDiagnostics=JSON.stringify(recoveredSourceDiagnostics);}result.innerHTML=versionUpdate?'<section class="card recovery-complete"><p class="eyebrow">RECOVERY COMPLETE</p><h2>当前版本已完整载入</h2><p>现在可以直接检查并修改需要更新的内容。</p><div class="actions"><button id="continue-version-update">继续更新 Recovery Map</button></div></section>':`<section class="card recovery-complete"><p class="eyebrow">RECOVERY COMPLETE</p><h2>你的 Recovery Map 已成功恢复</h2><p>资料已完成验证、解密和附件恢复。</p><div class="actions"><button id="enter-recovery-map">进入 Recovery Map</button></div></section><div id="recovered-map" hidden></div>`;document.querySelector('#enter-recovery-map')?.addEventListener('click',()=>{const map=result.querySelector('#recovered-map');map.hidden=false;renderRecoveryMap(map,snapshot,{allowAttachmentDownloads:true});result.querySelector('.recovery-complete').hidden=true;progressCard.hidden=true;app.classList.add('recovery-workspace-active');document.body.classList.add('recovery-workspace-active');map.scrollIntoView({behavior:'auto',block:'start'});});document.querySelector('#continue-version-update')?.addEventListener('click',()=>{const channel=crypto.randomUUID(),target=canonicalCreateUrl({entry:'version-update',channel,map_row_id:query.get('map_row_id')??'',recovery_map_id:query.get('recovery_map_id')??'',version_row_id:query.get('version_row_id')??'',version_id:query.get('version_id')??'',version_number:query.get('version_number')??'',snapshot_id:query.get('snapshot_id')??'',test:query.get('test')??'1'});let child=null;const handler=event=>{if(event.origin!==location.origin||event.source!==child||event.data?.type!=='LEGAVIK_VERSION_UPDATE_READY'||event.data?.channel!==channel)return;child.postMessage({type:'LEGAVIK_VERSION_UPDATE_SOURCE',channel,snapshot:recoveredForUpdate,sourceDiagnostics:recoveredSourceDiagnostics,recoveryPassword:recoveredPasswordForUpdate,changeTypes:[]},location.origin);recoveredForUpdate=null;recoveredPasswordForUpdate='';removeEventListener('message',handler);};addEventListener('message',handler);child=open(target,'_blank');if(!child)removeEventListener('message',handler);});}

recoverButton.onclick=async()=>{
  if(recoveryInFlight)return;
  const message=document.querySelector('#message'),result=document.querySelector('#result'),evidenceFile=document.querySelector('#evidence').files[0],kitFile=document.querySelector('#kit').files[0];let password=document.querySelector('#password').value;
  message.textContent='';result.textContent='';
  if(!evidenceFile||!kitFile||!password){message.className='error';message.textContent='请选择 Mainnet Recovery Evidence、Recovery Kit 并输入 Recovery Password。';return;}
  setRecovering(true);
  try{
    stage(0);const evidence=validateMainnetEvidence(JSON.parse(await evidenceFile.text())),kitBytes=new Uint8Array(await kitFile.arrayBuffer()),kit=recoveryKitBuilder.parseKit(kitBytes);assertKitEvidencePair({kit,evidence});if(versionUpdate&&query.get('snapshot_id')&&kit.snapshot_id!==query.get('snapshot_id'))throw new Error('所选恢复材料不属于当前 Recovery Map 版本。');
    stage(1);const downloaded=await verifyMainnetArchiveWithRetry({evidence});if(!downloaded.verified)throw new Error('Mainnet 中的加密恢复版本尚未完整可用，请稍后重试。');
    stage(2);const archiveBytes=downloaded.bytes;if(archiveBytes.length!==evidence.archive_size)throw new Error('Mainnet Archive 大小校验失败。');
    stage(3);const recovered=await recoverVaultArtifacts({kitBytes,archiveBytes,password});if(versionUpdate)recoveredPasswordForUpdate=password;stage(4);
    renderRecovered(recovered.snapshot);stage(5);message.className='success';message.textContent='恢复成功。Recovery Map 与全部附件完整性验证通过。';
  }catch(error){stage(-1);message.className='error';message.textContent=customerRecoveryError(error);setRecovering(false);}
  finally{password='';document.querySelector('#password').value='';}
};
stage(-1);
